// Code generated by GoComply XSD2Go for Moov; DO NOT EDIT.
// Models for urn:iso:std:iso:20022:tech:xsd:camt.052.001.12
package camt_052_001_12

import (
	"encoding/xml"

	"github.com/moov-io/fedwire20022/pkg/fedwire"
)

// XSD Elements

type Document struct {
	XMLName xml.Name

	BkToCstmrAcctRpt BankToCustomerAccountReportV12 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 BkToCstmrAcctRpt"`
}

// XSD ComplexType declarations

type AccountIdentification4Choice struct {
	IBAN *IBAN2007Identifier            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 IBAN,omitempty"`
	Othr *GenericAccountIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Othr,omitempty"`
}

type AccountInterest4 struct {
	Tp     *InterestType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp,omitempty"`
	Rate   []*Rate4             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Rate,omitempty"`
	FrToDt *DateTimePeriod1     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FrToDt,omitempty"`
	Rsn    *Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Rsn,omitempty"`
	Tax    *TaxCharges2         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tax,omitempty"`
}

type AccountReport33 struct {
	Id           Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id"`
	RptPgntn     *Pagination1            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RptPgntn,omitempty"`
	ElctrncSeqNb *Number                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ElctrncSeqNb,omitempty"`
	RptgSeq      *SequenceRange1Choice   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RptgSeq,omitempty"`
	LglSeqNb     *Number                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 LglSeqNb,omitempty"`
	CreDtTm      *fedwire.ISODateTime    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CreDtTm,omitempty"`
	FrToDt       *DateTimePeriod1        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FrToDt,omitempty"`
	CpyDplctInd  *CopyDuplicate1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CpyDplctInd,omitempty"`
	RptgSrc      *ReportingSource1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RptgSrc,omitempty"`
	Acct         CashAccount43           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Acct"`
	RltdAcct     *CashAccount40          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RltdAcct,omitempty"`
	Intrst       []*AccountInterest4     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Intrst,omitempty"`
	Bal          []*CashBalance8         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Bal,omitempty"`
	TxsSummry    *TotalTransactions6     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TxsSummry,omitempty"`
	Ntry         []*ReportEntry14        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Ntry,omitempty"`
	AddtlRptInf  *Max500Text             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AddtlRptInf,omitempty"`
}

type AccountSchemeName1Choice struct {
	Cd    *ExternalAccountIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type ActiveCurrencyAndAmount struct {
	Value ActiveCurrencyAndAmountSimpleType `xml:",chardata"`
	Ccy   ActiveCurrencyCode                `xml:"Ccy,attr"`
}

type ActiveOrHistoricCurrencyAnd13DecimalAmount struct {
	Value ActiveOrHistoricCurrencyAnd13DecimalAmountSimpleType `xml:",chardata"`
	Ccy   ActiveOrHistoricCurrencyCode                         `xml:"Ccy,attr"`
}

type ActiveOrHistoricCurrencyAndAmount struct {
	Value ActiveOrHistoricCurrencyAndAmountSimpleType `xml:",chardata"`
	Ccy   ActiveOrHistoricCurrencyCode                `xml:"Ccy,attr"`
}

type ActiveOrHistoricCurrencyAndAmountRange2 struct {
	Amt       ImpliedCurrencyAmountRange1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Amt"`
	CdtDbtInd *CreditDebitCode                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdtDbtInd,omitempty"`
	Ccy       ActiveOrHistoricCurrencyCode      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Ccy"`
}

type AddressType3Choice struct {
	Cd    *AddressType2Code        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type AmountAndCurrencyExchange4 struct {
	InstdAmt      *AmountAndCurrencyExchangeDetails5   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 InstdAmt,omitempty"`
	TxAmt         *AmountAndCurrencyExchangeDetails5   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TxAmt,omitempty"`
	CntrValAmt    *AmountAndCurrencyExchangeDetails5   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CntrValAmt,omitempty"`
	AnncdPstngAmt *AmountAndCurrencyExchangeDetails5   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AnncdPstngAmt,omitempty"`
	PrtryAmt      []*AmountAndCurrencyExchangeDetails6 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PrtryAmt,omitempty"`
}

type AmountAndCurrencyExchangeDetails5 struct {
	Amt     ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Amt"`
	CcyXchg *CurrencyExchange24               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CcyXchg,omitempty"`
}

type AmountAndCurrencyExchangeDetails6 struct {
	Tp      Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp"`
	Amt     ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Amt"`
	CcyXchg *CurrencyExchange24               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CcyXchg,omitempty"`
}

type AmountAndDirection35 struct {
	Amt       NonNegativeDecimalNumber `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Amt"`
	CdtDbtInd CreditDebitCode          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdtDbtInd"`
}

type AmountRangeBoundary1 struct {
	BdryAmt ImpliedCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 BdryAmt"`
	Incl    YesNoIndicator           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Incl"`
}

type BalanceSubType1Choice struct {
	Cd    *ExternalBalanceSubType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type BalanceType10Choice struct {
	Cd    *ExternalBalanceType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type BalanceType13 struct {
	CdOrPrtry BalanceType10Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdOrPrtry"`
	SubTp     *BalanceSubType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SubTp,omitempty"`
}

type BankToCustomerAccountReportV12 struct {
	GrpHdr      GroupHeader116        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 GrpHdr"`
	Rpt         []AccountReport33     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Rpt"`
	SplmtryData []*SupplementaryData1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SplmtryData,omitempty"`
}

type BankTransactionCodeStructure4 struct {
	Domn  *BankTransactionCodeStructure5            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Domn,omitempty"`
	Prtry *ProprietaryBankTransactionCodeStructure1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type BankTransactionCodeStructure5 struct {
	Cd   ExternalBankTransactionDomain1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd"`
	Fmly BankTransactionCodeStructure6      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Fmly"`
}

type BankTransactionCodeStructure6 struct {
	Cd        ExternalBankTransactionFamily1Code    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd"`
	SubFmlyCd ExternalBankTransactionSubFamily1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SubFmlyCd"`
}

type BatchInformation2 struct {
	MsgId     *Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 MsgId,omitempty"`
	PmtInfId  *Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PmtInfId,omitempty"`
	NbOfTxs   *Max15NumericText                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 NbOfTxs,omitempty"`
	TtlAmt    *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TtlAmt,omitempty"`
	CdtDbtInd *CreditDebitCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdtDbtInd,omitempty"`
}

type BranchAndFinancialInstitutionIdentification8 struct {
	FinInstnId FinancialInstitutionIdentification23 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FinInstnId"`
	BrnchId    *BranchData5                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 BrnchId,omitempty"`
}

type BranchData5 struct {
	Id      *Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id,omitempty"`
	LEI     *LEIIdentifier   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 LEI,omitempty"`
	Nm      *Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Nm,omitempty"`
	PstlAdr *PostalAddress27 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PstlAdr,omitempty"`
}

type CardAggregated2 struct {
	AddtlSvc      *CardPaymentServiceType2Code          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AddtlSvc,omitempty"`
	TxCtgy        *ExternalCardTransactionCategory1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TxCtgy,omitempty"`
	SaleRcncltnId *Max35Text                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SaleRcncltnId,omitempty"`
	SeqNbRg       *CardSequenceNumberRange1             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SeqNbRg,omitempty"`
	TxDtRg        *DateOrDateTimePeriod1Choice          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TxDtRg,omitempty"`
}

type CardEntry5 struct {
	Card      *PaymentCard4        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Card,omitempty"`
	POI       *PointOfInteraction1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 POI,omitempty"`
	AggtdNtry *CardAggregated2     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AggtdNtry,omitempty"`
	PrePdAcct *CashAccount40       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PrePdAcct,omitempty"`
}

type CardIndividualTransaction2 struct {
	ICCRltdData    *Max1025Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ICCRltdData,omitempty"`
	PmtCntxt       *PaymentContext3                      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PmtCntxt,omitempty"`
	AddtlSvc       *CardPaymentServiceType2Code          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AddtlSvc,omitempty"`
	TxCtgy         *ExternalCardTransactionCategory1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TxCtgy,omitempty"`
	SaleRcncltnId  *Max35Text                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SaleRcncltnId,omitempty"`
	SaleRefNb      *Max35Text                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SaleRefNb,omitempty"`
	RePresntmntRsn *ExternalRePresentmentReason1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RePresntmntRsn,omitempty"`
	SeqNb          *Max35Text                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SeqNb,omitempty"`
	TxId           *TransactionIdentifier1               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TxId,omitempty"`
	Pdct           *Product2                             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Pdct,omitempty"`
	VldtnDt        *fedwire.ISODate                      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 VldtnDt,omitempty"`
	VldtnSeqNb     *Max35Text                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 VldtnSeqNb,omitempty"`
}

type CardSecurityInformation1 struct {
	CSCMgmt CSCManagement1Code   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CSCMgmt"`
	CSCVal  *Min3Max4NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CSCVal,omitempty"`
}

type CardSequenceNumberRange1 struct {
	FrstTx *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FrstTx,omitempty"`
	LastTx *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 LastTx,omitempty"`
}

type CardTransaction18 struct {
	Card      *PaymentCard4           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Card,omitempty"`
	POI       *PointOfInteraction1    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 POI,omitempty"`
	Tx        *CardTransaction3Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tx,omitempty"`
	PrePdAcct *CashAccount40          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PrePdAcct,omitempty"`
}

type CardTransaction3Choice struct {
	Aggtd *CardAggregated2            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Aggtd,omitempty"`
	Indv  *CardIndividualTransaction2 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Indv,omitempty"`
}

type CardholderAuthentication2 struct {
	AuthntcnMtd  AuthenticationMethod1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AuthntcnMtd"`
	AuthntcnNtty AuthenticationEntity1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AuthntcnNtty"`
}

type CashAccount40 struct {
	Id   *AccountIdentification4Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id,omitempty"`
	Tp   *CashAccountType2Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp,omitempty"`
	Ccy  *ActiveOrHistoricCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Ccy,omitempty"`
	Nm   *Max70Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Nm,omitempty"`
	Prxy *ProxyAccountIdentification1  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prxy,omitempty"`
}

type CashAccount43 struct {
	Id   *AccountIdentification4Choice                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id,omitempty"`
	Tp   *CashAccountType2Choice                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp,omitempty"`
	Ccy  *ActiveOrHistoricCurrencyCode                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Ccy,omitempty"`
	Nm   *Max70Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Nm,omitempty"`
	Prxy *ProxyAccountIdentification1                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prxy,omitempty"`
	Ownr *PartyIdentification272                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Ownr,omitempty"`
	Svcr *BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Svcr,omitempty"`
}

type CashAccountType2Choice struct {
	Cd    *ExternalCashAccountType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type CashAvailability1 struct {
	Dt        CashAvailabilityDate1Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Dt"`
	Amt       ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Amt"`
	CdtDbtInd CreditDebitCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdtDbtInd"`
}

type CashAvailabilityDate1Choice struct {
	NbOfDays *Max15PlusSignedNumericText `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 NbOfDays,omitempty"`
	ActlDt   *fedwire.ISODate            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ActlDt,omitempty"`
}

type CashBalance8 struct {
	Tp        BalanceType13                     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp"`
	CdtLine   []*CreditLine3                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdtLine,omitempty"`
	Amt       ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Amt"`
	CdtDbtInd CreditDebitCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdtDbtInd"`
	Dt        DateAndDateTime2Choice            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Dt"`
	Avlbty    []*CashAvailability1              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Avlbty,omitempty"`
}

type CashDeposit1 struct {
	NoteDnmtn ActiveCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 NoteDnmtn"`
	NbOfNotes Max15NumericText        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 NbOfNotes"`
	Amt       ActiveCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Amt"`
}

type CategoryPurpose1Choice struct {
	Cd    *ExternalCategoryPurpose1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type ChargeType3Choice struct {
	Cd    *ExternalChargeType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *GenericIdentification3  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type Charges15 struct {
	TtlChrgsAndTaxAmt *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TtlChrgsAndTaxAmt,omitempty"`
	Rcrd              []*ChargesRecord8                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Rcrd,omitempty"`
}

type ChargesRecord8 struct {
	Amt         ActiveOrHistoricCurrencyAndAmount             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Amt"`
	CdtDbtInd   *CreditDebitCode                              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdtDbtInd,omitempty"`
	ChrgInclInd *ChargeIncludedIndicator                      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ChrgInclInd,omitempty"`
	Tp          *ChargeType3Choice                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp,omitempty"`
	Rate        *PercentageRate                               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Rate,omitempty"`
	Br          *ChargeBearerType1Code                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Br,omitempty"`
	Agt         *BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Agt,omitempty"`
	Tax         *TaxCharges2                                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tax,omitempty"`
}

type ClearingSystemIdentification2Choice struct {
	Cd    *ExternalClearingSystemIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type ClearingSystemMemberIdentification2 struct {
	ClrSysId *ClearingSystemIdentification2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ClrSysId,omitempty"`
	MmbId    Max35Text                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 MmbId"`
}

type Contact13 struct {
	NmPrfx    *NamePrefix2Code             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 NmPrfx,omitempty"`
	Nm        *Max140Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Nm,omitempty"`
	PhneNb    *PhoneNumber                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PhneNb,omitempty"`
	MobNb     *PhoneNumber                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 MobNb,omitempty"`
	FaxNb     *PhoneNumber                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FaxNb,omitempty"`
	URLAdr    *Max2048Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 URLAdr,omitempty"`
	EmailAdr  *Max256Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 EmailAdr,omitempty"`
	EmailPurp *Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 EmailPurp,omitempty"`
	JobTitl   *Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 JobTitl,omitempty"`
	Rspnsblty *Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Rspnsblty,omitempty"`
	Dept      *Max70Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Dept,omitempty"`
	Othr      []*OtherContact1             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Othr,omitempty"`
	PrefrdMtd *PreferredContactMethod2Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PrefrdMtd,omitempty"`
}

type CorporateAction9 struct {
	EvtTp Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 EvtTp"`
	EvtId Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 EvtId"`
}

type CreditLine3 struct {
	Incl TrueFalseIndicator                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Incl"`
	Tp   *CreditLineType1Choice             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp,omitempty"`
	Amt  *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Amt,omitempty"`
	Dt   *DateAndDateTime2Choice            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Dt,omitempty"`
}

type CreditLineType1Choice struct {
	Cd    *ExternalCreditLineType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type CreditorReferenceInformation3 struct {
	Tp  *CreditorReferenceType3 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp,omitempty"`
	Ref *Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Ref,omitempty"`
}

type CreditorReferenceType2Choice struct {
	Cd    *ExternalCreditorReferenceType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type CreditorReferenceType3 struct {
	CdOrPrtry CreditorReferenceType2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdOrPrtry"`
	Issr      *Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Issr,omitempty"`
}

type CurrencyExchange24 struct {
	SrcCcy       ActiveOrHistoricCurrencyCode  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SrcCcy"`
	TrgtCcy      *ActiveOrHistoricCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TrgtCcy,omitempty"`
	UnitCcy      *ActiveOrHistoricCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 UnitCcy,omitempty"`
	XchgRate     BaseOneRate                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 XchgRate"`
	CtrctId      *Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CtrctId,omitempty"`
	QtnDt        *fedwire.ISODateTime          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 QtnDt,omitempty"`
	XchgRateBase *PositiveNumber               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 XchgRateBase,omitempty"`
}

type DateAndDateTime2Choice struct {
	Dt   *fedwire.ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Dt,omitempty"`
	DtTm *fedwire.ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 DtTm,omitempty"`
}

type DateAndPlaceOfBirth1 struct {
	BirthDt     fedwire.ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 BirthDt"`
	PrvcOfBirth *Max35Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PrvcOfBirth,omitempty"`
	CityOfBirth Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CityOfBirth"`
	CtryOfBirth CountryCode     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CtryOfBirth"`
}

type DateAndType1 struct {
	Tp DateType2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp"`
	Dt fedwire.ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Dt"`
}

type DateOrDateTimePeriod1Choice struct {
	Dt   *DatePeriod2     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Dt,omitempty"`
	DtTm *DateTimePeriod1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 DtTm,omitempty"`
}

type DatePeriod2 struct {
	FrDt fedwire.ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FrDt"`
	ToDt fedwire.ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ToDt"`
}

type DateTimePeriod1 struct {
	FrDtTm fedwire.ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FrDtTm"`
	ToDtTm fedwire.ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ToDtTm"`
}

type DateType2Choice struct {
	Cd    *ExternalDateType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type DisplayCapabilities1 struct {
	DispTp    UserInterface2Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 DispTp"`
	NbOfLines Max3NumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 NbOfLines"`
	LineWidth Max3NumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 LineWidth"`
}

type DocumentAdjustment1 struct {
	Amt       ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Amt"`
	CdtDbtInd *CreditDebitCode                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdtDbtInd,omitempty"`
	Rsn       *Max4Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Rsn,omitempty"`
	AddtlInf  *Max140Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AddtlInf,omitempty"`
}

type DocumentAmount1 struct {
	Tp  DocumentAmountType1Choice         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp"`
	Amt ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Amt"`
}

type DocumentAmountType1Choice struct {
	Cd    *ExternalDocumentAmountType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type DocumentLineIdentification1 struct {
	Tp     *DocumentLineType1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp,omitempty"`
	Nb     *Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Nb,omitempty"`
	RltdDt *fedwire.ISODate   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RltdDt,omitempty"`
}

type DocumentLineInformation2 struct {
	Id   []DocumentLineIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id"`
	Desc *Max2048Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Desc,omitempty"`
	Amt  *RemittanceAmount4            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Amt,omitempty"`
}

type DocumentLineType1 struct {
	CdOrPrtry DocumentLineType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdOrPrtry"`
	Issr      *Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Issr,omitempty"`
}

type DocumentLineType1Choice struct {
	Cd    *ExternalDocumentLineType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type DocumentType1 struct {
	CdOrPrtry DocumentType2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdOrPrtry"`
	Issr      *Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Issr,omitempty"`
}

type DocumentType2Choice struct {
	Cd    *ExternalDocumentType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type EntryDetails13 struct {
	Btch   *BatchInformation2    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Btch,omitempty"`
	TxDtls []*EntryTransaction14 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TxDtls,omitempty"`
}

type EntryStatus1Choice struct {
	Cd    *ExternalEntryStatus1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type EntryTransaction14 struct {
	Refs        *TransactionReferences6            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Refs,omitempty"`
	Amt         *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Amt,omitempty"`
	CdtDbtInd   *CreditDebitCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdtDbtInd,omitempty"`
	AmtDtls     *AmountAndCurrencyExchange4        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AmtDtls,omitempty"`
	Avlbty      []*CashAvailability1               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Avlbty,omitempty"`
	BkTxCd      *BankTransactionCodeStructure4     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 BkTxCd,omitempty"`
	Chrgs       *Charges15                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Chrgs,omitempty"`
	Intrst      *TransactionInterest4              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Intrst,omitempty"`
	RltdPties   *TransactionParties12              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RltdPties,omitempty"`
	RltdAgts    *TransactionAgents6                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RltdAgts,omitempty"`
	LclInstrm   *LocalInstrument2Choice            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 LclInstrm,omitempty"`
	PmtTpInf    *PaymentTypeInformation27          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PmtTpInf,omitempty"`
	Purp        *Purpose2Choice                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Purp,omitempty"`
	RltdRmtInf  []*RemittanceLocation8             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RltdRmtInf,omitempty"`
	RmtInf      *RemittanceInformation22           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RmtInf,omitempty"`
	RltdDts     *TransactionDates3                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RltdDts,omitempty"`
	RltdPric    *TransactionPrice4Choice           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RltdPric,omitempty"`
	RltdQties   []*TransactionQuantities3Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RltdQties,omitempty"`
	FinInstrmId *SecurityIdentification19          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FinInstrmId,omitempty"`
	Tax         *TaxData1                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tax,omitempty"`
	RtrInf      *PaymentReturnReason8              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RtrInf,omitempty"`
	CorpActn    *CorporateAction9                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CorpActn,omitempty"`
	SfkpgAcct   *SecuritiesAccount19               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SfkpgAcct,omitempty"`
	CshDpst     []*CashDeposit1                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CshDpst,omitempty"`
	CardTx      *CardTransaction18                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CardTx,omitempty"`
	AddtlTxInf  *Max500Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AddtlTxInf,omitempty"`
	SplmtryData []*SupplementaryData1              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SplmtryData,omitempty"`
}

type FinancialIdentificationSchemeName1Choice struct {
	Cd    *ExternalFinancialInstitutionIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type FinancialInstitutionIdentification23 struct {
	BICFI       *BICFIDec2014Identifier              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 BICFI,omitempty"`
	ClrSysMmbId *ClearingSystemMemberIdentification2 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ClrSysMmbId,omitempty"`
	LEI         *LEIIdentifier                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 LEI,omitempty"`
	Nm          *Max140Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Nm,omitempty"`
	PstlAdr     *PostalAddress27                     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PstlAdr,omitempty"`
	Othr        *GenericFinancialIdentification1     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Othr,omitempty"`
}

type FinancialInstrumentQuantity1Choice struct {
	Unit     *DecimalNumber            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Unit,omitempty"`
	FaceAmt  *ImpliedCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FaceAmt,omitempty"`
	AmtsdVal *ImpliedCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AmtsdVal,omitempty"`
}

type FromToAmountRange1 struct {
	FrAmt AmountRangeBoundary1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FrAmt"`
	ToAmt AmountRangeBoundary1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ToAmt"`
}

type Garnishment4 struct {
	Tp                GarnishmentType1                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp"`
	Grnshee           *PartyIdentification272            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Grnshee,omitempty"`
	GrnshmtAdmstr     *PartyIdentification272            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 GrnshmtAdmstr,omitempty"`
	RefNb             *Max140Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RefNb,omitempty"`
	Dt                *fedwire.ISODate                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Dt,omitempty"`
	RmtdAmt           *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RmtdAmt,omitempty"`
	FmlyMdclInsrncInd *TrueFalseIndicator                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FmlyMdclInsrncInd,omitempty"`
	MplyeeTermntnInd  *TrueFalseIndicator                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 MplyeeTermntnInd,omitempty"`
}

type GarnishmentType1 struct {
	CdOrPrtry GarnishmentType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdOrPrtry"`
	Issr      *Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Issr,omitempty"`
}

type GarnishmentType1Choice struct {
	Cd    *ExternalGarnishmentType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type GenericAccountIdentification1 struct {
	Id      Max34Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id"`
	SchmeNm *AccountSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SchmeNm,omitempty"`
	Issr    *Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Issr,omitempty"`
}

type GenericFinancialIdentification1 struct {
	Id      Max35Text                                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id"`
	SchmeNm *FinancialIdentificationSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SchmeNm,omitempty"`
	Issr    *Max35Text                                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Issr,omitempty"`
}

type GenericIdentification1 struct {
	Id      Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id"`
	SchmeNm *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SchmeNm,omitempty"`
	Issr    *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Issr,omitempty"`
}

type GenericIdentification3 struct {
	Id   Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id"`
	Issr *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Issr,omitempty"`
}

type GenericIdentification30 struct {
	Id      Exact4AlphaNumericText `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id"`
	Issr    Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Issr"`
	SchmeNm *Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SchmeNm,omitempty"`
}

type GenericIdentification32 struct {
	Id     Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id"`
	Tp     *PartyType3Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp,omitempty"`
	Issr   *PartyType4Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Issr,omitempty"`
	ShrtNm *Max35Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ShrtNm,omitempty"`
}

type GenericOrganisationIdentification3 struct {
	Id      Max256Text                                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id"`
	SchmeNm *OrganisationIdentificationSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SchmeNm,omitempty"`
	Issr    *Max35Text                                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Issr,omitempty"`
}

type GenericPersonIdentification2 struct {
	Id      Max256Text                             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id"`
	SchmeNm *PersonIdentificationSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SchmeNm,omitempty"`
	Issr    *Max35Text                             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Issr,omitempty"`
}

type GroupHeader116 struct {
	MsgId       Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 MsgId"`
	CreDtTm     fedwire.ISODateTime     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CreDtTm"`
	MsgRcpt     *PartyIdentification272 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 MsgRcpt,omitempty"`
	MsgPgntn    *Pagination1            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 MsgPgntn,omitempty"`
	OrgnlBizQry *OriginalBusinessQuery1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 OrgnlBizQry,omitempty"`
	AddtlInf    *Max500Text             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AddtlInf,omitempty"`
}

type IdentificationSource3Choice struct {
	Cd    *ExternalFinancialInstrumentIdentificationType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type ImpliedCurrencyAmountRange1Choice struct {
	FrAmt   *AmountRangeBoundary1     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FrAmt,omitempty"`
	ToAmt   *AmountRangeBoundary1     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ToAmt,omitempty"`
	FrToAmt *FromToAmountRange1       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FrToAmt,omitempty"`
	EQAmt   *ImpliedCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 EQAmt,omitempty"`
	NEQAmt  *ImpliedCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 NEQAmt,omitempty"`
}

type InterestRecord2 struct {
	Amt       ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Amt"`
	CdtDbtInd CreditDebitCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdtDbtInd"`
	Tp        *InterestType1Choice              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp,omitempty"`
	Rate      *Rate4                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Rate,omitempty"`
	FrToDt    *DateTimePeriod1                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FrToDt,omitempty"`
	Rsn       *Max35Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Rsn,omitempty"`
	Tax       *TaxCharges2                      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tax,omitempty"`
}

type InterestType1Choice struct {
	Cd    *InterestType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type LocalInstrument2Choice struct {
	Cd    *ExternalLocalInstrument1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type MessageIdentification2 struct {
	MsgNmId *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 MsgNmId,omitempty"`
	MsgId   *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 MsgId,omitempty"`
}

type NameAndAddress18 struct {
	Nm  Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Nm"`
	Adr PostalAddress27 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Adr"`
}

type NumberAndSumOfTransactions1 struct {
	NbOfNtries *Max15NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 NbOfNtries,omitempty"`
	Sum        *DecimalNumber    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Sum,omitempty"`
}

type NumberAndSumOfTransactions4 struct {
	NbOfNtries *Max15NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 NbOfNtries,omitempty"`
	Sum        *DecimalNumber        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Sum,omitempty"`
	TtlNetNtry *AmountAndDirection35 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TtlNetNtry,omitempty"`
}

type OrganisationIdentification39 struct {
	AnyBIC *AnyBICDec2014Identifier              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AnyBIC,omitempty"`
	LEI    *LEIIdentifier                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 LEI,omitempty"`
	Othr   []*GenericOrganisationIdentification3 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Othr,omitempty"`
}

type OrganisationIdentificationSchemeName1Choice struct {
	Cd    *ExternalOrganisationIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type OriginalAndCurrentQuantities1 struct {
	FaceAmt  ImpliedCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FaceAmt"`
	AmtsdVal ImpliedCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AmtsdVal"`
}

type OriginalBusinessQuery1 struct {
	MsgId   Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 MsgId"`
	MsgNmId *Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 MsgNmId,omitempty"`
	CreDtTm *fedwire.ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CreDtTm,omitempty"`
}

type OtherContact1 struct {
	ChanlTp Max4Text    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ChanlTp"`
	Id      *Max128Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id,omitempty"`
}

type OtherIdentification1 struct {
	Id  Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id"`
	Sfx *Max16Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Sfx,omitempty"`
	Tp  IdentificationSource3Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp"`
}

type Pagination1 struct {
	PgNb      Max5NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PgNb"`
	LastPgInd YesNoIndicator  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 LastPgInd"`
}

type Party50Choice struct {
	Pty *PartyIdentification272                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Pty,omitempty"`
	Agt *BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Agt,omitempty"`
}

type Party52Choice struct {
	OrgId  *OrganisationIdentification39 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 OrgId,omitempty"`
	PrvtId *PersonIdentification18       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PrvtId,omitempty"`
}

type PartyIdentification272 struct {
	Nm        *Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Nm,omitempty"`
	PstlAdr   *PostalAddress27 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PstlAdr,omitempty"`
	Id        *Party52Choice   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id,omitempty"`
	CtryOfRes *CountryCode     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CtryOfRes,omitempty"`
	CtctDtls  *Contact13       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CtctDtls,omitempty"`
}

type PaymentCard4 struct {
	PlainCardData *PlainCardData1         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PlainCardData,omitempty"`
	CardCtryCd    *Exact3NumericText      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CardCtryCd,omitempty"`
	CardBrnd      *GenericIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CardBrnd,omitempty"`
	AddtlCardData *Max70Text              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AddtlCardData,omitempty"`
}

type PaymentContext3 struct {
	CardPres       *TrueFalseIndicator          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CardPres,omitempty"`
	CrdhldrPres    *TrueFalseIndicator          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CrdhldrPres,omitempty"`
	OnLineCntxt    *TrueFalseIndicator          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 OnLineCntxt,omitempty"`
	AttndncCntxt   *AttendanceContext1Code      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AttndncCntxt,omitempty"`
	TxEnvt         *TransactionEnvironment1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TxEnvt,omitempty"`
	TxChanl        *TransactionChannel1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TxChanl,omitempty"`
	AttndntMsgCpbl *TrueFalseIndicator          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AttndntMsgCpbl,omitempty"`
	AttndntLang    *ISO2ALanguageCode           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AttndntLang,omitempty"`
	CardDataNtryMd CardDataReading1Code         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CardDataNtryMd"`
	FllbckInd      *TrueFalseIndicator          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FllbckInd,omitempty"`
	AuthntcnMtd    *CardholderAuthentication2   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AuthntcnMtd,omitempty"`
}

type PaymentReturnReason8 struct {
	OrgnlBkTxCd *BankTransactionCodeStructure4 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 OrgnlBkTxCd,omitempty"`
	Orgtr       *PartyIdentification272        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Orgtr,omitempty"`
	Rsn         *ReturnReason5Choice           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Rsn,omitempty"`
	AddtlInf    []*Max105Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AddtlInf,omitempty"`
}

type PaymentTypeInformation27 struct {
	InstrPrty *Priority2Code          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 InstrPrty,omitempty"`
	ClrChanl  *ClearingChannel2Code   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ClrChanl,omitempty"`
	SvcLvl    []*ServiceLevel8Choice  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SvcLvl,omitempty"`
	LclInstrm *LocalInstrument2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 LclInstrm,omitempty"`
	SeqTp     *SequenceType3Code      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SeqTp,omitempty"`
	CtgyPurp  *CategoryPurpose1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CtgyPurp,omitempty"`
}

type PersonIdentification18 struct {
	DtAndPlcOfBirth *DateAndPlaceOfBirth1           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 DtAndPlcOfBirth,omitempty"`
	Othr            []*GenericPersonIdentification2 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Othr,omitempty"`
}

type PersonIdentificationSchemeName1Choice struct {
	Cd    *ExternalPersonIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type PlainCardData1 struct {
	PAN        Min8Max28NumericText      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PAN"`
	CardSeqNb  *Min2Max3NumericText      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CardSeqNb,omitempty"`
	FctvDt     *ISOYearMonth             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FctvDt,omitempty"`
	XpryDt     ISOYearMonth              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 XpryDt"`
	SvcCd      *Exact3NumericText        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SvcCd,omitempty"`
	TrckData   []*TrackData1             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TrckData,omitempty"`
	CardSctyCd *CardSecurityInformation1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CardSctyCd,omitempty"`
}

type PointOfInteraction1 struct {
	Id       GenericIdentification32          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id"`
	SysNm    *Max70Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SysNm,omitempty"`
	GrpId    *Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 GrpId,omitempty"`
	Cpblties *PointOfInteractionCapabilities1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cpblties,omitempty"`
	Cmpnt    []*PointOfInteractionComponent1  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cmpnt,omitempty"`
}

type PointOfInteractionCapabilities1 struct {
	CardRdngCpblties      []*CardDataReading1Code                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CardRdngCpblties,omitempty"`
	CrdhldrVrfctnCpblties []*CardholderVerificationCapability1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CrdhldrVrfctnCpblties,omitempty"`
	OnLineCpblties        *OnLineCapability1Code                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 OnLineCpblties,omitempty"`
	DispCpblties          []*DisplayCapabilities1                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 DispCpblties,omitempty"`
	PrtLineWidth          *Max3NumericText                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PrtLineWidth,omitempty"`
}

type PointOfInteractionComponent1 struct {
	POICmpntTp POIComponentType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 POICmpntTp"`
	ManfctrId  *Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ManfctrId,omitempty"`
	Mdl        *Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Mdl,omitempty"`
	VrsnNb     *Max16Text            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 VrsnNb,omitempty"`
	SrlNb      *Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SrlNb,omitempty"`
	ApprvlNb   []*Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ApprvlNb,omitempty"`
}

type PostalAddress27 struct {
	AdrTp       *AddressType3Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AdrTp,omitempty"`
	CareOf      *Max140Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CareOf,omitempty"`
	Dept        *Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Dept,omitempty"`
	SubDept     *Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SubDept,omitempty"`
	StrtNm      *Max140Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 StrtNm,omitempty"`
	BldgNb      *Max16Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 BldgNb,omitempty"`
	BldgNm      *Max140Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 BldgNm,omitempty"`
	Flr         *Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Flr,omitempty"`
	UnitNb      *Max16Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 UnitNb,omitempty"`
	PstBx       *Max16Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PstBx,omitempty"`
	Room        *Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Room,omitempty"`
	PstCd       *Max16Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PstCd,omitempty"`
	TwnNm       *Max140Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TwnNm,omitempty"`
	TwnLctnNm   *Max140Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TwnLctnNm,omitempty"`
	DstrctNm    *Max140Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 DstrctNm,omitempty"`
	CtrySubDvsn *Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CtrySubDvsn,omitempty"`
	Ctry        *CountryCode        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Ctry,omitempty"`
	AdrLine     []*Max70Text        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AdrLine,omitempty"`
}

type Price7 struct {
	Tp  YieldedOrValueType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp"`
	Val PriceRateOrAmount3Choice  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Val"`
}

type PriceRateOrAmount3Choice struct {
	Rate *PercentageRate                             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Rate,omitempty"`
	Amt  *ActiveOrHistoricCurrencyAnd13DecimalAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Amt,omitempty"`
}

type Product2 struct {
	PdctCd       Max70Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PdctCd"`
	UnitOfMeasr  *UnitOfMeasure1Code       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 UnitOfMeasr,omitempty"`
	PdctQty      *DecimalNumber            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PdctQty,omitempty"`
	UnitPric     *ImpliedCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 UnitPric,omitempty"`
	PdctAmt      *ImpliedCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PdctAmt,omitempty"`
	TaxTp        *Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TaxTp,omitempty"`
	AddtlPdctInf *Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AddtlPdctInf,omitempty"`
}

type ProprietaryAgent5 struct {
	Tp  Max35Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp"`
	Agt BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Agt"`
}

type ProprietaryBankTransactionCodeStructure1 struct {
	Cd   Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd"`
	Issr *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Issr,omitempty"`
}

type ProprietaryDate3 struct {
	Tp Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp"`
	Dt DateAndDateTime2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Dt"`
}

type ProprietaryParty6 struct {
	Tp  Max35Text     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp"`
	Pty Party50Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Pty"`
}

type ProprietaryPrice2 struct {
	Tp   Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp"`
	Pric ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Pric"`
}

type ProprietaryQuantity1 struct {
	Tp  Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp"`
	Qty Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Qty"`
}

type ProprietaryReference1 struct {
	Tp  Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp"`
	Ref Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Ref"`
}

type ProxyAccountIdentification1 struct {
	Tp *ProxyAccountType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp,omitempty"`
	Id Max2048Text              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id"`
}

type ProxyAccountType1Choice struct {
	Cd    *ExternalProxyAccountType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type Purpose2Choice struct {
	Cd    *ExternalPurpose1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type Rate4 struct {
	Tp      RateType4Choice                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp"`
	VldtyRg *ActiveOrHistoricCurrencyAndAmountRange2 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 VldtyRg,omitempty"`
}

type RateType4Choice struct {
	Pctg *PercentageRate `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Pctg,omitempty"`
	Othr *Max35Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Othr,omitempty"`
}

type ReferredDocumentInformation8 struct {
	Tp       *DocumentType1              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp,omitempty"`
	Nb       *Max35Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Nb,omitempty"`
	RltdDt   *DateAndType1               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RltdDt,omitempty"`
	LineDtls []*DocumentLineInformation2 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 LineDtls,omitempty"`
}

type RemittanceAmount4 struct {
	RmtAmtAndTp       []*DocumentAmount1     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RmtAmtAndTp,omitempty"`
	AdjstmntAmtAndRsn []*DocumentAdjustment1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AdjstmntAmtAndRsn,omitempty"`
}

type RemittanceInformation22 struct {
	Ustrd []*Max140Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Ustrd,omitempty"`
	Strd  []*StructuredRemittanceInformation18 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Strd,omitempty"`
}

type RemittanceLocation8 struct {
	RmtId       *Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RmtId,omitempty"`
	RmtLctnDtls []*RemittanceLocationData2 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RmtLctnDtls,omitempty"`
}

type RemittanceLocationData2 struct {
	Mtd        RemittanceLocationMethod2Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Mtd"`
	ElctrncAdr *Max2048Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ElctrncAdr,omitempty"`
	PstlAdr    *NameAndAddress18             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PstlAdr,omitempty"`
}

type ReportEntry14 struct {
	NtryRef       *Max35Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 NtryRef,omitempty"`
	Amt           ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Amt"`
	CdtDbtInd     CreditDebitCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdtDbtInd"`
	RvslInd       *TrueFalseIndicator               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RvslInd,omitempty"`
	Sts           EntryStatus1Choice                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Sts"`
	BookgDt       *DateAndDateTime2Choice           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 BookgDt,omitempty"`
	ValDt         *DateAndDateTime2Choice           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ValDt,omitempty"`
	AcctSvcrRef   *Max35Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AcctSvcrRef,omitempty"`
	Avlbty        []*CashAvailability1              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Avlbty,omitempty"`
	BkTxCd        BankTransactionCodeStructure4     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 BkTxCd"`
	ComssnWvrInd  *YesNoIndicator                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ComssnWvrInd,omitempty"`
	AddtlInfInd   *MessageIdentification2           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AddtlInfInd,omitempty"`
	AmtDtls       *AmountAndCurrencyExchange4       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AmtDtls,omitempty"`
	Chrgs         *Charges15                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Chrgs,omitempty"`
	TechInptChanl *TechnicalInputChannel1Choice     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TechInptChanl,omitempty"`
	Intrst        *TransactionInterest4             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Intrst,omitempty"`
	CardTx        *CardEntry5                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CardTx,omitempty"`
	NtryDtls      []*EntryDetails13                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 NtryDtls,omitempty"`
	AddtlNtryInf  *Max500Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AddtlNtryInf,omitempty"`
}

type ReportingSource1Choice struct {
	Cd    *ExternalReportingSource1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type ReturnReason5Choice struct {
	Cd    *ExternalReturnReason1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type SecuritiesAccount19 struct {
	Id Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id"`
	Tp *GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp,omitempty"`
	Nm *Max70Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Nm,omitempty"`
}

type SecurityIdentification19 struct {
	ISIN   *ISINOct2015Identifier  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ISIN,omitempty"`
	OthrId []*OtherIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 OthrId,omitempty"`
	Desc   *Max140Text             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Desc,omitempty"`
}

type SequenceRange1 struct {
	FrSeq Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FrSeq"`
	ToSeq Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ToSeq"`
}

type SequenceRange1Choice struct {
	FrSeq   *Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FrSeq,omitempty"`
	ToSeq   *Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ToSeq,omitempty"`
	FrToSeq []SequenceRange1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FrToSeq"`
	EQSeq   []Max35Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 EQSeq"`
	NEQSeq  []Max35Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 NEQSeq"`
}

type ServiceLevel8Choice struct {
	Cd    *ExternalServiceLevel1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type StructuredRemittanceInformation18 struct {
	RfrdDocInf  []*ReferredDocumentInformation8 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RfrdDocInf,omitempty"`
	RfrdDocAmt  *RemittanceAmount4              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RfrdDocAmt,omitempty"`
	CdtrRefInf  *CreditorReferenceInformation3  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdtrRefInf,omitempty"`
	Invcr       *PartyIdentification272         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Invcr,omitempty"`
	Invcee      *PartyIdentification272         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Invcee,omitempty"`
	TaxRmt      *TaxData1                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TaxRmt,omitempty"`
	GrnshmtRmt  *Garnishment4                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 GrnshmtRmt,omitempty"`
	AddtlRmtInf []*Max140Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AddtlRmtInf,omitempty"`
}

type SupplementaryData1 struct {
	PlcAndNm *Max350Text                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

type TaxAmount3 struct {
	Rate         *PercentageRate                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Rate,omitempty"`
	TaxblBaseAmt *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TaxblBaseAmt,omitempty"`
	TtlAmt       *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TtlAmt,omitempty"`
	Dtls         []*TaxRecordDetails3               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Dtls,omitempty"`
}

type TaxAuthorisation1 struct {
	Titl *Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Titl,omitempty"`
	Nm   *Max140Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Nm,omitempty"`
}

type TaxCharges2 struct {
	Id   *Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Id,omitempty"`
	Rate *PercentageRate                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Rate,omitempty"`
	Amt  *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Amt,omitempty"`
}

type TaxData1 struct {
	Cdtr            *TaxParty1                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cdtr,omitempty"`
	Dbtr            *TaxParty2                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Dbtr,omitempty"`
	UltmtDbtr       *TaxParty2                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 UltmtDbtr,omitempty"`
	AdmstnZone      *Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AdmstnZone,omitempty"`
	RefNb           *Max140Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RefNb,omitempty"`
	Mtd             *Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Mtd,omitempty"`
	TtlTaxblBaseAmt *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TtlTaxblBaseAmt,omitempty"`
	TtlTaxAmt       *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TtlTaxAmt,omitempty"`
	Dt              *fedwire.ISODate                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Dt,omitempty"`
	SeqNb           *Number                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SeqNb,omitempty"`
	Rcrd            []*TaxRecord3                      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Rcrd,omitempty"`
}

type TaxParty1 struct {
	TaxId  *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TaxId,omitempty"`
	RegnId *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RegnId,omitempty"`
	TaxTp  *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TaxTp,omitempty"`
}

type TaxParty2 struct {
	TaxId   *Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TaxId,omitempty"`
	RegnId  *Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RegnId,omitempty"`
	TaxTp   *Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TaxTp,omitempty"`
	Authstn *TaxAuthorisation1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Authstn,omitempty"`
}

type TaxPeriod3 struct {
	Yr     *ISOYear              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Yr,omitempty"`
	Tp     *TaxRecordPeriod1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp,omitempty"`
	FrToDt *DatePeriod2          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FrToDt,omitempty"`
}

type TaxRecord3 struct {
	Tp       *Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Tp,omitempty"`
	Ctgy     *Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Ctgy,omitempty"`
	CtgyDtls *Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CtgyDtls,omitempty"`
	DbtrSts  *Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 DbtrSts,omitempty"`
	CertId   *Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CertId,omitempty"`
	FrmsCd   *Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FrmsCd,omitempty"`
	Prd      *TaxPeriod3 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prd,omitempty"`
	TaxAmt   *TaxAmount3 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TaxAmt,omitempty"`
	AddtlInf *Max140Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AddtlInf,omitempty"`
}

type TaxRecordDetails3 struct {
	Prd *TaxPeriod3                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prd,omitempty"`
	Amt ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Amt"`
}

type TechnicalInputChannel1Choice struct {
	Cd    *ExternalTechnicalInputChannel1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cd,omitempty"`
	Prtry *Max35Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type TotalTransactions6 struct {
	TtlNtries          *NumberAndSumOfTransactions4     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TtlNtries,omitempty"`
	TtlCdtNtries       *NumberAndSumOfTransactions1     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TtlCdtNtries,omitempty"`
	TtlDbtNtries       *NumberAndSumOfTransactions1     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TtlDbtNtries,omitempty"`
	TtlNtriesPerBkTxCd []*TotalsPerBankTransactionCode5 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TtlNtriesPerBkTxCd,omitempty"`
}

type TotalsPerBankTransactionCode5 struct {
	NbOfNtries *Max15NumericText             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 NbOfNtries,omitempty"`
	Sum        *DecimalNumber                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Sum,omitempty"`
	TtlNetNtry *AmountAndDirection35         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TtlNetNtry,omitempty"`
	CdtNtries  *NumberAndSumOfTransactions1  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdtNtries,omitempty"`
	DbtNtries  *NumberAndSumOfTransactions1  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 DbtNtries,omitempty"`
	FcstInd    *TrueFalseIndicator           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 FcstInd,omitempty"`
	BkTxCd     BankTransactionCodeStructure4 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 BkTxCd"`
	Avlbty     []*CashAvailability1          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Avlbty,omitempty"`
	Dt         *DateAndDateTime2Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Dt,omitempty"`
}

type TrackData1 struct {
	TrckNb  *Exact1NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TrckNb,omitempty"`
	TrckVal Max140Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TrckVal"`
}

type TransactionAgents6 struct {
	InstgAgt   *BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 InstgAgt,omitempty"`
	InstdAgt   *BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 InstdAgt,omitempty"`
	DbtrAgt    *BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 DbtrAgt,omitempty"`
	CdtrAgt    *BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdtrAgt,omitempty"`
	IntrmyAgt1 *BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 IntrmyAgt1,omitempty"`
	IntrmyAgt2 *BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 IntrmyAgt2,omitempty"`
	IntrmyAgt3 *BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 IntrmyAgt3,omitempty"`
	RcvgAgt    *BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 RcvgAgt,omitempty"`
	DlvrgAgt   *BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 DlvrgAgt,omitempty"`
	IssgAgt    *BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 IssgAgt,omitempty"`
	SttlmPlc   *BranchAndFinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 SttlmPlc,omitempty"`
	Prtry      []*ProprietaryAgent5                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type TransactionDates3 struct {
	AccptncDtTm             *fedwire.ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AccptncDtTm,omitempty"`
	TradActvtyCtrctlSttlmDt *fedwire.ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TradActvtyCtrctlSttlmDt,omitempty"`
	TradDt                  *fedwire.ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TradDt,omitempty"`
	IntrBkSttlmDt           *fedwire.ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 IntrBkSttlmDt,omitempty"`
	StartDt                 *fedwire.ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 StartDt,omitempty"`
	EndDt                   *fedwire.ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 EndDt,omitempty"`
	TxDtTm                  *fedwire.ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TxDtTm,omitempty"`
	Prtry                   []*ProprietaryDate3  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type TransactionIdentifier1 struct {
	TxDtTm fedwire.ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TxDtTm"`
	TxRef  Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TxRef"`
}

type TransactionInterest4 struct {
	TtlIntrstAndTaxAmt *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TtlIntrstAndTaxAmt,omitempty"`
	Rcrd               []*InterestRecord2                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Rcrd,omitempty"`
}

type TransactionParties12 struct {
	InitgPty  *Party50Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 InitgPty,omitempty"`
	Dbtr      *Party50Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Dbtr,omitempty"`
	DbtrAcct  *CashAccount40       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 DbtrAcct,omitempty"`
	UltmtDbtr *Party50Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 UltmtDbtr,omitempty"`
	Cdtr      *Party50Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Cdtr,omitempty"`
	CdtrAcct  *CashAccount40       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 CdtrAcct,omitempty"`
	UltmtCdtr *Party50Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 UltmtCdtr,omitempty"`
	TradgPty  *Party50Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TradgPty,omitempty"`
	Prtry     []*ProprietaryParty6 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type TransactionPrice4Choice struct {
	DealPric *Price7             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 DealPric,omitempty"`
	Prtry    []ProprietaryPrice2 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry"`
}

type TransactionQuantities3Choice struct {
	Qty                *FinancialInstrumentQuantity1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Qty,omitempty"`
	OrgnlAndCurFaceAmt *OriginalAndCurrentQuantities1      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 OrgnlAndCurFaceAmt,omitempty"`
	Prtry              *ProprietaryQuantity1               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type TransactionReferences6 struct {
	MsgId             *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 MsgId,omitempty"`
	AcctSvcrRef       *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AcctSvcrRef,omitempty"`
	PmtInfId          *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PmtInfId,omitempty"`
	InstrId           *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 InstrId,omitempty"`
	EndToEndId        *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 EndToEndId,omitempty"`
	UETR              *UUIDv4Identifier        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 UETR,omitempty"`
	TxId              *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 TxId,omitempty"`
	MndtId            *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 MndtId,omitempty"`
	ChqNb             *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ChqNb,omitempty"`
	ClrSysRef         *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ClrSysRef,omitempty"`
	AcctOwnrTxId      *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AcctOwnrTxId,omitempty"`
	AcctSvcrTxId      *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 AcctSvcrTxId,omitempty"`
	MktInfrstrctrTxId *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 MktInfrstrctrTxId,omitempty"`
	PrcgId            *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 PrcgId,omitempty"`
	Prtry             []*ProprietaryReference1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Prtry,omitempty"`
}

type YieldedOrValueType1Choice struct {
	Yldd  *YesNoIndicator      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 Yldd,omitempty"`
	ValTp *PriceValueType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.12 ValTp,omitempty"`
}

// XSD SimpleType declarations

type ActiveCurrencyAndAmountSimpleType fedwire.Amount

type ActiveCurrencyCode string

type ActiveOrHistoricCurrencyAnd13DecimalAmountSimpleType float64

type ActiveOrHistoricCurrencyAndAmountSimpleType fedwire.Amount

type ActiveOrHistoricCurrencyCode string

type AddressType2Code string

const AddressType2CodeAddr AddressType2Code = "ADDR"
const AddressType2CodePbox AddressType2Code = "PBOX"
const AddressType2CodeHome AddressType2Code = "HOME"
const AddressType2CodeBizz AddressType2Code = "BIZZ"
const AddressType2CodeMlto AddressType2Code = "MLTO"
const AddressType2CodeDlvy AddressType2Code = "DLVY"

type AnyBICDec2014Identifier string

type AttendanceContext1Code string

const AttendanceContext1CodeAttd AttendanceContext1Code = "ATTD"
const AttendanceContext1CodeSatt AttendanceContext1Code = "SATT"
const AttendanceContext1CodeUatt AttendanceContext1Code = "UATT"

type AuthenticationEntity1Code string

const AuthenticationEntity1CodeIccd AuthenticationEntity1Code = "ICCD"
const AuthenticationEntity1CodeAgnt AuthenticationEntity1Code = "AGNT"
const AuthenticationEntity1CodeMerc AuthenticationEntity1Code = "MERC"

type AuthenticationMethod1Code string

const AuthenticationMethod1CodeUknw AuthenticationMethod1Code = "UKNW"
const AuthenticationMethod1CodeByps AuthenticationMethod1Code = "BYPS"
const AuthenticationMethod1CodeNpin AuthenticationMethod1Code = "NPIN"
const AuthenticationMethod1CodeFpin AuthenticationMethod1Code = "FPIN"
const AuthenticationMethod1CodeCpsg AuthenticationMethod1Code = "CPSG"
const AuthenticationMethod1CodePpsg AuthenticationMethod1Code = "PPSG"
const AuthenticationMethod1CodeManu AuthenticationMethod1Code = "MANU"
const AuthenticationMethod1CodeMerc AuthenticationMethod1Code = "MERC"
const AuthenticationMethod1CodeScrt AuthenticationMethod1Code = "SCRT"
const AuthenticationMethod1CodeSnct AuthenticationMethod1Code = "SNCT"
const AuthenticationMethod1CodeScnl AuthenticationMethod1Code = "SCNL"

type BICFIDec2014Identifier string

type BaseOneRate float64

type CSCManagement1Code string

const CSCManagement1CodePrst CSCManagement1Code = "PRST"
const CSCManagement1CodeByps CSCManagement1Code = "BYPS"
const CSCManagement1CodeUnrd CSCManagement1Code = "UNRD"
const CSCManagement1CodeNcsc CSCManagement1Code = "NCSC"

type CardDataReading1Code string

const CardDataReading1CodeTagc CardDataReading1Code = "TAGC"
const CardDataReading1CodePhys CardDataReading1Code = "PHYS"
const CardDataReading1CodeBrcd CardDataReading1Code = "BRCD"
const CardDataReading1CodeMgst CardDataReading1Code = "MGST"
const CardDataReading1CodeCicc CardDataReading1Code = "CICC"
const CardDataReading1CodeDfle CardDataReading1Code = "DFLE"
const CardDataReading1CodeCtls CardDataReading1Code = "CTLS"
const CardDataReading1CodeEctl CardDataReading1Code = "ECTL"

type CardPaymentServiceType2Code string

const CardPaymentServiceType2CodeAggr CardPaymentServiceType2Code = "AGGR"
const CardPaymentServiceType2CodeDccv CardPaymentServiceType2Code = "DCCV"
const CardPaymentServiceType2CodeGrtt CardPaymentServiceType2Code = "GRTT"
const CardPaymentServiceType2CodeInsp CardPaymentServiceType2Code = "INSP"
const CardPaymentServiceType2CodeLoyt CardPaymentServiceType2Code = "LOYT"
const CardPaymentServiceType2CodeNres CardPaymentServiceType2Code = "NRES"
const CardPaymentServiceType2CodePuco CardPaymentServiceType2Code = "PUCO"
const CardPaymentServiceType2CodeRecp CardPaymentServiceType2Code = "RECP"
const CardPaymentServiceType2CodeSoaf CardPaymentServiceType2Code = "SOAF"
const CardPaymentServiceType2CodeUnaf CardPaymentServiceType2Code = "UNAF"
const CardPaymentServiceType2CodeVcau CardPaymentServiceType2Code = "VCAU"

type CardholderVerificationCapability1Code string

const CardholderVerificationCapability1CodeMnsg CardholderVerificationCapability1Code = "MNSG"
const CardholderVerificationCapability1CodeNpin CardholderVerificationCapability1Code = "NPIN"
const CardholderVerificationCapability1CodeFcpn CardholderVerificationCapability1Code = "FCPN"
const CardholderVerificationCapability1CodeFepn CardholderVerificationCapability1Code = "FEPN"
const CardholderVerificationCapability1CodeFdsg CardholderVerificationCapability1Code = "FDSG"
const CardholderVerificationCapability1CodeFbio CardholderVerificationCapability1Code = "FBIO"
const CardholderVerificationCapability1CodeMnvr CardholderVerificationCapability1Code = "MNVR"
const CardholderVerificationCapability1CodeFbig CardholderVerificationCapability1Code = "FBIG"
const CardholderVerificationCapability1CodeApki CardholderVerificationCapability1Code = "APKI"
const CardholderVerificationCapability1CodePkis CardholderVerificationCapability1Code = "PKIS"
const CardholderVerificationCapability1CodeChdt CardholderVerificationCapability1Code = "CHDT"
const CardholderVerificationCapability1CodeScec CardholderVerificationCapability1Code = "SCEC"

type ChargeBearerType1Code string

const ChargeBearerType1CodeDebt ChargeBearerType1Code = "DEBT"
const ChargeBearerType1CodeCred ChargeBearerType1Code = "CRED"
const ChargeBearerType1CodeShar ChargeBearerType1Code = "SHAR"
const ChargeBearerType1CodeSlev ChargeBearerType1Code = "SLEV"

type ChargeIncludedIndicator bool

type ClearingChannel2Code string

const ClearingChannel2CodeRtgs ClearingChannel2Code = "RTGS"
const ClearingChannel2CodeRtns ClearingChannel2Code = "RTNS"
const ClearingChannel2CodeMpns ClearingChannel2Code = "MPNS"
const ClearingChannel2CodeBook ClearingChannel2Code = "BOOK"

type CopyDuplicate1Code string

const CopyDuplicate1CodeCodu CopyDuplicate1Code = "CODU"
const CopyDuplicate1CodeCopy CopyDuplicate1Code = "COPY"
const CopyDuplicate1CodeDupl CopyDuplicate1Code = "DUPL"

type CountryCode string

type CreditDebitCode string

const CreditDebitCodeCrdt CreditDebitCode = "CRDT"
const CreditDebitCodeDbit CreditDebitCode = "DBIT"

type DecimalNumber float64

type Exact1NumericText string

type Exact3NumericText string

type Exact4AlphaNumericText string

type ExternalAccountIdentification1Code string

type ExternalBalanceSubType1Code string

type ExternalBalanceType1Code string

type ExternalBankTransactionDomain1Code string

type ExternalBankTransactionFamily1Code string

type ExternalBankTransactionSubFamily1Code string

type ExternalCardTransactionCategory1Code string

type ExternalCashAccountType1Code string

type ExternalCategoryPurpose1Code string

type ExternalChargeType1Code string

type ExternalClearingSystemIdentification1Code string

type ExternalCreditLineType1Code string

type ExternalCreditorReferenceType1Code string

type ExternalDateType1Code string

type ExternalDocumentAmountType1Code string

type ExternalDocumentLineType1Code string

type ExternalDocumentType1Code string

type ExternalEntryStatus1Code string

type ExternalFinancialInstitutionIdentification1Code string

type ExternalFinancialInstrumentIdentificationType1Code string

type ExternalGarnishmentType1Code string

type ExternalLocalInstrument1Code string

type ExternalOrganisationIdentification1Code string

type ExternalPersonIdentification1Code string

type ExternalProxyAccountType1Code string

type ExternalPurpose1Code string

type ExternalRePresentmentReason1Code string

type ExternalReportingSource1Code string

type ExternalReturnReason1Code string

type ExternalServiceLevel1Code string

type ExternalTechnicalInputChannel1Code string

type IBAN2007Identifier string

type ISINOct2015Identifier string

type ISO2ALanguageCode string

type ISOYear string

type ISOYearMonth string

type ImpliedCurrencyAndAmount float64

type InterestType1Code string

const InterestType1CodeIndy InterestType1Code = "INDY"
const InterestType1CodeOvrn InterestType1Code = "OVRN"

type LEIIdentifier string

type Max1025Text string

type Max105Text string

type Max128Text string

type Max140Text string

type Max15NumericText string

type Max15PlusSignedNumericText string

type Max16Text string

type Max2048Text string

type Max256Text string

type Max34Text string

type Max350Text string

type Max35Text string

type Max3NumericText string

type Max4Text string

type Max500Text string

type Max5NumericText string

type Max70Text string

type Min2Max3NumericText string

type Min3Max4NumericText string

type Min8Max28NumericText string

type NamePrefix2Code string

const NamePrefix2CodeDoct NamePrefix2Code = "DOCT"
const NamePrefix2CodeMadm NamePrefix2Code = "MADM"
const NamePrefix2CodeMiss NamePrefix2Code = "MISS"
const NamePrefix2CodeMist NamePrefix2Code = "MIST"
const NamePrefix2CodeMiks NamePrefix2Code = "MIKS"

type NonNegativeDecimalNumber float64

type Number float64

type OnLineCapability1Code string

const OnLineCapability1CodeOfln OnLineCapability1Code = "OFLN"
const OnLineCapability1CodeOnln OnLineCapability1Code = "ONLN"
const OnLineCapability1CodeSmon OnLineCapability1Code = "SMON"

type POIComponentType1Code string

const POIComponentType1CodeSoft POIComponentType1Code = "SOFT"
const POIComponentType1CodeEmvk POIComponentType1Code = "EMVK"
const POIComponentType1CodeEmvo POIComponentType1Code = "EMVO"
const POIComponentType1CodeMrit POIComponentType1Code = "MRIT"
const POIComponentType1CodeChit POIComponentType1Code = "CHIT"
const POIComponentType1CodeSecm POIComponentType1Code = "SECM"
const POIComponentType1CodePedv POIComponentType1Code = "PEDV"

type PartyType3Code string

const PartyType3CodeOpoi PartyType3Code = "OPOI"
const PartyType3CodeMerc PartyType3Code = "MERC"
const PartyType3CodeAccp PartyType3Code = "ACCP"
const PartyType3CodeItag PartyType3Code = "ITAG"
const PartyType3CodeAcqr PartyType3Code = "ACQR"
const PartyType3CodeCiss PartyType3Code = "CISS"
const PartyType3CodeDlis PartyType3Code = "DLIS"

type PartyType4Code string

const PartyType4CodeMerc PartyType4Code = "MERC"
const PartyType4CodeAccp PartyType4Code = "ACCP"
const PartyType4CodeItag PartyType4Code = "ITAG"
const PartyType4CodeAcqr PartyType4Code = "ACQR"
const PartyType4CodeCiss PartyType4Code = "CISS"
const PartyType4CodeTaxh PartyType4Code = "TAXH"

type PercentageRate float64

type PhoneNumber string

type PositiveNumber float64

type PreferredContactMethod2Code string

const PreferredContactMethod2CodeMail PreferredContactMethod2Code = "MAIL"
const PreferredContactMethod2CodeFaxx PreferredContactMethod2Code = "FAXX"
const PreferredContactMethod2CodeLett PreferredContactMethod2Code = "LETT"
const PreferredContactMethod2CodeCell PreferredContactMethod2Code = "CELL"
const PreferredContactMethod2CodeOnli PreferredContactMethod2Code = "ONLI"
const PreferredContactMethod2CodePhon PreferredContactMethod2Code = "PHON"

type PriceValueType1Code string

const PriceValueType1CodeDisc PriceValueType1Code = "DISC"
const PriceValueType1CodePrem PriceValueType1Code = "PREM"
const PriceValueType1CodeParv PriceValueType1Code = "PARV"

type Priority2Code string

const Priority2CodeHigh Priority2Code = "HIGH"
const Priority2CodeNorm Priority2Code = "NORM"

type RemittanceLocationMethod2Code string

const RemittanceLocationMethod2CodeFaxi RemittanceLocationMethod2Code = "FAXI"
const RemittanceLocationMethod2CodeEdic RemittanceLocationMethod2Code = "EDIC"
const RemittanceLocationMethod2CodeUrid RemittanceLocationMethod2Code = "URID"
const RemittanceLocationMethod2CodeEmal RemittanceLocationMethod2Code = "EMAL"
const RemittanceLocationMethod2CodePost RemittanceLocationMethod2Code = "POST"
const RemittanceLocationMethod2CodeSmsm RemittanceLocationMethod2Code = "SMSM"

type SequenceType3Code string

const SequenceType3CodeFrst SequenceType3Code = "FRST"
const SequenceType3CodeRcur SequenceType3Code = "RCUR"
const SequenceType3CodeFnal SequenceType3Code = "FNAL"
const SequenceType3CodeOoff SequenceType3Code = "OOFF"
const SequenceType3CodeRpre SequenceType3Code = "RPRE"

type TaxRecordPeriod1Code string

const TaxRecordPeriod1CodeMm01 TaxRecordPeriod1Code = "MM01"
const TaxRecordPeriod1CodeMm02 TaxRecordPeriod1Code = "MM02"
const TaxRecordPeriod1CodeMm03 TaxRecordPeriod1Code = "MM03"
const TaxRecordPeriod1CodeMm04 TaxRecordPeriod1Code = "MM04"
const TaxRecordPeriod1CodeMm05 TaxRecordPeriod1Code = "MM05"
const TaxRecordPeriod1CodeMm06 TaxRecordPeriod1Code = "MM06"
const TaxRecordPeriod1CodeMm07 TaxRecordPeriod1Code = "MM07"
const TaxRecordPeriod1CodeMm08 TaxRecordPeriod1Code = "MM08"
const TaxRecordPeriod1CodeMm09 TaxRecordPeriod1Code = "MM09"
const TaxRecordPeriod1CodeMm10 TaxRecordPeriod1Code = "MM10"
const TaxRecordPeriod1CodeMm11 TaxRecordPeriod1Code = "MM11"
const TaxRecordPeriod1CodeMm12 TaxRecordPeriod1Code = "MM12"
const TaxRecordPeriod1CodeQtr1 TaxRecordPeriod1Code = "QTR1"
const TaxRecordPeriod1CodeQtr2 TaxRecordPeriod1Code = "QTR2"
const TaxRecordPeriod1CodeQtr3 TaxRecordPeriod1Code = "QTR3"
const TaxRecordPeriod1CodeQtr4 TaxRecordPeriod1Code = "QTR4"
const TaxRecordPeriod1CodeHlf1 TaxRecordPeriod1Code = "HLF1"
const TaxRecordPeriod1CodeHlf2 TaxRecordPeriod1Code = "HLF2"

type TransactionChannel1Code string

const TransactionChannel1CodeMail TransactionChannel1Code = "MAIL"
const TransactionChannel1CodeTlph TransactionChannel1Code = "TLPH"
const TransactionChannel1CodeEcom TransactionChannel1Code = "ECOM"
const TransactionChannel1CodeTvpy TransactionChannel1Code = "TVPY"

type TransactionEnvironment1Code string

const TransactionEnvironment1CodeMerc TransactionEnvironment1Code = "MERC"
const TransactionEnvironment1CodePriv TransactionEnvironment1Code = "PRIV"
const TransactionEnvironment1CodePubl TransactionEnvironment1Code = "PUBL"

type TrueFalseIndicator bool

type UUIDv4Identifier string

type UnitOfMeasure1Code string

const UnitOfMeasure1CodePiec UnitOfMeasure1Code = "PIEC"
const UnitOfMeasure1CodeTons UnitOfMeasure1Code = "TONS"
const UnitOfMeasure1CodeFoot UnitOfMeasure1Code = "FOOT"
const UnitOfMeasure1CodeGbga UnitOfMeasure1Code = "GBGA"
const UnitOfMeasure1CodeUsga UnitOfMeasure1Code = "USGA"
const UnitOfMeasure1CodeGram UnitOfMeasure1Code = "GRAM"
const UnitOfMeasure1CodeInch UnitOfMeasure1Code = "INCH"
const UnitOfMeasure1CodeKilo UnitOfMeasure1Code = "KILO"
const UnitOfMeasure1CodePund UnitOfMeasure1Code = "PUND"
const UnitOfMeasure1CodeMetr UnitOfMeasure1Code = "METR"
const UnitOfMeasure1CodeCmet UnitOfMeasure1Code = "CMET"
const UnitOfMeasure1CodeMmet UnitOfMeasure1Code = "MMET"
const UnitOfMeasure1CodeLitr UnitOfMeasure1Code = "LITR"
const UnitOfMeasure1CodeCeli UnitOfMeasure1Code = "CELI"
const UnitOfMeasure1CodeMili UnitOfMeasure1Code = "MILI"
const UnitOfMeasure1CodeGbou UnitOfMeasure1Code = "GBOU"
const UnitOfMeasure1CodeUsou UnitOfMeasure1Code = "USOU"
const UnitOfMeasure1CodeGbqa UnitOfMeasure1Code = "GBQA"
const UnitOfMeasure1CodeUsqa UnitOfMeasure1Code = "USQA"
const UnitOfMeasure1CodeGbpi UnitOfMeasure1Code = "GBPI"
const UnitOfMeasure1CodeUspi UnitOfMeasure1Code = "USPI"
const UnitOfMeasure1CodeMile UnitOfMeasure1Code = "MILE"
const UnitOfMeasure1CodeKmet UnitOfMeasure1Code = "KMET"
const UnitOfMeasure1CodeYard UnitOfMeasure1Code = "YARD"
const UnitOfMeasure1CodeSqki UnitOfMeasure1Code = "SQKI"
const UnitOfMeasure1CodeHect UnitOfMeasure1Code = "HECT"
const UnitOfMeasure1CodeAres UnitOfMeasure1Code = "ARES"
const UnitOfMeasure1CodeSmet UnitOfMeasure1Code = "SMET"
const UnitOfMeasure1CodeScmt UnitOfMeasure1Code = "SCMT"
const UnitOfMeasure1CodeSmil UnitOfMeasure1Code = "SMIL"
const UnitOfMeasure1CodeSqmi UnitOfMeasure1Code = "SQMI"
const UnitOfMeasure1CodeSqya UnitOfMeasure1Code = "SQYA"
const UnitOfMeasure1CodeSqfo UnitOfMeasure1Code = "SQFO"
const UnitOfMeasure1CodeSqin UnitOfMeasure1Code = "SQIN"
const UnitOfMeasure1CodeAcre UnitOfMeasure1Code = "ACRE"

type UserInterface2Code string

const UserInterface2CodeMdsp UserInterface2Code = "MDSP"
const UserInterface2CodeCdsp UserInterface2Code = "CDSP"

type YesNoIndicator bool
