// Code generated by GoComply XSD2Go for Moov; DO NOT EDIT.
// Models for urn:iso:std:iso:20022:tech:xsd:camt.052.001.09
package camt_052_001_09

import (
	"encoding/xml"

	"github.com/moov-io/fedwire20022/pkg/fedwire"
)

// XSD Elements

type Document struct {
	XMLName xml.Name

	BkToCstmrAcctRpt BankToCustomerAccountReportV09 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 BkToCstmrAcctRpt"`
}

// XSD ComplexType declarations

type AccountIdentification4Choice struct {
	IBAN *IBAN2007Identifier            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 IBAN,omitempty"`
	Othr *GenericAccountIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Othr,omitempty"`
}

type AccountInterest4 struct {
	Tp     *InterestType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp,omitempty"`
	Rate   []*Rate4             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Rate,omitempty"`
	FrToDt *DateTimePeriod1     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FrToDt,omitempty"`
	Rsn    *Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Rsn,omitempty"`
	Tax    *TaxCharges2         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tax,omitempty"`
}

type AccountReport30 struct {
	Id           Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id"`
	RptPgntn     *Pagination1            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RptPgntn,omitempty"`
	ElctrncSeqNb *Number                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ElctrncSeqNb,omitempty"`
	RptgSeq      *SequenceRange1Choice   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RptgSeq,omitempty"`
	LglSeqNb     *Number                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 LglSeqNb,omitempty"`
	CreDtTm      *fedwire.ISODateTime    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CreDtTm,omitempty"`
	FrToDt       *DateTimePeriod1        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FrToDt,omitempty"`
	CpyDplctInd  *CopyDuplicate1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CpyDplctInd,omitempty"`
	RptgSrc      *ReportingSource1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RptgSrc,omitempty"`
	Acct         CashAccount41           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Acct"`
	RltdAcct     *CashAccount40          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RltdAcct,omitempty"`
	Intrst       []*AccountInterest4     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Intrst,omitempty"`
	Bal          []*CashBalance8         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Bal,omitempty"`
	TxsSummry    *TotalTransactions6     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TxsSummry,omitempty"`
	Ntry         []*ReportEntry11        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Ntry,omitempty"`
	AddtlRptInf  *Max500Text             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AddtlRptInf,omitempty"`
}

type AccountSchemeName1Choice struct {
	Cd    *ExternalAccountIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type ActiveCurrencyAndAmount struct {
	Value ActiveCurrencyAndAmountSimpleType `xml:",chardata"`
	Ccy   ActiveCurrencyCode                `xml:"Ccy,attr"`
}

type ActiveOrHistoricCurrencyAnd13DecimalAmount struct {
	Value ActiveOrHistoricCurrencyAnd13DecimalAmountSimpleType `xml:",chardata"`
	Ccy   ActiveOrHistoricCurrencyCode                         `xml:"Ccy,attr"`
}

type ActiveOrHistoricCurrencyAndAmount struct {
	Value ActiveOrHistoricCurrencyAndAmountSimpleType `xml:",chardata"`
	Ccy   ActiveOrHistoricCurrencyCode                `xml:"Ccy,attr"`
}

type ActiveOrHistoricCurrencyAndAmountRange2 struct {
	Amt       ImpliedCurrencyAmountRange1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Amt"`
	CdtDbtInd *CreditDebitCode                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdtDbtInd,omitempty"`
	Ccy       ActiveOrHistoricCurrencyCode      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Ccy"`
}

type AddressType3Choice struct {
	Cd    *AddressType2Code        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type AmountAndCurrencyExchange3 struct {
	InstdAmt      *AmountAndCurrencyExchangeDetails3   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 InstdAmt,omitempty"`
	TxAmt         *AmountAndCurrencyExchangeDetails3   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TxAmt,omitempty"`
	CntrValAmt    *AmountAndCurrencyExchangeDetails3   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CntrValAmt,omitempty"`
	AnncdPstngAmt *AmountAndCurrencyExchangeDetails3   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AnncdPstngAmt,omitempty"`
	PrtryAmt      []*AmountAndCurrencyExchangeDetails4 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PrtryAmt,omitempty"`
}

type AmountAndCurrencyExchangeDetails3 struct {
	Amt     ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Amt"`
	CcyXchg *CurrencyExchange5                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CcyXchg,omitempty"`
}

type AmountAndCurrencyExchangeDetails4 struct {
	Tp      Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp"`
	Amt     ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Amt"`
	CcyXchg *CurrencyExchange5                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CcyXchg,omitempty"`
}

type AmountAndDirection35 struct {
	Amt       NonNegativeDecimalNumber `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Amt"`
	CdtDbtInd CreditDebitCode          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdtDbtInd"`
}

type AmountRangeBoundary1 struct {
	BdryAmt ImpliedCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 BdryAmt"`
	Incl    YesNoIndicator           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Incl"`
}

type BalanceSubType1Choice struct {
	Cd    *ExternalBalanceSubType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type BalanceType10Choice struct {
	Cd    *ExternalBalanceType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type BalanceType13 struct {
	CdOrPrtry BalanceType10Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdOrPrtry"`
	SubTp     *BalanceSubType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SubTp,omitempty"`
}

type BankToCustomerAccountReportV09 struct {
	GrpHdr      GroupHeader81         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 GrpHdr"`
	Rpt         []AccountReport30     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Rpt"`
	SplmtryData []*SupplementaryData1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SplmtryData,omitempty"`
}

type BankTransactionCodeStructure4 struct {
	Domn  *BankTransactionCodeStructure5            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Domn,omitempty"`
	Prtry *ProprietaryBankTransactionCodeStructure1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type BankTransactionCodeStructure5 struct {
	Cd   ExternalBankTransactionDomain1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd"`
	Fmly BankTransactionCodeStructure6      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Fmly"`
}

type BankTransactionCodeStructure6 struct {
	Cd        ExternalBankTransactionFamily1Code    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd"`
	SubFmlyCd ExternalBankTransactionSubFamily1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SubFmlyCd"`
}

type BatchInformation2 struct {
	MsgId     *Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 MsgId,omitempty"`
	PmtInfId  *Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PmtInfId,omitempty"`
	NbOfTxs   *Max15NumericText                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 NbOfTxs,omitempty"`
	TtlAmt    *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TtlAmt,omitempty"`
	CdtDbtInd *CreditDebitCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdtDbtInd,omitempty"`
}

type BranchAndFinancialInstitutionIdentification6 struct {
	FinInstnId FinancialInstitutionIdentification18 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FinInstnId"`
	BrnchId    *BranchData3                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 BrnchId,omitempty"`
}

type BranchData3 struct {
	Id      *Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id,omitempty"`
	LEI     *LEIIdentifier   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 LEI,omitempty"`
	Nm      *Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Nm,omitempty"`
	PstlAdr *PostalAddress24 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PstlAdr,omitempty"`
}

type CardAggregated2 struct {
	AddtlSvc      *CardPaymentServiceType2Code          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AddtlSvc,omitempty"`
	TxCtgy        *ExternalCardTransactionCategory1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TxCtgy,omitempty"`
	SaleRcncltnId *Max35Text                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SaleRcncltnId,omitempty"`
	SeqNbRg       *CardSequenceNumberRange1             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SeqNbRg,omitempty"`
	TxDtRg        *DateOrDateTimePeriod1Choice          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TxDtRg,omitempty"`
}

type CardEntry5 struct {
	Card      *PaymentCard4        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Card,omitempty"`
	POI       *PointOfInteraction1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 POI,omitempty"`
	AggtdNtry *CardAggregated2     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AggtdNtry,omitempty"`
	PrePdAcct *CashAccount40       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PrePdAcct,omitempty"`
}

type CardIndividualTransaction2 struct {
	ICCRltdData    *Max1025Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ICCRltdData,omitempty"`
	PmtCntxt       *PaymentContext3                      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PmtCntxt,omitempty"`
	AddtlSvc       *CardPaymentServiceType2Code          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AddtlSvc,omitempty"`
	TxCtgy         *ExternalCardTransactionCategory1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TxCtgy,omitempty"`
	SaleRcncltnId  *Max35Text                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SaleRcncltnId,omitempty"`
	SaleRefNb      *Max35Text                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SaleRefNb,omitempty"`
	RePresntmntRsn *ExternalRePresentmentReason1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RePresntmntRsn,omitempty"`
	SeqNb          *Max35Text                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SeqNb,omitempty"`
	TxId           *TransactionIdentifier1               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TxId,omitempty"`
	Pdct           *Product2                             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Pdct,omitempty"`
	VldtnDt        *fedwire.ISODate                      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 VldtnDt,omitempty"`
	VldtnSeqNb     *Max35Text                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 VldtnSeqNb,omitempty"`
}

type CardSecurityInformation1 struct {
	CSCMgmt CSCManagement1Code   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CSCMgmt"`
	CSCVal  *Min3Max4NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CSCVal,omitempty"`
}

type CardSequenceNumberRange1 struct {
	FrstTx *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FrstTx,omitempty"`
	LastTx *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 LastTx,omitempty"`
}

type CardTransaction18 struct {
	Card      *PaymentCard4           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Card,omitempty"`
	POI       *PointOfInteraction1    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 POI,omitempty"`
	Tx        *CardTransaction3Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tx,omitempty"`
	PrePdAcct *CashAccount40          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PrePdAcct,omitempty"`
}

type CardTransaction3Choice struct {
	Aggtd *CardAggregated2            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Aggtd,omitempty"`
	Indv  *CardIndividualTransaction2 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Indv,omitempty"`
}

type CardholderAuthentication2 struct {
	AuthntcnMtd  AuthenticationMethod1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AuthntcnMtd"`
	AuthntcnNtty AuthenticationEntity1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AuthntcnNtty"`
}

type CashAccount40 struct {
	Id   *AccountIdentification4Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id,omitempty"`
	Tp   *CashAccountType2Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp,omitempty"`
	Ccy  *ActiveOrHistoricCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Ccy,omitempty"`
	Nm   *Max70Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Nm,omitempty"`
	Prxy *ProxyAccountIdentification1  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prxy,omitempty"`
}

type CashAccount41 struct {
	Id   *AccountIdentification4Choice                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id,omitempty"`
	Tp   *CashAccountType2Choice                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp,omitempty"`
	Ccy  *ActiveOrHistoricCurrencyCode                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Ccy,omitempty"`
	Nm   *Max70Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Nm,omitempty"`
	Prxy *ProxyAccountIdentification1                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prxy,omitempty"`
	Ownr *PartyIdentification135                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Ownr,omitempty"`
	Svcr *BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Svcr,omitempty"`
}

type CashAccountType2Choice struct {
	Cd    *ExternalCashAccountType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type CashAvailability1 struct {
	Dt        CashAvailabilityDate1Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Dt"`
	Amt       ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Amt"`
	CdtDbtInd CreditDebitCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdtDbtInd"`
}

type CashAvailabilityDate1Choice struct {
	NbOfDays *Max15PlusSignedNumericText `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 NbOfDays,omitempty"`
	ActlDt   *fedwire.ISODate            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ActlDt,omitempty"`
}

type CashBalance8 struct {
	Tp        BalanceType13                     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp"`
	CdtLine   []*CreditLine3                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdtLine,omitempty"`
	Amt       ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Amt"`
	CdtDbtInd CreditDebitCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdtDbtInd"`
	Dt        DateAndDateTime2Choice            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Dt"`
	Avlbty    []*CashAvailability1              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Avlbty,omitempty"`
}

type CashDeposit1 struct {
	NoteDnmtn ActiveCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 NoteDnmtn"`
	NbOfNotes Max15NumericText        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 NbOfNotes"`
	Amt       ActiveCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Amt"`
}

type ChargeType3Choice struct {
	Cd    *ExternalChargeType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *GenericIdentification3  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type Charges6 struct {
	TtlChrgsAndTaxAmt *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TtlChrgsAndTaxAmt,omitempty"`
	Rcrd              []*ChargesRecord3                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Rcrd,omitempty"`
}

type ChargesRecord3 struct {
	Amt         ActiveOrHistoricCurrencyAndAmount             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Amt"`
	CdtDbtInd   *CreditDebitCode                              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdtDbtInd,omitempty"`
	ChrgInclInd *ChargeIncludedIndicator                      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ChrgInclInd,omitempty"`
	Tp          *ChargeType3Choice                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp,omitempty"`
	Rate        *PercentageRate                               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Rate,omitempty"`
	Br          *ChargeBearerType1Code                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Br,omitempty"`
	Agt         *BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Agt,omitempty"`
	Tax         *TaxCharges2                                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tax,omitempty"`
}

type ClearingSystemIdentification2Choice struct {
	Cd    *ExternalClearingSystemIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type ClearingSystemMemberIdentification2 struct {
	ClrSysId *ClearingSystemIdentification2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ClrSysId,omitempty"`
	MmbId    Max35Text                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 MmbId"`
}

type Contact4 struct {
	NmPrfx    *NamePrefix2Code             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 NmPrfx,omitempty"`
	Nm        *Max140Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Nm,omitempty"`
	PhneNb    *PhoneNumber                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PhneNb,omitempty"`
	MobNb     *PhoneNumber                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 MobNb,omitempty"`
	FaxNb     *PhoneNumber                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FaxNb,omitempty"`
	EmailAdr  *Max2048Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 EmailAdr,omitempty"`
	EmailPurp *Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 EmailPurp,omitempty"`
	JobTitl   *Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 JobTitl,omitempty"`
	Rspnsblty *Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Rspnsblty,omitempty"`
	Dept      *Max70Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Dept,omitempty"`
	Othr      []*OtherContact1             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Othr,omitempty"`
	PrefrdMtd *PreferredContactMethod1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PrefrdMtd,omitempty"`
}

type CorporateAction9 struct {
	EvtTp Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 EvtTp"`
	EvtId Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 EvtId"`
}

type CreditLine3 struct {
	Incl TrueFalseIndicator                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Incl"`
	Tp   *CreditLineType1Choice             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp,omitempty"`
	Amt  *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Amt,omitempty"`
	Dt   *DateAndDateTime2Choice            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Dt,omitempty"`
}

type CreditLineType1Choice struct {
	Cd    *ExternalCreditLineType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type CreditorReferenceInformation2 struct {
	Tp  *CreditorReferenceType2 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp,omitempty"`
	Ref *Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Ref,omitempty"`
}

type CreditorReferenceType1Choice struct {
	Cd    *DocumentType3Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type CreditorReferenceType2 struct {
	CdOrPrtry CreditorReferenceType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdOrPrtry"`
	Issr      *Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Issr,omitempty"`
}

type CurrencyExchange5 struct {
	SrcCcy   ActiveOrHistoricCurrencyCode  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SrcCcy"`
	TrgtCcy  *ActiveOrHistoricCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TrgtCcy,omitempty"`
	UnitCcy  *ActiveOrHistoricCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 UnitCcy,omitempty"`
	XchgRate BaseOneRate                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 XchgRate"`
	CtrctId  *Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CtrctId,omitempty"`
	QtnDt    *fedwire.ISODateTime          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 QtnDt,omitempty"`
}

type DateAndDateTime2Choice struct {
	Dt   *fedwire.ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Dt,omitempty"`
	DtTm *fedwire.ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 DtTm,omitempty"`
}

type DateAndPlaceOfBirth1 struct {
	BirthDt     fedwire.ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 BirthDt"`
	PrvcOfBirth *Max35Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PrvcOfBirth,omitempty"`
	CityOfBirth Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CityOfBirth"`
	CtryOfBirth CountryCode     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CtryOfBirth"`
}

type DateOrDateTimePeriod1Choice struct {
	Dt   *DatePeriod2     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Dt,omitempty"`
	DtTm *DateTimePeriod1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 DtTm,omitempty"`
}

type DatePeriod2 struct {
	FrDt fedwire.ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FrDt"`
	ToDt fedwire.ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ToDt"`
}

type DateTimePeriod1 struct {
	FrDtTm fedwire.ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FrDtTm"`
	ToDtTm fedwire.ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ToDtTm"`
}

type DiscountAmountAndType1 struct {
	Tp  *DiscountAmountType1Choice        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp,omitempty"`
	Amt ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Amt"`
}

type DiscountAmountType1Choice struct {
	Cd    *ExternalDiscountAmountType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type DisplayCapabilities1 struct {
	DispTp    UserInterface2Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 DispTp"`
	NbOfLines Max3NumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 NbOfLines"`
	LineWidth Max3NumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 LineWidth"`
}

type DocumentAdjustment1 struct {
	Amt       ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Amt"`
	CdtDbtInd *CreditDebitCode                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdtDbtInd,omitempty"`
	Rsn       *Max4Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Rsn,omitempty"`
	AddtlInf  *Max140Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AddtlInf,omitempty"`
}

type DocumentLineIdentification1 struct {
	Tp     *DocumentLineType1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp,omitempty"`
	Nb     *Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Nb,omitempty"`
	RltdDt *fedwire.ISODate   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RltdDt,omitempty"`
}

type DocumentLineInformation1 struct {
	Id   []DocumentLineIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id"`
	Desc *Max2048Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Desc,omitempty"`
	Amt  *RemittanceAmount3            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Amt,omitempty"`
}

type DocumentLineType1 struct {
	CdOrPrtry DocumentLineType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdOrPrtry"`
	Issr      *Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Issr,omitempty"`
}

type DocumentLineType1Choice struct {
	Cd    *ExternalDocumentLineType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type EntryDetails10 struct {
	Btch   *BatchInformation2    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Btch,omitempty"`
	TxDtls []*EntryTransaction11 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TxDtls,omitempty"`
}

type EntryStatus1Choice struct {
	Cd    *ExternalEntryStatus1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type EntryTransaction11 struct {
	Refs        *TransactionReferences6            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Refs,omitempty"`
	Amt         *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Amt,omitempty"`
	CdtDbtInd   *CreditDebitCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdtDbtInd,omitempty"`
	AmtDtls     *AmountAndCurrencyExchange3        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AmtDtls,omitempty"`
	Avlbty      []*CashAvailability1               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Avlbty,omitempty"`
	BkTxCd      *BankTransactionCodeStructure4     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 BkTxCd,omitempty"`
	Chrgs       *Charges6                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Chrgs,omitempty"`
	Intrst      *TransactionInterest4              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Intrst,omitempty"`
	RltdPties   *TransactionParties9               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RltdPties,omitempty"`
	RltdAgts    *TransactionAgents5                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RltdAgts,omitempty"`
	LclInstrm   *LocalInstrument2Choice            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 LclInstrm,omitempty"`
	Purp        *Purpose2Choice                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Purp,omitempty"`
	RltdRmtInf  []*RemittanceLocation7             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RltdRmtInf,omitempty"`
	RmtInf      *RemittanceInformation21           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RmtInf,omitempty"`
	RltdDts     *TransactionDates3                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RltdDts,omitempty"`
	RltdPric    *TransactionPrice4Choice           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RltdPric,omitempty"`
	RltdQties   []*TransactionQuantities3Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RltdQties,omitempty"`
	FinInstrmId *SecurityIdentification19          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FinInstrmId,omitempty"`
	Tax         *TaxInformation10                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tax,omitempty"`
	RtrInf      *PaymentReturnReason5              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RtrInf,omitempty"`
	CorpActn    *CorporateAction9                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CorpActn,omitempty"`
	SfkpgAcct   *SecuritiesAccount19               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SfkpgAcct,omitempty"`
	CshDpst     []*CashDeposit1                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CshDpst,omitempty"`
	CardTx      *CardTransaction18                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CardTx,omitempty"`
	AddtlTxInf  *Max500Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AddtlTxInf,omitempty"`
	SplmtryData []*SupplementaryData1              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SplmtryData,omitempty"`
}

type FinancialIdentificationSchemeName1Choice struct {
	Cd    *ExternalFinancialInstitutionIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type FinancialInstitutionIdentification18 struct {
	BICFI       *BICFIDec2014Identifier              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 BICFI,omitempty"`
	ClrSysMmbId *ClearingSystemMemberIdentification2 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ClrSysMmbId,omitempty"`
	LEI         *LEIIdentifier                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 LEI,omitempty"`
	Nm          *Max140Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Nm,omitempty"`
	PstlAdr     *PostalAddress24                     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PstlAdr,omitempty"`
	Othr        *GenericFinancialIdentification1     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Othr,omitempty"`
}

type FinancialInstrumentQuantity1Choice struct {
	Unit     *DecimalNumber            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Unit,omitempty"`
	FaceAmt  *ImpliedCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FaceAmt,omitempty"`
	AmtsdVal *ImpliedCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AmtsdVal,omitempty"`
}

type FromToAmountRange1 struct {
	FrAmt AmountRangeBoundary1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FrAmt"`
	ToAmt AmountRangeBoundary1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ToAmt"`
}

type Garnishment3 struct {
	Tp                GarnishmentType1                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp"`
	Grnshee           *PartyIdentification135            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Grnshee,omitempty"`
	GrnshmtAdmstr     *PartyIdentification135            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 GrnshmtAdmstr,omitempty"`
	RefNb             *Max140Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RefNb,omitempty"`
	Dt                *fedwire.ISODate                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Dt,omitempty"`
	RmtdAmt           *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RmtdAmt,omitempty"`
	FmlyMdclInsrncInd *TrueFalseIndicator                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FmlyMdclInsrncInd,omitempty"`
	MplyeeTermntnInd  *TrueFalseIndicator                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 MplyeeTermntnInd,omitempty"`
}

type GarnishmentType1 struct {
	CdOrPrtry GarnishmentType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdOrPrtry"`
	Issr      *Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Issr,omitempty"`
}

type GarnishmentType1Choice struct {
	Cd    *ExternalGarnishmentType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type GenericAccountIdentification1 struct {
	Id      Max34Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id"`
	SchmeNm *AccountSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SchmeNm,omitempty"`
	Issr    *Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Issr,omitempty"`
}

type GenericFinancialIdentification1 struct {
	Id      Max35Text                                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id"`
	SchmeNm *FinancialIdentificationSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SchmeNm,omitempty"`
	Issr    *Max35Text                                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Issr,omitempty"`
}

type GenericIdentification1 struct {
	Id      Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id"`
	SchmeNm *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SchmeNm,omitempty"`
	Issr    *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Issr,omitempty"`
}

type GenericIdentification3 struct {
	Id   Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id"`
	Issr *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Issr,omitempty"`
}

type GenericIdentification30 struct {
	Id      Exact4AlphaNumericText `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id"`
	Issr    Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Issr"`
	SchmeNm *Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SchmeNm,omitempty"`
}

type GenericIdentification32 struct {
	Id     Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id"`
	Tp     *PartyType3Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp,omitempty"`
	Issr   *PartyType4Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Issr,omitempty"`
	ShrtNm *Max35Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ShrtNm,omitempty"`
}

type GenericOrganisationIdentification1 struct {
	Id      Max35Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id"`
	SchmeNm *OrganisationIdentificationSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SchmeNm,omitempty"`
	Issr    *Max35Text                                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Issr,omitempty"`
}

type GenericPersonIdentification1 struct {
	Id      Max35Text                              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id"`
	SchmeNm *PersonIdentificationSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SchmeNm,omitempty"`
	Issr    *Max35Text                             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Issr,omitempty"`
}

type GroupHeader81 struct {
	MsgId       Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 MsgId"`
	CreDtTm     fedwire.ISODateTime     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CreDtTm"`
	MsgRcpt     *PartyIdentification135 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 MsgRcpt,omitempty"`
	MsgPgntn    *Pagination1            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 MsgPgntn,omitempty"`
	OrgnlBizQry *OriginalBusinessQuery1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 OrgnlBizQry,omitempty"`
	AddtlInf    *Max500Text             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AddtlInf,omitempty"`
}

type IdentificationSource3Choice struct {
	Cd    *ExternalFinancialInstrumentIdentificationType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type ImpliedCurrencyAmountRange1Choice struct {
	FrAmt   *AmountRangeBoundary1     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FrAmt,omitempty"`
	ToAmt   *AmountRangeBoundary1     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ToAmt,omitempty"`
	FrToAmt *FromToAmountRange1       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FrToAmt,omitempty"`
	EQAmt   *ImpliedCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 EQAmt,omitempty"`
	NEQAmt  *ImpliedCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 NEQAmt,omitempty"`
}

type InterestRecord2 struct {
	Amt       ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Amt"`
	CdtDbtInd CreditDebitCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdtDbtInd"`
	Tp        *InterestType1Choice              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp,omitempty"`
	Rate      *Rate4                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Rate,omitempty"`
	FrToDt    *DateTimePeriod1                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FrToDt,omitempty"`
	Rsn       *Max35Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Rsn,omitempty"`
	Tax       *TaxCharges2                      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tax,omitempty"`
}

type InterestType1Choice struct {
	Cd    *InterestType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type LocalInstrument2Choice struct {
	Cd    *ExternalLocalInstrument1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type MessageIdentification2 struct {
	MsgNmId *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 MsgNmId,omitempty"`
	MsgId   *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 MsgId,omitempty"`
}

type NameAndAddress16 struct {
	Nm  Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Nm"`
	Adr PostalAddress24 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Adr"`
}

type NumberAndSumOfTransactions1 struct {
	NbOfNtries *Max15NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 NbOfNtries,omitempty"`
	Sum        *DecimalNumber    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Sum,omitempty"`
}

type NumberAndSumOfTransactions4 struct {
	NbOfNtries *Max15NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 NbOfNtries,omitempty"`
	Sum        *DecimalNumber        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Sum,omitempty"`
	TtlNetNtry *AmountAndDirection35 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TtlNetNtry,omitempty"`
}

type OrganisationIdentification29 struct {
	AnyBIC *AnyBICDec2014Identifier              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AnyBIC,omitempty"`
	LEI    *LEIIdentifier                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 LEI,omitempty"`
	Othr   []*GenericOrganisationIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Othr,omitempty"`
}

type OrganisationIdentificationSchemeName1Choice struct {
	Cd    *ExternalOrganisationIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type OriginalAndCurrentQuantities1 struct {
	FaceAmt  ImpliedCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FaceAmt"`
	AmtsdVal ImpliedCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AmtsdVal"`
}

type OriginalBusinessQuery1 struct {
	MsgId   Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 MsgId"`
	MsgNmId *Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 MsgNmId,omitempty"`
	CreDtTm *fedwire.ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CreDtTm,omitempty"`
}

type OtherContact1 struct {
	ChanlTp Max4Text    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ChanlTp"`
	Id      *Max128Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id,omitempty"`
}

type OtherIdentification1 struct {
	Id  Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id"`
	Sfx *Max16Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Sfx,omitempty"`
	Tp  IdentificationSource3Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp"`
}

type Pagination1 struct {
	PgNb      Max5NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PgNb"`
	LastPgInd YesNoIndicator  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 LastPgInd"`
}

type Party38Choice struct {
	OrgId  *OrganisationIdentification29 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 OrgId,omitempty"`
	PrvtId *PersonIdentification13       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PrvtId,omitempty"`
}

type Party40Choice struct {
	Pty *PartyIdentification135                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Pty,omitempty"`
	Agt *BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Agt,omitempty"`
}

type PartyIdentification135 struct {
	Nm        *Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Nm,omitempty"`
	PstlAdr   *PostalAddress24 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PstlAdr,omitempty"`
	Id        *Party38Choice   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id,omitempty"`
	CtryOfRes *CountryCode     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CtryOfRes,omitempty"`
	CtctDtls  *Contact4        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CtctDtls,omitempty"`
}

type PaymentCard4 struct {
	PlainCardData *PlainCardData1         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PlainCardData,omitempty"`
	CardCtryCd    *Exact3NumericText      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CardCtryCd,omitempty"`
	CardBrnd      *GenericIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CardBrnd,omitempty"`
	AddtlCardData *Max70Text              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AddtlCardData,omitempty"`
}

type PaymentContext3 struct {
	CardPres       *TrueFalseIndicator          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CardPres,omitempty"`
	CrdhldrPres    *TrueFalseIndicator          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CrdhldrPres,omitempty"`
	OnLineCntxt    *TrueFalseIndicator          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 OnLineCntxt,omitempty"`
	AttndncCntxt   *AttendanceContext1Code      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AttndncCntxt,omitempty"`
	TxEnvt         *TransactionEnvironment1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TxEnvt,omitempty"`
	TxChanl        *TransactionChannel1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TxChanl,omitempty"`
	AttndntMsgCpbl *TrueFalseIndicator          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AttndntMsgCpbl,omitempty"`
	AttndntLang    *ISO2ALanguageCode           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AttndntLang,omitempty"`
	CardDataNtryMd CardDataReading1Code         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CardDataNtryMd"`
	FllbckInd      *TrueFalseIndicator          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FllbckInd,omitempty"`
	AuthntcnMtd    *CardholderAuthentication2   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AuthntcnMtd,omitempty"`
}

type PaymentReturnReason5 struct {
	OrgnlBkTxCd *BankTransactionCodeStructure4 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 OrgnlBkTxCd,omitempty"`
	Orgtr       *PartyIdentification135        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Orgtr,omitempty"`
	Rsn         *ReturnReason5Choice           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Rsn,omitempty"`
	AddtlInf    []*Max105Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AddtlInf,omitempty"`
}

type PersonIdentification13 struct {
	DtAndPlcOfBirth *DateAndPlaceOfBirth1           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 DtAndPlcOfBirth,omitempty"`
	Othr            []*GenericPersonIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Othr,omitempty"`
}

type PersonIdentificationSchemeName1Choice struct {
	Cd    *ExternalPersonIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type PlainCardData1 struct {
	PAN        Min8Max28NumericText      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PAN"`
	CardSeqNb  *Min2Max3NumericText      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CardSeqNb,omitempty"`
	FctvDt     *ISOYearMonth             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FctvDt,omitempty"`
	XpryDt     ISOYearMonth              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 XpryDt"`
	SvcCd      *Exact3NumericText        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SvcCd,omitempty"`
	TrckData   []*TrackData1             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TrckData,omitempty"`
	CardSctyCd *CardSecurityInformation1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CardSctyCd,omitempty"`
}

type PointOfInteraction1 struct {
	Id       GenericIdentification32          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id"`
	SysNm    *Max70Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SysNm,omitempty"`
	GrpId    *Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 GrpId,omitempty"`
	Cpblties *PointOfInteractionCapabilities1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cpblties,omitempty"`
	Cmpnt    []*PointOfInteractionComponent1  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cmpnt,omitempty"`
}

type PointOfInteractionCapabilities1 struct {
	CardRdngCpblties      []*CardDataReading1Code                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CardRdngCpblties,omitempty"`
	CrdhldrVrfctnCpblties []*CardholderVerificationCapability1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CrdhldrVrfctnCpblties,omitempty"`
	OnLineCpblties        *OnLineCapability1Code                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 OnLineCpblties,omitempty"`
	DispCpblties          []*DisplayCapabilities1                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 DispCpblties,omitempty"`
	PrtLineWidth          *Max3NumericText                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PrtLineWidth,omitempty"`
}

type PointOfInteractionComponent1 struct {
	POICmpntTp POIComponentType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 POICmpntTp"`
	ManfctrId  *Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ManfctrId,omitempty"`
	Mdl        *Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Mdl,omitempty"`
	VrsnNb     *Max16Text            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 VrsnNb,omitempty"`
	SrlNb      *Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SrlNb,omitempty"`
	ApprvlNb   []*Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ApprvlNb,omitempty"`
}

type PostalAddress24 struct {
	AdrTp       *AddressType3Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AdrTp,omitempty"`
	Dept        *Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Dept,omitempty"`
	SubDept     *Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SubDept,omitempty"`
	StrtNm      *Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 StrtNm,omitempty"`
	BldgNb      *Max16Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 BldgNb,omitempty"`
	BldgNm      *Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 BldgNm,omitempty"`
	Flr         *Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Flr,omitempty"`
	PstBx       *Max16Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PstBx,omitempty"`
	Room        *Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Room,omitempty"`
	PstCd       *Max16Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PstCd,omitempty"`
	TwnNm       *Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TwnNm,omitempty"`
	TwnLctnNm   *Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TwnLctnNm,omitempty"`
	DstrctNm    *Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 DstrctNm,omitempty"`
	CtrySubDvsn *Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CtrySubDvsn,omitempty"`
	Ctry        *CountryCode        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Ctry,omitempty"`
	AdrLine     []*Max70Text        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AdrLine,omitempty"`
}

type Price7 struct {
	Tp  YieldedOrValueType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp"`
	Val PriceRateOrAmount3Choice  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Val"`
}

type PriceRateOrAmount3Choice struct {
	Rate *PercentageRate                             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Rate,omitempty"`
	Amt  *ActiveOrHistoricCurrencyAnd13DecimalAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Amt,omitempty"`
}

type Product2 struct {
	PdctCd       Max70Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PdctCd"`
	UnitOfMeasr  *UnitOfMeasure1Code       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 UnitOfMeasr,omitempty"`
	PdctQty      *DecimalNumber            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PdctQty,omitempty"`
	UnitPric     *ImpliedCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 UnitPric,omitempty"`
	PdctAmt      *ImpliedCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PdctAmt,omitempty"`
	TaxTp        *Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TaxTp,omitempty"`
	AddtlPdctInf *Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AddtlPdctInf,omitempty"`
}

type ProprietaryAgent4 struct {
	Tp  Max35Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp"`
	Agt BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Agt"`
}

type ProprietaryBankTransactionCodeStructure1 struct {
	Cd   Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd"`
	Issr *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Issr,omitempty"`
}

type ProprietaryDate3 struct {
	Tp Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp"`
	Dt DateAndDateTime2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Dt"`
}

type ProprietaryParty5 struct {
	Tp  Max35Text     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp"`
	Pty Party40Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Pty"`
}

type ProprietaryPrice2 struct {
	Tp   Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp"`
	Pric ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Pric"`
}

type ProprietaryQuantity1 struct {
	Tp  Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp"`
	Qty Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Qty"`
}

type ProprietaryReference1 struct {
	Tp  Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp"`
	Ref Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Ref"`
}

type ProxyAccountIdentification1 struct {
	Tp *ProxyAccountType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp,omitempty"`
	Id Max2048Text              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id"`
}

type ProxyAccountType1Choice struct {
	Cd    *ExternalProxyAccountType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type Purpose2Choice struct {
	Cd    *ExternalPurpose1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type Rate4 struct {
	Tp      RateType4Choice                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp"`
	VldtyRg *ActiveOrHistoricCurrencyAndAmountRange2 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 VldtyRg,omitempty"`
}

type RateType4Choice struct {
	Pctg *PercentageRate `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Pctg,omitempty"`
	Othr *Max35Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Othr,omitempty"`
}

type ReferredDocumentInformation7 struct {
	Tp       *ReferredDocumentType4      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp,omitempty"`
	Nb       *Max35Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Nb,omitempty"`
	RltdDt   *fedwire.ISODate            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RltdDt,omitempty"`
	LineDtls []*DocumentLineInformation1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 LineDtls,omitempty"`
}

type ReferredDocumentType3Choice struct {
	Cd    *DocumentType6Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type ReferredDocumentType4 struct {
	CdOrPrtry ReferredDocumentType3Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdOrPrtry"`
	Issr      *Max35Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Issr,omitempty"`
}

type RemittanceAmount2 struct {
	DuePyblAmt        *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 DuePyblAmt,omitempty"`
	DscntApldAmt      []*DiscountAmountAndType1          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 DscntApldAmt,omitempty"`
	CdtNoteAmt        *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdtNoteAmt,omitempty"`
	TaxAmt            []*TaxAmountAndType1               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TaxAmt,omitempty"`
	AdjstmntAmtAndRsn []*DocumentAdjustment1             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AdjstmntAmtAndRsn,omitempty"`
	RmtdAmt           *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RmtdAmt,omitempty"`
}

type RemittanceAmount3 struct {
	DuePyblAmt        *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 DuePyblAmt,omitempty"`
	DscntApldAmt      []*DiscountAmountAndType1          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 DscntApldAmt,omitempty"`
	CdtNoteAmt        *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdtNoteAmt,omitempty"`
	TaxAmt            []*TaxAmountAndType1               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TaxAmt,omitempty"`
	AdjstmntAmtAndRsn []*DocumentAdjustment1             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AdjstmntAmtAndRsn,omitempty"`
	RmtdAmt           *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RmtdAmt,omitempty"`
}

type RemittanceInformation21 struct {
	Ustrd []*Max140Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Ustrd,omitempty"`
	Strd  []*StructuredRemittanceInformation17 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Strd,omitempty"`
}

type RemittanceLocation7 struct {
	RmtId       *Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RmtId,omitempty"`
	RmtLctnDtls []*RemittanceLocationData1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RmtLctnDtls,omitempty"`
}

type RemittanceLocationData1 struct {
	Mtd        RemittanceLocationMethod2Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Mtd"`
	ElctrncAdr *Max2048Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ElctrncAdr,omitempty"`
	PstlAdr    *NameAndAddress16             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PstlAdr,omitempty"`
}

type ReportEntry11 struct {
	NtryRef       *Max35Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 NtryRef,omitempty"`
	Amt           ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Amt"`
	CdtDbtInd     CreditDebitCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdtDbtInd"`
	RvslInd       *TrueFalseIndicator               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RvslInd,omitempty"`
	Sts           EntryStatus1Choice                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Sts"`
	BookgDt       *DateAndDateTime2Choice           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 BookgDt,omitempty"`
	ValDt         *DateAndDateTime2Choice           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ValDt,omitempty"`
	AcctSvcrRef   *Max35Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AcctSvcrRef,omitempty"`
	Avlbty        []*CashAvailability1              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Avlbty,omitempty"`
	BkTxCd        BankTransactionCodeStructure4     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 BkTxCd"`
	ComssnWvrInd  *YesNoIndicator                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ComssnWvrInd,omitempty"`
	AddtlInfInd   *MessageIdentification2           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AddtlInfInd,omitempty"`
	AmtDtls       *AmountAndCurrencyExchange3       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AmtDtls,omitempty"`
	Chrgs         *Charges6                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Chrgs,omitempty"`
	TechInptChanl *TechnicalInputChannel1Choice     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TechInptChanl,omitempty"`
	Intrst        *TransactionInterest4             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Intrst,omitempty"`
	CardTx        *CardEntry5                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CardTx,omitempty"`
	NtryDtls      []*EntryDetails10                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 NtryDtls,omitempty"`
	AddtlNtryInf  *Max500Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AddtlNtryInf,omitempty"`
}

type ReportingSource1Choice struct {
	Cd    *ExternalReportingSource1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type ReturnReason5Choice struct {
	Cd    *ExternalReturnReason1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type SecuritiesAccount19 struct {
	Id Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id"`
	Tp *GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp,omitempty"`
	Nm *Max70Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Nm,omitempty"`
}

type SecurityIdentification19 struct {
	ISIN   *ISINOct2015Identifier  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ISIN,omitempty"`
	OthrId []*OtherIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 OthrId,omitempty"`
	Desc   *Max140Text             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Desc,omitempty"`
}

type SequenceRange1 struct {
	FrSeq Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FrSeq"`
	ToSeq Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ToSeq"`
}

type SequenceRange1Choice struct {
	FrSeq   *Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FrSeq,omitempty"`
	ToSeq   *Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ToSeq,omitempty"`
	FrToSeq []SequenceRange1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FrToSeq"`
	EQSeq   []Max35Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 EQSeq"`
	NEQSeq  []Max35Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 NEQSeq"`
}

type StructuredRemittanceInformation17 struct {
	RfrdDocInf  []*ReferredDocumentInformation7 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RfrdDocInf,omitempty"`
	RfrdDocAmt  *RemittanceAmount2              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RfrdDocAmt,omitempty"`
	CdtrRefInf  *CreditorReferenceInformation2  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdtrRefInf,omitempty"`
	Invcr       *PartyIdentification135         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Invcr,omitempty"`
	Invcee      *PartyIdentification135         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Invcee,omitempty"`
	TaxRmt      *TaxData1                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TaxRmt,omitempty"`
	GrnshmtRmt  *Garnishment3                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 GrnshmtRmt,omitempty"`
	AddtlRmtInf []*Max140Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AddtlRmtInf,omitempty"`
}

type SupplementaryData1 struct {
	PlcAndNm *Max350Text                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

type TaxAmount3 struct {
	Rate         *PercentageRate                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Rate,omitempty"`
	TaxblBaseAmt *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TaxblBaseAmt,omitempty"`
	TtlAmt       *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TtlAmt,omitempty"`
	Dtls         []*TaxRecordDetails3               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Dtls,omitempty"`
}

type TaxAmountAndType1 struct {
	Tp  *TaxAmountType1Choice             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp,omitempty"`
	Amt ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Amt"`
}

type TaxAmountType1Choice struct {
	Cd    *ExternalTaxAmountType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type TaxAuthorisation1 struct {
	Titl *Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Titl,omitempty"`
	Nm   *Max140Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Nm,omitempty"`
}

type TaxCharges2 struct {
	Id   *Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Id,omitempty"`
	Rate *PercentageRate                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Rate,omitempty"`
	Amt  *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Amt,omitempty"`
}

type TaxData1 struct {
	Cdtr            *TaxParty1                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cdtr,omitempty"`
	Dbtr            *TaxParty2                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Dbtr,omitempty"`
	UltmtDbtr       *TaxParty2                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 UltmtDbtr,omitempty"`
	AdmstnZone      *Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AdmstnZone,omitempty"`
	RefNb           *Max140Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RefNb,omitempty"`
	Mtd             *Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Mtd,omitempty"`
	TtlTaxblBaseAmt *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TtlTaxblBaseAmt,omitempty"`
	TtlTaxAmt       *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TtlTaxAmt,omitempty"`
	Dt              *fedwire.ISODate                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Dt,omitempty"`
	SeqNb           *Number                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SeqNb,omitempty"`
	Rcrd            []*TaxRecord3                      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Rcrd,omitempty"`
}

type TaxInformation10 struct {
	Cdtr            *TaxParty1                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cdtr,omitempty"`
	Dbtr            *TaxParty2                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Dbtr,omitempty"`
	AdmstnZone      *Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AdmstnZone,omitempty"`
	RefNb           *Max140Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RefNb,omitempty"`
	Mtd             *Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Mtd,omitempty"`
	TtlTaxblBaseAmt *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TtlTaxblBaseAmt,omitempty"`
	TtlTaxAmt       *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TtlTaxAmt,omitempty"`
	Dt              *fedwire.ISODate                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Dt,omitempty"`
	SeqNb           *Number                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SeqNb,omitempty"`
	Rcrd            []*TaxRecord3                      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Rcrd,omitempty"`
}

type TaxParty1 struct {
	TaxId  *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TaxId,omitempty"`
	RegnId *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RegnId,omitempty"`
	TaxTp  *Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TaxTp,omitempty"`
}

type TaxParty2 struct {
	TaxId   *Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TaxId,omitempty"`
	RegnId  *Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RegnId,omitempty"`
	TaxTp   *Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TaxTp,omitempty"`
	Authstn *TaxAuthorisation1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Authstn,omitempty"`
}

type TaxPeriod3 struct {
	Yr     *ISOYear              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Yr,omitempty"`
	Tp     *TaxRecordPeriod1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp,omitempty"`
	FrToDt *DatePeriod2          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FrToDt,omitempty"`
}

type TaxRecord3 struct {
	Tp       *Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Tp,omitempty"`
	Ctgy     *Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Ctgy,omitempty"`
	CtgyDtls *Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CtgyDtls,omitempty"`
	DbtrSts  *Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 DbtrSts,omitempty"`
	CertId   *Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CertId,omitempty"`
	FrmsCd   *Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FrmsCd,omitempty"`
	Prd      *TaxPeriod3 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prd,omitempty"`
	TaxAmt   *TaxAmount3 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TaxAmt,omitempty"`
	AddtlInf *Max140Text `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AddtlInf,omitempty"`
}

type TaxRecordDetails3 struct {
	Prd *TaxPeriod3                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prd,omitempty"`
	Amt ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Amt"`
}

type TechnicalInputChannel1Choice struct {
	Cd    *ExternalTechnicalInputChannel1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cd,omitempty"`
	Prtry *Max35Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type TotalTransactions6 struct {
	TtlNtries          *NumberAndSumOfTransactions4     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TtlNtries,omitempty"`
	TtlCdtNtries       *NumberAndSumOfTransactions1     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TtlCdtNtries,omitempty"`
	TtlDbtNtries       *NumberAndSumOfTransactions1     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TtlDbtNtries,omitempty"`
	TtlNtriesPerBkTxCd []*TotalsPerBankTransactionCode5 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TtlNtriesPerBkTxCd,omitempty"`
}

type TotalsPerBankTransactionCode5 struct {
	NbOfNtries *Max15NumericText             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 NbOfNtries,omitempty"`
	Sum        *DecimalNumber                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Sum,omitempty"`
	TtlNetNtry *AmountAndDirection35         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TtlNetNtry,omitempty"`
	CdtNtries  *NumberAndSumOfTransactions1  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdtNtries,omitempty"`
	DbtNtries  *NumberAndSumOfTransactions1  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 DbtNtries,omitempty"`
	FcstInd    *TrueFalseIndicator           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 FcstInd,omitempty"`
	BkTxCd     BankTransactionCodeStructure4 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 BkTxCd"`
	Avlbty     []*CashAvailability1          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Avlbty,omitempty"`
	Dt         *DateAndDateTime2Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Dt,omitempty"`
}

type TrackData1 struct {
	TrckNb  *Exact1NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TrckNb,omitempty"`
	TrckVal Max140Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TrckVal"`
}

type TransactionAgents5 struct {
	InstgAgt   *BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 InstgAgt,omitempty"`
	InstdAgt   *BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 InstdAgt,omitempty"`
	DbtrAgt    *BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 DbtrAgt,omitempty"`
	CdtrAgt    *BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdtrAgt,omitempty"`
	IntrmyAgt1 *BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 IntrmyAgt1,omitempty"`
	IntrmyAgt2 *BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 IntrmyAgt2,omitempty"`
	IntrmyAgt3 *BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 IntrmyAgt3,omitempty"`
	RcvgAgt    *BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 RcvgAgt,omitempty"`
	DlvrgAgt   *BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 DlvrgAgt,omitempty"`
	IssgAgt    *BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 IssgAgt,omitempty"`
	SttlmPlc   *BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 SttlmPlc,omitempty"`
	Prtry      []*ProprietaryAgent4                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type TransactionDates3 struct {
	AccptncDtTm             *fedwire.ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AccptncDtTm,omitempty"`
	TradActvtyCtrctlSttlmDt *fedwire.ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TradActvtyCtrctlSttlmDt,omitempty"`
	TradDt                  *fedwire.ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TradDt,omitempty"`
	IntrBkSttlmDt           *fedwire.ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 IntrBkSttlmDt,omitempty"`
	StartDt                 *fedwire.ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 StartDt,omitempty"`
	EndDt                   *fedwire.ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 EndDt,omitempty"`
	TxDtTm                  *fedwire.ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TxDtTm,omitempty"`
	Prtry                   []*ProprietaryDate3  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type TransactionIdentifier1 struct {
	TxDtTm fedwire.ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TxDtTm"`
	TxRef  Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TxRef"`
}

type TransactionInterest4 struct {
	TtlIntrstAndTaxAmt *ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TtlIntrstAndTaxAmt,omitempty"`
	Rcrd               []*InterestRecord2                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Rcrd,omitempty"`
}

type TransactionParties9 struct {
	InitgPty  *Party40Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 InitgPty,omitempty"`
	Dbtr      *Party40Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Dbtr,omitempty"`
	DbtrAcct  *CashAccount40       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 DbtrAcct,omitempty"`
	UltmtDbtr *Party40Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 UltmtDbtr,omitempty"`
	Cdtr      *Party40Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Cdtr,omitempty"`
	CdtrAcct  *CashAccount40       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 CdtrAcct,omitempty"`
	UltmtCdtr *Party40Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 UltmtCdtr,omitempty"`
	TradgPty  *Party40Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TradgPty,omitempty"`
	Prtry     []*ProprietaryParty5 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type TransactionPrice4Choice struct {
	DealPric *Price7             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 DealPric,omitempty"`
	Prtry    []ProprietaryPrice2 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry"`
}

type TransactionQuantities3Choice struct {
	Qty                *FinancialInstrumentQuantity1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Qty,omitempty"`
	OrgnlAndCurFaceAmt *OriginalAndCurrentQuantities1      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 OrgnlAndCurFaceAmt,omitempty"`
	Prtry              *ProprietaryQuantity1               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type TransactionReferences6 struct {
	MsgId             *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 MsgId,omitempty"`
	AcctSvcrRef       *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AcctSvcrRef,omitempty"`
	PmtInfId          *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PmtInfId,omitempty"`
	InstrId           *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 InstrId,omitempty"`
	EndToEndId        *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 EndToEndId,omitempty"`
	UETR              *UUIDv4Identifier        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 UETR,omitempty"`
	TxId              *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 TxId,omitempty"`
	MndtId            *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 MndtId,omitempty"`
	ChqNb             *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ChqNb,omitempty"`
	ClrSysRef         *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ClrSysRef,omitempty"`
	AcctOwnrTxId      *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AcctOwnrTxId,omitempty"`
	AcctSvcrTxId      *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 AcctSvcrTxId,omitempty"`
	MktInfrstrctrTxId *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 MktInfrstrctrTxId,omitempty"`
	PrcgId            *Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 PrcgId,omitempty"`
	Prtry             []*ProprietaryReference1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Prtry,omitempty"`
}

type YieldedOrValueType1Choice struct {
	Yldd  *YesNoIndicator      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 Yldd,omitempty"`
	ValTp *PriceValueType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.052.001.09 ValTp,omitempty"`
}

// XSD SimpleType declarations

type ActiveCurrencyAndAmountSimpleType fedwire.Amount

type ActiveCurrencyCode string

type ActiveOrHistoricCurrencyAnd13DecimalAmountSimpleType float64

type ActiveOrHistoricCurrencyAndAmountSimpleType fedwire.Amount

type ActiveOrHistoricCurrencyCode string

type AddressType2Code string

const AddressType2CodeAddr AddressType2Code = "ADDR"
const AddressType2CodePbox AddressType2Code = "PBOX"
const AddressType2CodeHome AddressType2Code = "HOME"
const AddressType2CodeBizz AddressType2Code = "BIZZ"
const AddressType2CodeMlto AddressType2Code = "MLTO"
const AddressType2CodeDlvy AddressType2Code = "DLVY"

type AnyBICDec2014Identifier string

type AttendanceContext1Code string

const AttendanceContext1CodeAttd AttendanceContext1Code = "ATTD"
const AttendanceContext1CodeSatt AttendanceContext1Code = "SATT"
const AttendanceContext1CodeUatt AttendanceContext1Code = "UATT"

type AuthenticationEntity1Code string

const AuthenticationEntity1CodeIccd AuthenticationEntity1Code = "ICCD"
const AuthenticationEntity1CodeAgnt AuthenticationEntity1Code = "AGNT"
const AuthenticationEntity1CodeMerc AuthenticationEntity1Code = "MERC"

type AuthenticationMethod1Code string

const AuthenticationMethod1CodeUknw AuthenticationMethod1Code = "UKNW"
const AuthenticationMethod1CodeByps AuthenticationMethod1Code = "BYPS"
const AuthenticationMethod1CodeNpin AuthenticationMethod1Code = "NPIN"
const AuthenticationMethod1CodeFpin AuthenticationMethod1Code = "FPIN"
const AuthenticationMethod1CodeCpsg AuthenticationMethod1Code = "CPSG"
const AuthenticationMethod1CodePpsg AuthenticationMethod1Code = "PPSG"
const AuthenticationMethod1CodeManu AuthenticationMethod1Code = "MANU"
const AuthenticationMethod1CodeMerc AuthenticationMethod1Code = "MERC"
const AuthenticationMethod1CodeScrt AuthenticationMethod1Code = "SCRT"
const AuthenticationMethod1CodeSnct AuthenticationMethod1Code = "SNCT"
const AuthenticationMethod1CodeScnl AuthenticationMethod1Code = "SCNL"

type BICFIDec2014Identifier string

type BaseOneRate float64

type CSCManagement1Code string

const CSCManagement1CodePrst CSCManagement1Code = "PRST"
const CSCManagement1CodeByps CSCManagement1Code = "BYPS"
const CSCManagement1CodeUnrd CSCManagement1Code = "UNRD"
const CSCManagement1CodeNcsc CSCManagement1Code = "NCSC"

type CardDataReading1Code string

const CardDataReading1CodeTagc CardDataReading1Code = "TAGC"
const CardDataReading1CodePhys CardDataReading1Code = "PHYS"
const CardDataReading1CodeBrcd CardDataReading1Code = "BRCD"
const CardDataReading1CodeMgst CardDataReading1Code = "MGST"
const CardDataReading1CodeCicc CardDataReading1Code = "CICC"
const CardDataReading1CodeDfle CardDataReading1Code = "DFLE"
const CardDataReading1CodeCtls CardDataReading1Code = "CTLS"
const CardDataReading1CodeEctl CardDataReading1Code = "ECTL"

type CardPaymentServiceType2Code string

const CardPaymentServiceType2CodeAggr CardPaymentServiceType2Code = "AGGR"
const CardPaymentServiceType2CodeDccv CardPaymentServiceType2Code = "DCCV"
const CardPaymentServiceType2CodeGrtt CardPaymentServiceType2Code = "GRTT"
const CardPaymentServiceType2CodeInsp CardPaymentServiceType2Code = "INSP"
const CardPaymentServiceType2CodeLoyt CardPaymentServiceType2Code = "LOYT"
const CardPaymentServiceType2CodeNres CardPaymentServiceType2Code = "NRES"
const CardPaymentServiceType2CodePuco CardPaymentServiceType2Code = "PUCO"
const CardPaymentServiceType2CodeRecp CardPaymentServiceType2Code = "RECP"
const CardPaymentServiceType2CodeSoaf CardPaymentServiceType2Code = "SOAF"
const CardPaymentServiceType2CodeUnaf CardPaymentServiceType2Code = "UNAF"
const CardPaymentServiceType2CodeVcau CardPaymentServiceType2Code = "VCAU"

type CardholderVerificationCapability1Code string

const CardholderVerificationCapability1CodeMnsg CardholderVerificationCapability1Code = "MNSG"
const CardholderVerificationCapability1CodeNpin CardholderVerificationCapability1Code = "NPIN"
const CardholderVerificationCapability1CodeFcpn CardholderVerificationCapability1Code = "FCPN"
const CardholderVerificationCapability1CodeFepn CardholderVerificationCapability1Code = "FEPN"
const CardholderVerificationCapability1CodeFdsg CardholderVerificationCapability1Code = "FDSG"
const CardholderVerificationCapability1CodeFbio CardholderVerificationCapability1Code = "FBIO"
const CardholderVerificationCapability1CodeMnvr CardholderVerificationCapability1Code = "MNVR"
const CardholderVerificationCapability1CodeFbig CardholderVerificationCapability1Code = "FBIG"
const CardholderVerificationCapability1CodeApki CardholderVerificationCapability1Code = "APKI"
const CardholderVerificationCapability1CodePkis CardholderVerificationCapability1Code = "PKIS"
const CardholderVerificationCapability1CodeChdt CardholderVerificationCapability1Code = "CHDT"
const CardholderVerificationCapability1CodeScec CardholderVerificationCapability1Code = "SCEC"

type ChargeBearerType1Code string

const ChargeBearerType1CodeDebt ChargeBearerType1Code = "DEBT"
const ChargeBearerType1CodeCred ChargeBearerType1Code = "CRED"
const ChargeBearerType1CodeShar ChargeBearerType1Code = "SHAR"
const ChargeBearerType1CodeSlev ChargeBearerType1Code = "SLEV"

type ChargeIncludedIndicator bool

type CopyDuplicate1Code string

const CopyDuplicate1CodeCodu CopyDuplicate1Code = "CODU"
const CopyDuplicate1CodeCopy CopyDuplicate1Code = "COPY"
const CopyDuplicate1CodeDupl CopyDuplicate1Code = "DUPL"

type CountryCode string

type CreditDebitCode string

const CreditDebitCodeCrdt CreditDebitCode = "CRDT"
const CreditDebitCodeDbit CreditDebitCode = "DBIT"

type DecimalNumber float64

type DocumentType3Code string

const DocumentType3CodeRadm DocumentType3Code = "RADM"
const DocumentType3CodeRpin DocumentType3Code = "RPIN"
const DocumentType3CodeFxdr DocumentType3Code = "FXDR"
const DocumentType3CodeDisp DocumentType3Code = "DISP"
const DocumentType3CodePuor DocumentType3Code = "PUOR"
const DocumentType3CodeScor DocumentType3Code = "SCOR"

type DocumentType6Code string

const DocumentType6CodeMsin DocumentType6Code = "MSIN"
const DocumentType6CodeCnfa DocumentType6Code = "CNFA"
const DocumentType6CodeDnfa DocumentType6Code = "DNFA"
const DocumentType6CodeCinv DocumentType6Code = "CINV"
const DocumentType6CodeCren DocumentType6Code = "CREN"
const DocumentType6CodeDebn DocumentType6Code = "DEBN"
const DocumentType6CodeHiri DocumentType6Code = "HIRI"
const DocumentType6CodeSbin DocumentType6Code = "SBIN"
const DocumentType6CodeCmcn DocumentType6Code = "CMCN"
const DocumentType6CodeSoac DocumentType6Code = "SOAC"
const DocumentType6CodeDisp DocumentType6Code = "DISP"
const DocumentType6CodeBold DocumentType6Code = "BOLD"
const DocumentType6CodeVchr DocumentType6Code = "VCHR"
const DocumentType6CodeAroi DocumentType6Code = "AROI"
const DocumentType6CodeTsut DocumentType6Code = "TSUT"
const DocumentType6CodePuor DocumentType6Code = "PUOR"

type Exact1NumericText string

type Exact3NumericText string

type Exact4AlphaNumericText string

type ExternalAccountIdentification1Code string

type ExternalBalanceSubType1Code string

type ExternalBalanceType1Code string

type ExternalBankTransactionDomain1Code string

type ExternalBankTransactionFamily1Code string

type ExternalBankTransactionSubFamily1Code string

type ExternalCardTransactionCategory1Code string

type ExternalCashAccountType1Code string

type ExternalChargeType1Code string

type ExternalClearingSystemIdentification1Code string

type ExternalCreditLineType1Code string

type ExternalDiscountAmountType1Code string

type ExternalDocumentLineType1Code string

type ExternalEntryStatus1Code string

type ExternalFinancialInstitutionIdentification1Code string

type ExternalFinancialInstrumentIdentificationType1Code string

type ExternalGarnishmentType1Code string

type ExternalLocalInstrument1Code string

type ExternalOrganisationIdentification1Code string

type ExternalPersonIdentification1Code string

type ExternalProxyAccountType1Code string

type ExternalPurpose1Code string

type ExternalRePresentmentReason1Code string

type ExternalReportingSource1Code string

type ExternalReturnReason1Code string

type ExternalTaxAmountType1Code string

type ExternalTechnicalInputChannel1Code string

type IBAN2007Identifier string

type ISINOct2015Identifier string

type ISO2ALanguageCode string

type ISOYear string

type ISOYearMonth string

type ImpliedCurrencyAndAmount float64

type InterestType1Code string

const InterestType1CodeIndy InterestType1Code = "INDY"
const InterestType1CodeOvrn InterestType1Code = "OVRN"

type LEIIdentifier string

type Max1025Text string

type Max105Text string

type Max128Text string

type Max140Text string

type Max15NumericText string

type Max15PlusSignedNumericText string

type Max16Text string

type Max2048Text string

type Max34Text string

type Max350Text string

type Max35Text string

type Max3NumericText string

type Max4Text string

type Max500Text string

type Max5NumericText string

type Max70Text string

type Min2Max3NumericText string

type Min3Max4NumericText string

type Min8Max28NumericText string

type NamePrefix2Code string

const NamePrefix2CodeDoct NamePrefix2Code = "DOCT"
const NamePrefix2CodeMadm NamePrefix2Code = "MADM"
const NamePrefix2CodeMiss NamePrefix2Code = "MISS"
const NamePrefix2CodeMist NamePrefix2Code = "MIST"
const NamePrefix2CodeMiks NamePrefix2Code = "MIKS"

type NonNegativeDecimalNumber float64

type Number float64

type OnLineCapability1Code string

const OnLineCapability1CodeOfln OnLineCapability1Code = "OFLN"
const OnLineCapability1CodeOnln OnLineCapability1Code = "ONLN"
const OnLineCapability1CodeSmon OnLineCapability1Code = "SMON"

type POIComponentType1Code string

const POIComponentType1CodeSoft POIComponentType1Code = "SOFT"
const POIComponentType1CodeEmvk POIComponentType1Code = "EMVK"
const POIComponentType1CodeEmvo POIComponentType1Code = "EMVO"
const POIComponentType1CodeMrit POIComponentType1Code = "MRIT"
const POIComponentType1CodeChit POIComponentType1Code = "CHIT"
const POIComponentType1CodeSecm POIComponentType1Code = "SECM"
const POIComponentType1CodePedv POIComponentType1Code = "PEDV"

type PartyType3Code string

const PartyType3CodeOpoi PartyType3Code = "OPOI"
const PartyType3CodeMerc PartyType3Code = "MERC"
const PartyType3CodeAccp PartyType3Code = "ACCP"
const PartyType3CodeItag PartyType3Code = "ITAG"
const PartyType3CodeAcqr PartyType3Code = "ACQR"
const PartyType3CodeCiss PartyType3Code = "CISS"
const PartyType3CodeDlis PartyType3Code = "DLIS"

type PartyType4Code string

const PartyType4CodeMerc PartyType4Code = "MERC"
const PartyType4CodeAccp PartyType4Code = "ACCP"
const PartyType4CodeItag PartyType4Code = "ITAG"
const PartyType4CodeAcqr PartyType4Code = "ACQR"
const PartyType4CodeCiss PartyType4Code = "CISS"
const PartyType4CodeTaxh PartyType4Code = "TAXH"

type PercentageRate float64

type PhoneNumber string

type PreferredContactMethod1Code string

const PreferredContactMethod1CodeLett PreferredContactMethod1Code = "LETT"
const PreferredContactMethod1CodeMail PreferredContactMethod1Code = "MAIL"
const PreferredContactMethod1CodePhon PreferredContactMethod1Code = "PHON"
const PreferredContactMethod1CodeFaxx PreferredContactMethod1Code = "FAXX"
const PreferredContactMethod1CodeCell PreferredContactMethod1Code = "CELL"

type PriceValueType1Code string

const PriceValueType1CodeDisc PriceValueType1Code = "DISC"
const PriceValueType1CodePrem PriceValueType1Code = "PREM"
const PriceValueType1CodeParv PriceValueType1Code = "PARV"

type RemittanceLocationMethod2Code string

const RemittanceLocationMethod2CodeFaxi RemittanceLocationMethod2Code = "FAXI"
const RemittanceLocationMethod2CodeEdic RemittanceLocationMethod2Code = "EDIC"
const RemittanceLocationMethod2CodeUrid RemittanceLocationMethod2Code = "URID"
const RemittanceLocationMethod2CodeEmal RemittanceLocationMethod2Code = "EMAL"
const RemittanceLocationMethod2CodePost RemittanceLocationMethod2Code = "POST"
const RemittanceLocationMethod2CodeSmsm RemittanceLocationMethod2Code = "SMSM"

type TaxRecordPeriod1Code string

const TaxRecordPeriod1CodeMm01 TaxRecordPeriod1Code = "MM01"
const TaxRecordPeriod1CodeMm02 TaxRecordPeriod1Code = "MM02"
const TaxRecordPeriod1CodeMm03 TaxRecordPeriod1Code = "MM03"
const TaxRecordPeriod1CodeMm04 TaxRecordPeriod1Code = "MM04"
const TaxRecordPeriod1CodeMm05 TaxRecordPeriod1Code = "MM05"
const TaxRecordPeriod1CodeMm06 TaxRecordPeriod1Code = "MM06"
const TaxRecordPeriod1CodeMm07 TaxRecordPeriod1Code = "MM07"
const TaxRecordPeriod1CodeMm08 TaxRecordPeriod1Code = "MM08"
const TaxRecordPeriod1CodeMm09 TaxRecordPeriod1Code = "MM09"
const TaxRecordPeriod1CodeMm10 TaxRecordPeriod1Code = "MM10"
const TaxRecordPeriod1CodeMm11 TaxRecordPeriod1Code = "MM11"
const TaxRecordPeriod1CodeMm12 TaxRecordPeriod1Code = "MM12"
const TaxRecordPeriod1CodeQtr1 TaxRecordPeriod1Code = "QTR1"
const TaxRecordPeriod1CodeQtr2 TaxRecordPeriod1Code = "QTR2"
const TaxRecordPeriod1CodeQtr3 TaxRecordPeriod1Code = "QTR3"
const TaxRecordPeriod1CodeQtr4 TaxRecordPeriod1Code = "QTR4"
const TaxRecordPeriod1CodeHlf1 TaxRecordPeriod1Code = "HLF1"
const TaxRecordPeriod1CodeHlf2 TaxRecordPeriod1Code = "HLF2"

type TransactionChannel1Code string

const TransactionChannel1CodeMail TransactionChannel1Code = "MAIL"
const TransactionChannel1CodeTlph TransactionChannel1Code = "TLPH"
const TransactionChannel1CodeEcom TransactionChannel1Code = "ECOM"
const TransactionChannel1CodeTvpy TransactionChannel1Code = "TVPY"

type TransactionEnvironment1Code string

const TransactionEnvironment1CodeMerc TransactionEnvironment1Code = "MERC"
const TransactionEnvironment1CodePriv TransactionEnvironment1Code = "PRIV"
const TransactionEnvironment1CodePubl TransactionEnvironment1Code = "PUBL"

type TrueFalseIndicator bool

type UUIDv4Identifier string

type UnitOfMeasure1Code string

const UnitOfMeasure1CodePiec UnitOfMeasure1Code = "PIEC"
const UnitOfMeasure1CodeTons UnitOfMeasure1Code = "TONS"
const UnitOfMeasure1CodeFoot UnitOfMeasure1Code = "FOOT"
const UnitOfMeasure1CodeGbga UnitOfMeasure1Code = "GBGA"
const UnitOfMeasure1CodeUsga UnitOfMeasure1Code = "USGA"
const UnitOfMeasure1CodeGram UnitOfMeasure1Code = "GRAM"
const UnitOfMeasure1CodeInch UnitOfMeasure1Code = "INCH"
const UnitOfMeasure1CodeKilo UnitOfMeasure1Code = "KILO"
const UnitOfMeasure1CodePund UnitOfMeasure1Code = "PUND"
const UnitOfMeasure1CodeMetr UnitOfMeasure1Code = "METR"
const UnitOfMeasure1CodeCmet UnitOfMeasure1Code = "CMET"
const UnitOfMeasure1CodeMmet UnitOfMeasure1Code = "MMET"
const UnitOfMeasure1CodeLitr UnitOfMeasure1Code = "LITR"
const UnitOfMeasure1CodeCeli UnitOfMeasure1Code = "CELI"
const UnitOfMeasure1CodeMili UnitOfMeasure1Code = "MILI"
const UnitOfMeasure1CodeGbou UnitOfMeasure1Code = "GBOU"
const UnitOfMeasure1CodeUsou UnitOfMeasure1Code = "USOU"
const UnitOfMeasure1CodeGbqa UnitOfMeasure1Code = "GBQA"
const UnitOfMeasure1CodeUsqa UnitOfMeasure1Code = "USQA"
const UnitOfMeasure1CodeGbpi UnitOfMeasure1Code = "GBPI"
const UnitOfMeasure1CodeUspi UnitOfMeasure1Code = "USPI"
const UnitOfMeasure1CodeMile UnitOfMeasure1Code = "MILE"
const UnitOfMeasure1CodeKmet UnitOfMeasure1Code = "KMET"
const UnitOfMeasure1CodeYard UnitOfMeasure1Code = "YARD"
const UnitOfMeasure1CodeSqki UnitOfMeasure1Code = "SQKI"
const UnitOfMeasure1CodeHect UnitOfMeasure1Code = "HECT"
const UnitOfMeasure1CodeAres UnitOfMeasure1Code = "ARES"
const UnitOfMeasure1CodeSmet UnitOfMeasure1Code = "SMET"
const UnitOfMeasure1CodeScmt UnitOfMeasure1Code = "SCMT"
const UnitOfMeasure1CodeSmil UnitOfMeasure1Code = "SMIL"
const UnitOfMeasure1CodeSqmi UnitOfMeasure1Code = "SQMI"
const UnitOfMeasure1CodeSqya UnitOfMeasure1Code = "SQYA"
const UnitOfMeasure1CodeSqfo UnitOfMeasure1Code = "SQFO"
const UnitOfMeasure1CodeSqin UnitOfMeasure1Code = "SQIN"
const UnitOfMeasure1CodeAcre UnitOfMeasure1Code = "ACRE"

type UserInterface2Code string

const UserInterface2CodeMdsp UserInterface2Code = "MDSP"
const UserInterface2CodeCdsp UserInterface2Code = "CDSP"

type YesNoIndicator bool
