// Code generated by GoComply XSD2Go for Moov; DO NOT EDIT.
// Models for urn:iso:std:iso:20022:tech:xsd:camt.060.001.02
package camt_060_001_02

import (
	"encoding/xml"
	"time"

	"github.com/moov-io/fedwire20022/pkg/fedwire"
)

// XSD Elements

type Document struct {
	XMLName xml.Name

	AcctRptgReq AccountReportingRequestV02 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 AcctRptgReq"`
}

// XSD ComplexType declarations

type AccountIdentification4Choice struct {
	IBAN *IBAN2007Identifier            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 IBAN,omitempty"`
	Othr *GenericAccountIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Othr,omitempty"`
}

type AccountReportingRequestV02 struct {
	GrpHdr  GroupHeader43       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 GrpHdr"`
	RptgReq []ReportingRequest2 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 RptgReq"`
}

type AccountSchemeName1Choice struct {
	Cd    *ExternalAccountIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Cd,omitempty"`
	Prtry *Max35Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Prtry,omitempty"`
}

type ActiveOrHistoricCurrencyAndAmount struct {
	Value ActiveOrHistoricCurrencyAndAmountSimpleType `xml:",chardata"`
	Ccy   ActiveOrHistoricCurrencyCode                `xml:"Ccy,attr"`
}

type BalanceSubType1Choice struct {
	Cd    *ExternalBalanceSubType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Cd,omitempty"`
	Prtry *Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Prtry,omitempty"`
}

type BalanceType12 struct {
	CdOrPrtry BalanceType5Choice     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 CdOrPrtry"`
	SubTp     *BalanceSubType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 SubTp,omitempty"`
}

type BalanceType5Choice struct {
	Cd    *BalanceType12Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Cd,omitempty"`
	Prtry *Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Prtry,omitempty"`
}

type BranchAndFinancialInstitutionIdentification4 struct {
	FinInstnId FinancialInstitutionIdentification7 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 FinInstnId"`
	BrnchId    *BranchData2                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 BrnchId,omitempty"`
}

type BranchAndFinancialInstitutionIdentification5 struct {
	FinInstnId FinancialInstitutionIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 FinInstnId"`
	BrnchId    *BranchData2                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 BrnchId,omitempty"`
}

type BranchData2 struct {
	Id      *Max35Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Id,omitempty"`
	Nm      *Max140Text     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Nm,omitempty"`
	PstlAdr *PostalAddress6 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 PstlAdr,omitempty"`
}

type CashAccount16 struct {
	Id  AccountIdentification4Choice  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Id"`
	Tp  *CashAccountType2             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Tp,omitempty"`
	Ccy *ActiveOrHistoricCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Ccy,omitempty"`
	Nm  *Max70Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Nm,omitempty"`
}

type CashAccountType2 struct {
	Cd    *CashAccountType4Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Cd,omitempty"`
	Prtry *Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Prtry,omitempty"`
}

type ClearingSystemIdentification2Choice struct {
	Cd    *ExternalClearingSystemIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Cd,omitempty"`
	Prtry *Max35Text                                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Prtry,omitempty"`
}

type ClearingSystemMemberIdentification2 struct {
	ClrSysId *ClearingSystemIdentification2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 ClrSysId,omitempty"`
	MmbId    Max35Text                            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 MmbId"`
}

type ContactDetails2 struct {
	NmPrfx   *NamePrefix1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 NmPrfx,omitempty"`
	Nm       *Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Nm,omitempty"`
	PhneNb   *PhoneNumber     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 PhneNb,omitempty"`
	MobNb    *PhoneNumber     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 MobNb,omitempty"`
	FaxNb    *PhoneNumber     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 FaxNb,omitempty"`
	EmailAdr *Max2048Text     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 EmailAdr,omitempty"`
	Othr     *Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Othr,omitempty"`
}

type DateAndPlaceOfBirth struct {
	BirthDt     fedwire.ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 BirthDt"`
	PrvcOfBirth *Max35Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 PrvcOfBirth,omitempty"`
	CityOfBirth Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 CityOfBirth"`
	CtryOfBirth CountryCode     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 CtryOfBirth"`
}

type DatePeriodDetails1 struct {
	FrDt fedwire.ISODate  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 FrDt"`
	ToDt *fedwire.ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 ToDt,omitempty"`
}

type FinancialIdentificationSchemeName1Choice struct {
	Cd    *ExternalFinancialInstitutionIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Cd,omitempty"`
	Prtry *Max35Text                                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Prtry,omitempty"`
}

type FinancialInstitutionIdentification7 struct {
	BIC         *BICIdentifier                       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 BIC,omitempty"`
	ClrSysMmbId *ClearingSystemMemberIdentification2 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 ClrSysMmbId,omitempty"`
	Nm          *Max140Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Nm,omitempty"`
	PstlAdr     *PostalAddress6                      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 PstlAdr,omitempty"`
	Othr        *GenericFinancialIdentification1     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Othr,omitempty"`
}

type FinancialInstitutionIdentification8 struct {
	BICFI       *BICFIIdentifier                     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 BICFI,omitempty"`
	ClrSysMmbId *ClearingSystemMemberIdentification2 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 ClrSysMmbId,omitempty"`
	Nm          *Max140Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Nm,omitempty"`
	PstlAdr     *PostalAddress6                      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 PstlAdr,omitempty"`
	Othr        *GenericFinancialIdentification1     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Othr,omitempty"`
}

type GenericAccountIdentification1 struct {
	Id      Max34Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Id"`
	SchmeNm *AccountSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 SchmeNm,omitempty"`
	Issr    *Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Issr,omitempty"`
}

type GenericFinancialIdentification1 struct {
	Id      Max35Text                                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Id"`
	SchmeNm *FinancialIdentificationSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 SchmeNm,omitempty"`
	Issr    *Max35Text                                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Issr,omitempty"`
}

type GenericOrganisationIdentification1 struct {
	Id      Max35Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Id"`
	SchmeNm *OrganisationIdentificationSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 SchmeNm,omitempty"`
	Issr    *Max35Text                                   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Issr,omitempty"`
}

type GenericPersonIdentification1 struct {
	Id      Max35Text                              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Id"`
	SchmeNm *PersonIdentificationSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 SchmeNm,omitempty"`
	Issr    *Max35Text                             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Issr,omitempty"`
}

type GroupHeader43 struct {
	MsgId   Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 MsgId"`
	CreDtTm fedwire.ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 CreDtTm"`
	MsgSndr *Party7Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 MsgSndr,omitempty"`
}

type Limit2 struct {
	Amt       ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Amt"`
	CdtDbtInd FloorLimitType1Code               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 CdtDbtInd"`
}

type OrganisationIdentification4 struct {
	BICOrBEI *AnyBICIdentifier                     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 BICOrBEI,omitempty"`
	Othr     []*GenericOrganisationIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Othr,omitempty"`
}

type OrganisationIdentification8 struct {
	AnyBIC *AnyBICIdentifier                     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 AnyBIC,omitempty"`
	Othr   []*GenericOrganisationIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Othr,omitempty"`
}

type OrganisationIdentificationSchemeName1Choice struct {
	Cd    *ExternalOrganisationIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Cd,omitempty"`
	Prtry *Max35Text                               `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Prtry,omitempty"`
}

type Party11Choice struct {
	OrgId  *OrganisationIdentification8 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 OrgId,omitempty"`
	PrvtId *PersonIdentification5       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 PrvtId,omitempty"`
}

type Party12Choice struct {
	Pty *PartyIdentification43                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Pty,omitempty"`
	Agt *BranchAndFinancialInstitutionIdentification5 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Agt,omitempty"`
}

type Party6Choice struct {
	OrgId  *OrganisationIdentification4 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 OrgId,omitempty"`
	PrvtId *PersonIdentification5       `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 PrvtId,omitempty"`
}

type Party7Choice struct {
	Pty *PartyIdentification32                        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Pty,omitempty"`
	Agt *BranchAndFinancialInstitutionIdentification4 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Agt,omitempty"`
}

type PartyIdentification32 struct {
	Nm        *Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Nm,omitempty"`
	PstlAdr   *PostalAddress6  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 PstlAdr,omitempty"`
	Id        *Party6Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Id,omitempty"`
	CtryOfRes *CountryCode     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 CtryOfRes,omitempty"`
	CtctDtls  *ContactDetails2 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 CtctDtls,omitempty"`
}

type PartyIdentification43 struct {
	Nm        *Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Nm,omitempty"`
	PstlAdr   *PostalAddress6  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 PstlAdr,omitempty"`
	Id        *Party11Choice   `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Id,omitempty"`
	CtryOfRes *CountryCode     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 CtryOfRes,omitempty"`
	CtctDtls  *ContactDetails2 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 CtctDtls,omitempty"`
}

type PersonIdentification5 struct {
	DtAndPlcOfBirth *DateAndPlaceOfBirth            `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 DtAndPlcOfBirth,omitempty"`
	Othr            []*GenericPersonIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Othr,omitempty"`
}

type PersonIdentificationSchemeName1Choice struct {
	Cd    *ExternalPersonIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Cd,omitempty"`
	Prtry *Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Prtry,omitempty"`
}

type PostalAddress6 struct {
	AdrTp       *AddressType2Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 AdrTp,omitempty"`
	Dept        *Max70Text        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Dept,omitempty"`
	SubDept     *Max70Text        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 SubDept,omitempty"`
	StrtNm      *Max70Text        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 StrtNm,omitempty"`
	BldgNb      *Max16Text        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 BldgNb,omitempty"`
	PstCd       *Max16Text        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 PstCd,omitempty"`
	TwnNm       *Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 TwnNm,omitempty"`
	CtrySubDvsn *Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 CtrySubDvsn,omitempty"`
	Ctry        *CountryCode      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Ctry,omitempty"`
	AdrLine     []*Max70Text      `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 AdrLine,omitempty"`
}

type ReportingPeriod1 struct {
	FrToDt DatePeriodDetails1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 FrToDt"`
	FrToTm TimePeriodDetails1 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 FrToTm"`
	Tp     QueryType3Code     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Tp"`
}

type ReportingRequest2 struct {
	Id          *Max35Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Id,omitempty"`
	ReqdMsgNmId Max35Text                                     `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 ReqdMsgNmId"`
	Acct        *CashAccount16                                `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Acct,omitempty"`
	AcctOwnr    Party12Choice                                 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 AcctOwnr"`
	AcctSvcr    *BranchAndFinancialInstitutionIdentification5 `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 AcctSvcr,omitempty"`
	RptgPrd     *ReportingPeriod1                             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 RptgPrd,omitempty"`
	ReqdTxTp    *TransactionType1                             `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 ReqdTxTp,omitempty"`
	ReqdBalTp   []*BalanceType12                              `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 ReqdBalTp,omitempty"`
}

type TimePeriodDetails1 struct {
	FrTm ISOTime  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 FrTm"`
	ToTm *ISOTime `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 ToTm,omitempty"`
}

type TransactionType1 struct {
	Sts       EntryStatus2Code `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 Sts"`
	CdtDbtInd CreditDebitCode  `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 CdtDbtInd"`
	FlrLmt    []*Limit2        `xml:"urn:iso:std:iso:20022:tech:xsd:camt.060.001.02 FlrLmt,omitempty"`
}

// XSD SimpleType declarations

type ActiveOrHistoricCurrencyAndAmountSimpleType fedwire.Amount

type ActiveOrHistoricCurrencyCode string

type AddressType2Code string

const AddressType2CodeAddr AddressType2Code = "ADDR"
const AddressType2CodePbox AddressType2Code = "PBOX"
const AddressType2CodeHome AddressType2Code = "HOME"
const AddressType2CodeBizz AddressType2Code = "BIZZ"
const AddressType2CodeMlto AddressType2Code = "MLTO"
const AddressType2CodeDlvy AddressType2Code = "DLVY"

type AnyBICIdentifier string

type BICFIIdentifier string

type BICIdentifier string

type BalanceType12Code string

const BalanceType12CodeXpcd BalanceType12Code = "XPCD"
const BalanceType12CodeOpav BalanceType12Code = "OPAV"
const BalanceType12CodeItav BalanceType12Code = "ITAV"
const BalanceType12CodeClav BalanceType12Code = "CLAV"
const BalanceType12CodeFwav BalanceType12Code = "FWAV"
const BalanceType12CodeClbd BalanceType12Code = "CLBD"
const BalanceType12CodeItbd BalanceType12Code = "ITBD"
const BalanceType12CodeOpbd BalanceType12Code = "OPBD"
const BalanceType12CodePrcd BalanceType12Code = "PRCD"
const BalanceType12CodeInfo BalanceType12Code = "INFO"

type CashAccountType4Code string

const CashAccountType4CodeCash CashAccountType4Code = "CASH"
const CashAccountType4CodeChar CashAccountType4Code = "CHAR"
const CashAccountType4CodeComm CashAccountType4Code = "COMM"
const CashAccountType4CodeTaxe CashAccountType4Code = "TAXE"
const CashAccountType4CodeCish CashAccountType4Code = "CISH"
const CashAccountType4CodeTras CashAccountType4Code = "TRAS"
const CashAccountType4CodeSacc CashAccountType4Code = "SACC"
const CashAccountType4CodeCacc CashAccountType4Code = "CACC"
const CashAccountType4CodeSvgs CashAccountType4Code = "SVGS"
const CashAccountType4CodeOndp CashAccountType4Code = "ONDP"
const CashAccountType4CodeMgld CashAccountType4Code = "MGLD"
const CashAccountType4CodeNrex CashAccountType4Code = "NREX"
const CashAccountType4CodeMoma CashAccountType4Code = "MOMA"
const CashAccountType4CodeLoan CashAccountType4Code = "LOAN"
const CashAccountType4CodeSlry CashAccountType4Code = "SLRY"
const CashAccountType4CodeOdft CashAccountType4Code = "ODFT"

type CountryCode string

type CreditDebitCode string

const CreditDebitCodeCrdt CreditDebitCode = "CRDT"
const CreditDebitCodeDbit CreditDebitCode = "DBIT"

type EntryStatus2Code string

const EntryStatus2CodeBook EntryStatus2Code = "BOOK"
const EntryStatus2CodePdng EntryStatus2Code = "PDNG"
const EntryStatus2CodeInfo EntryStatus2Code = "INFO"

type ExternalAccountIdentification1Code string

type ExternalBalanceSubType1Code string

type ExternalClearingSystemIdentification1Code string

type ExternalFinancialInstitutionIdentification1Code string

type ExternalOrganisationIdentification1Code string

type ExternalPersonIdentification1Code string

type FloorLimitType1Code string

const FloorLimitType1CodeCred FloorLimitType1Code = "CRED"
const FloorLimitType1CodeDebt FloorLimitType1Code = "DEBT"
const FloorLimitType1CodeBoth FloorLimitType1Code = "BOTH"

type IBAN2007Identifier string

type ISOTime time.Time

type Max140Text string

type Max16Text string

type Max2048Text string

type Max34Text string

type Max35Text string

type Max70Text string

type NamePrefix1Code string

const NamePrefix1CodeDoct NamePrefix1Code = "DOCT"
const NamePrefix1CodeMist NamePrefix1Code = "MIST"
const NamePrefix1CodeMiss NamePrefix1Code = "MISS"
const NamePrefix1CodeMadm NamePrefix1Code = "MADM"

type PhoneNumber string

type QueryType3Code string

const QueryType3CodeAlll QueryType3Code = "ALLL"
const QueryType3CodeChng QueryType3Code = "CHNG"
const QueryType3CodeModf QueryType3Code = "MODF"
