// Code generated by GoComply XSD2Go for Moov; DO NOT EDIT.
// Models for urn:iso:std:iso:20022:tech:xsd:camt.060.001.02
package camt_060_001_02

import (
	"github.com/moov-io/fedwire20022/pkg/fedwire"
)

func (a ActiveOrHistoricCurrencyAndAmountSimpleType) MarshalText() ([]byte, error) {
	return fedwire.Amount(a).MarshalText()
}
