// Code generated by GoComply XSD2Go for Moov; DO NOT EDIT.
// Models for urn:iso:std:iso:20022:tech:xsd:camt.052.001.08
package ActivityReport_camt_052_001_08

import (
	"github.com/moov-io/wire20022/pkg/internal"
)

func (a ActiveOrHistoricCurrencyAndAmountSimpleType) MarshalText() ([]byte, error) {
	return fedwire.Amount(a).MarshalText()
}
