// Code generated by GoComply XSD2Go for Moov; DO NOT EDIT.
// Models for urn:iso:std:iso:20022:tech:xsd:admi.007.001.01
package FedwireFundsAcknowledgement_admi_007_001_01

import (
	"encoding/xml"

	"github.com/moov-io/fedwire20022/pkg/fedwire"
)

// XSD Elements

type Document struct {
	XMLName xml.Name

	RctAck ReceiptAcknowledgementV01 `xml:"urn:iso:std:iso:20022:tech:xsd:admi.007.001.01 RctAck"`
}

// XSD ComplexType declarations

type MessageHeader101 struct {
	MsgId   OMADFedwireFunds1   `xml:"urn:iso:std:iso:20022:tech:xsd:admi.007.001.01 MsgId"`
	CreDtTm fedwire.ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:admi.007.001.01 CreDtTm"`
}

type MessageReference11 struct {
	Ref   Max35Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:admi.007.001.01 Ref"`
	MsgNm MessageNameIdentificationFRS1 `xml:"urn:iso:std:iso:20022:tech:xsd:admi.007.001.01 MsgNm"`
}

type ReceiptAcknowledgementReport21 struct {
	RltdRef MessageReference11 `xml:"urn:iso:std:iso:20022:tech:xsd:admi.007.001.01 RltdRef"`
	ReqHdlg RequestHandling21  `xml:"urn:iso:std:iso:20022:tech:xsd:admi.007.001.01 ReqHdlg"`
}

type ReceiptAcknowledgementV01 struct {
	MsgId MessageHeader101               `xml:"urn:iso:std:iso:20022:tech:xsd:admi.007.001.01 MsgId"`
	Rpt   ReceiptAcknowledgementReport21 `xml:"urn:iso:std:iso:20022:tech:xsd:admi.007.001.01 Rpt"`
}

type RequestHandling21 struct {
	StsCd Max4AlphaNumericTextFixed `xml:"urn:iso:std:iso:20022:tech:xsd:admi.007.001.01 StsCd"`
}

// XSD SimpleType declarations

type Max35Text string

type Max4AlphaNumericTextFixed string

const Max4AlphaNumericTextFixedTs01 Max4AlphaNumericTextFixed = "TS01"

type MessageNameIdentificationFRS1 string

type OMADFedwireFunds1 string
