// Code generated by GoComply XSD2Go for Moov; DO NOT EDIT.
// Models for urn:iso:std:iso:20022:tech:xsd:camt.052.001.06
package camt_052_001_06

import (
	"github.com/moov-io/fedwire20022/pkg/fedwire"
)

func (a ActiveCurrencyAndAmountSimpleType) MarshalText() ([]byte, error) {
	return fedwire.Amount(a).MarshalText()
}

func (a ActiveOrHistoricCurrencyAndAmountSimpleType) MarshalText() ([]byte, error) {
	return fedwire.Amount(a).MarshalText()
}
