package PaymentReturn

func PathMapV2() map[string]any {
	return PathMapV7()
}
func PathMapV3() map[string]any {
	return PathMapV7()
}
func PathMapV4() map[string]any {
	return PathMapV7()
}
func PathMapV5() map[string]any {
	return PathMapV7()
}
func PathMapV6() map[string]any {
	return PathMapV7()
}
func PathMapV7() map[string]any {
	return map[string]any{
		"PmtRtr.GrpHdr.MsgId":                                         "MessageId",
		"PmtRtr.GrpHdr.CreDtTm":                                       "CreatedDateTime",
		"PmtRtr.GrpHdr.NbOfTxs":                                       "NumberOfTransactions",
		"PmtRtr.GrpHdr.SttlmInf.SttlmMtd":                             "SettlementMethod",
		"PmtRtr.GrpHdr.SttlmInf.ClrSys.Cd":                            "CommonClearingSysCode",
		"PmtRtr.TxInf[0].OrgnlGrpInf.OrgnlMsgId":                      "OriginalMessageId",
		"PmtRtr.TxInf[0].OrgnlGrpInf.OrgnlMsgNmId":                    "OriginalMessageNameId",
		"PmtRtr.TxInf[0].OrgnlGrpInf.OrgnlCreDtTm":                    "OriginalCreationDateTime",
		"PmtRtr.TxInf[0].OrgnlInstrId":                                "OriginalInstructionId",
		"PmtRtr.TxInf[0].OrgnlEndToEndId":                             "OriginalEndToEndId",
		"PmtRtr.TxInf[0].RtrdIntrBkSttlmAmt.Value":                    "ReturnedInterbankSettlementAmount.Amount",
		"PmtRtr.TxInf[0].RtrdIntrBkSttlmAmt.Ccy":                      "ReturnedInterbankSettlementAmount.Currency",
		"PmtRtr.TxInf[0].IntrBkSttlmDt":                               "InterbankSettlementDate",
		"PmtRtr.TxInf[0].RtrdInstdAmt.Value":                          "ReturnedInstructedAmount.Amount",
		"PmtRtr.TxInf[0].RtrdInstdAmt.Ccy":                            "ReturnedInstructedAmount.Currency",
		"PmtRtr.TxInf[0].ChrgBr":                                      "ChargeBearer",
		"PmtRtr.TxInf[0].InstgAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd": "InstructingAgent.PaymentSysCode",
		"PmtRtr.TxInf[0].InstgAgt.FinInstnId.ClrSysMmbId.MmbId":       "InstructingAgent.PaymentSysMemberId",
		"PmtRtr.TxInf[0].InstdAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd": "InstructedAgent.PaymentSysCode",
		"PmtRtr.TxInf[0].InstdAgt.FinInstnId.ClrSysMmbId.MmbId":       "InstructedAgent.PaymentSysMemberId",
		"PmtRtr.TxInf[0].RtrRsnInf[0].Rsn.Cd":                         "ReturnReasonInformation.Reason",
		"PmtRtr.TxInf[0].RtrRsnInf[0].AddtlInf[0]":                    "ReturnReasonInformation.AdditionalInfo",
		"PmtRtr.TxInf[0].OrgnlTxRef.PmtTpInf.LclInstrm.Prtry":         "OriginalTransactionRef",
	}
}
func PathMapV8() map[string]any {
	return map[string]any{
		"PmtRtr.GrpHdr.MsgId":                                                 "MessageId",
		"PmtRtr.GrpHdr.CreDtTm":                                               "CreatedDateTime",
		"PmtRtr.GrpHdr.NbOfTxs":                                               "NumberOfTransactions",
		"PmtRtr.GrpHdr.SttlmInf.SttlmMtd":                                     "SettlementMethod",
		"PmtRtr.GrpHdr.SttlmInf.ClrSys.Cd":                                    "CommonClearingSysCode",
		"PmtRtr.TxInf[0].OrgnlGrpInf.OrgnlMsgId":                              "OriginalMessageId",
		"PmtRtr.TxInf[0].OrgnlGrpInf.OrgnlMsgNmId":                            "OriginalMessageNameId",
		"PmtRtr.TxInf[0].OrgnlGrpInf.OrgnlCreDtTm":                            "OriginalCreationDateTime",
		"PmtRtr.TxInf[0].OrgnlInstrId":                                        "OriginalInstructionId",
		"PmtRtr.TxInf[0].OrgnlEndToEndId":                                     "OriginalEndToEndId",
		"PmtRtr.TxInf[0].RtrdIntrBkSttlmAmt.Value":                            "ReturnedInterbankSettlementAmount.Amount",
		"PmtRtr.TxInf[0].RtrdIntrBkSttlmAmt.Ccy":                              "ReturnedInterbankSettlementAmount.Currency",
		"PmtRtr.TxInf[0].IntrBkSttlmDt":                                       "InterbankSettlementDate",
		"PmtRtr.TxInf[0].RtrdInstdAmt.Value":                                  "ReturnedInstructedAmount.Amount",
		"PmtRtr.TxInf[0].RtrdInstdAmt.Ccy":                                    "ReturnedInstructedAmount.Currency",
		"PmtRtr.TxInf[0].ChrgBr":                                              "ChargeBearer",
		"PmtRtr.TxInf[0].InstgAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd":         "InstructingAgent.PaymentSysCode",
		"PmtRtr.TxInf[0].InstgAgt.FinInstnId.ClrSysMmbId.MmbId":               "InstructingAgent.PaymentSysMemberId",
		"PmtRtr.TxInf[0].InstdAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd":         "InstructedAgent.PaymentSysCode",
		"PmtRtr.TxInf[0].InstdAgt.FinInstnId.ClrSysMmbId.MmbId":               "InstructedAgent.PaymentSysMemberId",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.Nm":                                "RtrChain.Debtor.Name",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.StrtNm":                    "RtrChain.Debtor.Address.StreetName",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.BldgNb":                    "RtrChain.Debtor.Address.BuildingNumber",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.PstCd":                     "RtrChain.Debtor.Address.PostalCode",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.TwnNm":                     "RtrChain.Debtor.Address.TownName",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.CtrySubDvsn":               "RtrChain.Debtor.Address.Subdivision",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.Ctry":                      "RtrChain.Debtor.Address.Country",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.Nm":                                "RtrChain.Creditor.Name",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.StrtNm":                    "RtrChain.Creditor.Address.StreetName",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.BldgNb":                    "RtrChain.Creditor.Address.BuildingNumber",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.PstCd":                     "RtrChain.Creditor.Address.PostalCode",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.TwnNm":                     "RtrChain.Creditor.Address.TownName",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.CtrySubDvsn":               "RtrChain.Creditor.Address.Subdivision",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.Ctry":                      "RtrChain.Creditor.Address.Country",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd": "RtrChain.DebtorAgent.PaymentSysCode",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.ClrSysMmbId.MmbId":       "RtrChain.DebtorAgent.PaymentSysMemberId",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.Nm":                      "RtrChain.DebtorAgent.BankName",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.StrtNm":          "RtrChain.DebtorAgent.PostalAddress.StreetName",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.BldgNb":          "RtrChain.DebtorAgent.PostalAddress.BuildingNumber",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.PstCd":           "RtrChain.DebtorAgent.PostalAddress.PostalCode",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.TwnNm":           "RtrChain.DebtorAgent.PostalAddress.TownName",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.CtrySubDvsn":     "RtrChain.DebtorAgent.PostalAddress.Subdivision",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.Ctry":            "RtrChain.DebtorAgent.PostalAddress.Country",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd": "RtrChain.CreditorAgent.PaymentSysCode",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.ClrSysMmbId.MmbId":       "RtrChain.CreditorAgent.PaymentSysMemberId",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.Nm":                      "RtrChain.CreditorAgent.BankName",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.StrtNm":          "RtrChain.CreditorAgent.PostalAddress.StreetName",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.BldgNb":          "RtrChain.CreditorAgent.PostalAddress.BuildingNumber",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.PstCd":           "RtrChain.CreditorAgent.PostalAddress.PostalCode",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.TwnNm":           "RtrChain.CreditorAgent.PostalAddress.TownName",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.CtrySubDvsn":     "RtrChain.CreditorAgent.PostalAddress.Subdivision",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.Ctry":            "RtrChain.CreditorAgent.PostalAddress.Country",
		"PmtRtr.TxInf[0].RtrRsnInf[0].Rsn.Cd":                                 "ReturnReasonInformation.Reason",
		"PmtRtr.TxInf[0].RtrRsnInf[0].AddtlInf[0]":                            "ReturnReasonInformation.AdditionalInfo",
		"PmtRtr.TxInf[0].OrgnlTxRef.PmtTpInf.LclInstrm.Prtry":                 "OriginalTransactionRef",
	}
}
func PathMapV9() map[string]any {
	return map[string]any{
		"PmtRtr.GrpHdr.MsgId":                                                 "MessageId",
		"PmtRtr.GrpHdr.CreDtTm":                                               "CreatedDateTime",
		"PmtRtr.GrpHdr.NbOfTxs":                                               "NumberOfTransactions",
		"PmtRtr.GrpHdr.SttlmInf.SttlmMtd":                                     "SettlementMethod",
		"PmtRtr.GrpHdr.SttlmInf.ClrSys.Cd":                                    "CommonClearingSysCode",
		"PmtRtr.TxInf[0].OrgnlGrpInf.OrgnlMsgId":                              "OriginalMessageId",
		"PmtRtr.TxInf[0].OrgnlGrpInf.OrgnlMsgNmId":                            "OriginalMessageNameId",
		"PmtRtr.TxInf[0].OrgnlGrpInf.OrgnlCreDtTm":                            "OriginalCreationDateTime",
		"PmtRtr.TxInf[0].OrgnlInstrId":                                        "OriginalInstructionId",
		"PmtRtr.TxInf[0].OrgnlEndToEndId":                                     "OriginalEndToEndId",
		"PmtRtr.TxInf[0].OrgnlUETR":                                           "OriginalUETR",
		"PmtRtr.TxInf[0].RtrdIntrBkSttlmAmt.Value":                            "ReturnedInterbankSettlementAmount.Amount",
		"PmtRtr.TxInf[0].RtrdIntrBkSttlmAmt.Ccy":                              "ReturnedInterbankSettlementAmount.Currency",
		"PmtRtr.TxInf[0].IntrBkSttlmDt":                                       "InterbankSettlementDate",
		"PmtRtr.TxInf[0].RtrdInstdAmt.Value":                                  "ReturnedInstructedAmount.Amount",
		"PmtRtr.TxInf[0].RtrdInstdAmt.Ccy":                                    "ReturnedInstructedAmount.Currency",
		"PmtRtr.TxInf[0].ChrgBr":                                              "ChargeBearer",
		"PmtRtr.TxInf[0].InstgAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd":         "InstructingAgent.PaymentSysCode",
		"PmtRtr.TxInf[0].InstgAgt.FinInstnId.ClrSysMmbId.MmbId":               "InstructingAgent.PaymentSysMemberId",
		"PmtRtr.TxInf[0].InstdAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd":         "InstructedAgent.PaymentSysCode",
		"PmtRtr.TxInf[0].InstdAgt.FinInstnId.ClrSysMmbId.MmbId":               "InstructedAgent.PaymentSysMemberId",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.Nm":                                "RtrChain.Debtor.Name",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.StrtNm":                    "RtrChain.Debtor.Address.StreetName",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.BldgNb":                    "RtrChain.Debtor.Address.BuildingNumber",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.BldgNm":                    "RtrChain.Debtor.Address.BuildingName",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.Flr":                       "RtrChain.Debtor.Address.Floor",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.Room":                      "RtrChain.Debtor.Address.RoomNumber",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.PstCd":                     "RtrChain.Debtor.Address.PostalCode",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.TwnNm":                     "RtrChain.Debtor.Address.TownName",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.CtrySubDvsn":               "RtrChain.Debtor.Address.Subdivision",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.Ctry":                      "RtrChain.Debtor.Address.Country",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.Nm":                                "RtrChain.Creditor.Name",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.StrtNm":                    "RtrChain.Creditor.Address.StreetName",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.BldgNb":                    "RtrChain.Creditor.Address.BuildingNumber",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.BldgNm":                    "RtrChain.Creditor.Address.BuildingName",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.Flr":                       "RtrChain.Creditor.Address.Floor",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.Room":                      "RtrChain.Creditor.Address.RoomNumber",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.PstCd":                     "RtrChain.Creditor.Address.PostalCode",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.TwnNm":                     "RtrChain.Creditor.Address.TownName",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.CtrySubDvsn":               "RtrChain.Creditor.Address.Subdivision",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.Ctry":                      "RtrChain.Creditor.Address.Country",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd": "RtrChain.DebtorAgent.PaymentSysCode",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.ClrSysMmbId.MmbId":       "RtrChain.DebtorAgent.PaymentSysMemberId",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.Nm":                      "RtrChain.DebtorAgent.BankName",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.StrtNm":          "RtrChain.DebtorAgent.PostalAddress.StreetName",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.BldgNb":          "RtrChain.DebtorAgent.PostalAddress.BuildingNumber",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.BldgNm":          "RtrChain.DebtorAgent.PostalAddress.BuildingName",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.Flr":             "RtrChain.DebtorAgent.PostalAddress.Floor",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.Room":            "RtrChain.DebtorAgent.PostalAddress.RoomNumber",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.PstCd":           "RtrChain.DebtorAgent.PostalAddress.PostalCode",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.TwnNm":           "RtrChain.DebtorAgent.PostalAddress.TownName",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.CtrySubDvsn":     "RtrChain.DebtorAgent.PostalAddress.Subdivision",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.Ctry":            "RtrChain.DebtorAgent.PostalAddress.Country",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd": "RtrChain.CreditorAgent.PaymentSysCode",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.ClrSysMmbId.MmbId":       "RtrChain.CreditorAgent.PaymentSysMemberId",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.Nm":                      "RtrChain.CreditorAgent.BankName",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.StrtNm":          "RtrChain.CreditorAgent.PostalAddress.StreetName",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.BldgNb":          "RtrChain.CreditorAgent.PostalAddress.BuildingNumber",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.BldgNm":          "RtrChain.CreditorAgent.PostalAddress.BuildingName",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.Flr":             "RtrChain.CreditorAgent.PostalAddress.Floor",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.Room":            "RtrChain.CreditorAgent.PostalAddress.RoomNumber",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.PstCd":           "RtrChain.CreditorAgent.PostalAddress.PostalCode",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.TwnNm":           "RtrChain.CreditorAgent.PostalAddress.TownName",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.CtrySubDvsn":     "RtrChain.CreditorAgent.PostalAddress.Subdivision",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.Ctry":            "RtrChain.CreditorAgent.PostalAddress.Country",
		"PmtRtr.TxInf[0].RtrRsnInf[0].Rsn.Cd":                                 "ReturnReasonInformation.Reason",
		"PmtRtr.TxInf[0].RtrRsnInf[0].AddtlInf[0]":                            "ReturnReasonInformation.AdditionalInfo",
		"PmtRtr.TxInf[0].OrgnlTxRef.PmtTpInf.LclInstrm.Prtry":                 "OriginalTransactionRef",
	}
}
func PathMapV10() map[string]any {
	return map[string]any{
		"PmtRtr.GrpHdr.MsgId":                                                 "MessageId",
		"PmtRtr.GrpHdr.CreDtTm":                                               "CreatedDateTime",
		"PmtRtr.GrpHdr.NbOfTxs":                                               "NumberOfTransactions",
		"PmtRtr.GrpHdr.SttlmInf.SttlmMtd":                                     "SettlementMethod",
		"PmtRtr.GrpHdr.SttlmInf.ClrSys.Cd":                                    "CommonClearingSysCode",
		"PmtRtr.TxInf[0].OrgnlGrpInf.OrgnlMsgId":                              "OriginalMessageId",
		"PmtRtr.TxInf[0].OrgnlGrpInf.OrgnlMsgNmId":                            "OriginalMessageNameId",
		"PmtRtr.TxInf[0].OrgnlGrpInf.OrgnlCreDtTm":                            "OriginalCreationDateTime",
		"PmtRtr.TxInf[0].OrgnlInstrId":                                        "OriginalInstructionId",
		"PmtRtr.TxInf[0].OrgnlEndToEndId":                                     "OriginalEndToEndId",
		"PmtRtr.TxInf[0].OrgnlUETR":                                           "OriginalUETR",
		"PmtRtr.TxInf[0].RtrdIntrBkSttlmAmt.Value":                            "ReturnedInterbankSettlementAmount.Amount",
		"PmtRtr.TxInf[0].RtrdIntrBkSttlmAmt.Ccy":                              "ReturnedInterbankSettlementAmount.Currency",
		"PmtRtr.TxInf[0].IntrBkSttlmDt":                                       "InterbankSettlementDate",
		"PmtRtr.TxInf[0].RtrdInstdAmt.Value":                                  "ReturnedInstructedAmount.Amount",
		"PmtRtr.TxInf[0].RtrdInstdAmt.Ccy":                                    "ReturnedInstructedAmount.Currency",
		"PmtRtr.TxInf[0].ChrgBr":                                              "ChargeBearer",
		"PmtRtr.TxInf[0].InstgAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd":         "InstructingAgent.PaymentSysCode",
		"PmtRtr.TxInf[0].InstgAgt.FinInstnId.ClrSysMmbId.MmbId":               "InstructingAgent.PaymentSysMemberId",
		"PmtRtr.TxInf[0].InstdAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd":         "InstructedAgent.PaymentSysCode",
		"PmtRtr.TxInf[0].InstdAgt.FinInstnId.ClrSysMmbId.MmbId":               "InstructedAgent.PaymentSysMemberId",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.Nm":                                "RtrChain.Debtor.Name",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.StrtNm":                    "RtrChain.Debtor.Address.StreetName",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.BldgNb":                    "RtrChain.Debtor.Address.BuildingNumber",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.BldgNm":                    "RtrChain.Debtor.Address.BuildingName",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.Flr":                       "RtrChain.Debtor.Address.Floor",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.Room":                      "RtrChain.Debtor.Address.RoomNumber",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.PstCd":                     "RtrChain.Debtor.Address.PostalCode",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.TwnNm":                     "RtrChain.Debtor.Address.TownName",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.CtrySubDvsn":               "RtrChain.Debtor.Address.Subdivision",
		"PmtRtr.TxInf[0].RtrChain.Dbtr.Pty.PstlAdr.Ctry":                      "RtrChain.Debtor.Address.Country",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.Nm":                                "RtrChain.Creditor.Name",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.StrtNm":                    "RtrChain.Creditor.Address.StreetName",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.BldgNb":                    "RtrChain.Creditor.Address.BuildingNumber",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.BldgNm":                    "RtrChain.Creditor.Address.BuildingName",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.Flr":                       "RtrChain.Creditor.Address.Floor",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.Room":                      "RtrChain.Creditor.Address.RoomNumber",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.PstCd":                     "RtrChain.Creditor.Address.PostalCode",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.TwnNm":                     "RtrChain.Creditor.Address.TownName",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.CtrySubDvsn":               "RtrChain.Creditor.Address.Subdivision",
		"PmtRtr.TxInf[0].RtrChain.Cdtr.Pty.PstlAdr.Ctry":                      "RtrChain.Creditor.Address.Country",
		"PmtRtr.TxInf[0].RtrChain.DbtrAcct.Id.Othr.Id":                        "RtrChain.DebtorOtherTypeId",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd": "RtrChain.DebtorAgent.PaymentSysCode",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.ClrSysMmbId.MmbId":       "RtrChain.DebtorAgent.PaymentSysMemberId",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.Nm":                      "RtrChain.DebtorAgent.BankName",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.StrtNm":          "RtrChain.DebtorAgent.PostalAddress.StreetName",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.BldgNb":          "RtrChain.DebtorAgent.PostalAddress.BuildingNumber",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.BldgNm":          "RtrChain.DebtorAgent.PostalAddress.BuildingName",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.Flr":             "RtrChain.DebtorAgent.PostalAddress.Floor",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.Room":            "RtrChain.DebtorAgent.PostalAddress.RoomNumber",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.PstCd":           "RtrChain.DebtorAgent.PostalAddress.PostalCode",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.TwnNm":           "RtrChain.DebtorAgent.PostalAddress.TownName",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.CtrySubDvsn":     "RtrChain.DebtorAgent.PostalAddress.Subdivision",
		"PmtRtr.TxInf[0].RtrChain.DbtrAgt.FinInstnId.PstlAdr.Ctry":            "RtrChain.DebtorAgent.PostalAddress.Country",
		"PmtRtr.TxInf[0].RtrChain.CdtrAcct.Id.Othr.Id":                        "RtrChain.CreditorAccountOtherTypeId",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd": "RtrChain.CreditorAgent.PaymentSysCode",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.ClrSysMmbId.MmbId":       "RtrChain.CreditorAgent.PaymentSysMemberId",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.Nm":                      "RtrChain.CreditorAgent.BankName",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.StrtNm":          "RtrChain.CreditorAgent.PostalAddress.StreetName",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.BldgNb":          "RtrChain.CreditorAgent.PostalAddress.BuildingNumber",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.BldgNm":          "RtrChain.CreditorAgent.PostalAddress.BuildingName",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.Flr":             "RtrChain.CreditorAgent.PostalAddress.Floor",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.Room":            "RtrChain.CreditorAgent.PostalAddress.RoomNumber",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.PstCd":           "RtrChain.CreditorAgent.PostalAddress.PostalCode",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.TwnNm":           "RtrChain.CreditorAgent.PostalAddress.TownName",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.CtrySubDvsn":     "RtrChain.CreditorAgent.PostalAddress.Subdivision",
		"PmtRtr.TxInf[0].RtrChain.CdtrAgt.FinInstnId.PstlAdr.Ctry":            "RtrChain.CreditorAgent.PostalAddress.Country",
		"PmtRtr.TxInf[0].RtrRsnInf[0].Rsn.Cd":                                 "ReturnReasonInformation.Reason",
		"PmtRtr.TxInf[0].RtrRsnInf[0].AddtlInf[0]":                            "ReturnReasonInformation.AdditionalInfo",
		"PmtRtr.TxInf[0].OrgnlTxRef.PmtTpInf.LclInstrm.Prtry":                 "OriginalTransactionRef",
	}
}
func PathMapV11() map[string]any {
	return PathMapV10()
}
func PathMapV12() map[string]any {
	return PathMapV10()
}
func PathMapV13() map[string]any {
	return PathMapV10()
}
