package DrawdownRequest

func PathMapV1() map[string]string {
	return map[string]string{
		"CstmrDrctDbtInitn.GrpHdr.MsgId":                                                      "MessageId",
		"CstmrDrctDbtInitn.GrpHdr.CreDtTm":                                                    "CreateDatetime",
		"CstmrDrctDbtInitn.GrpHdr.NbOfTxs":                                                    "NumberofTransaction",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.Nm":                                                "InitiatingParty.Name",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.StrtNm":                                    "InitiatingParty.Address.StreetName",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.BldgNb":                                    "InitiatingParty.Address.BuildingNumber",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.PstCd":                                     "InitiatingParty.Address.PostalCode",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.TwnNm":                                     "InitiatingParty.Address.TownName",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.CtrySubDvsn":                               "InitiatingParty.Address.Subdivision",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.Ctry":                                      "InitiatingParty.Address.Country",
		"CstmrDrctDbtInitn.PmtInf[0].PmtInfId":                                                "PaymentInfoId",
		"CstmrDrctDbtInitn.PmtInf[0].PmtMtd":                                                  "PaymentMethod",
		"CstmrDrctDbtInitn.PmtInf[0].ReqdExctnDt":                                             "RequestedExecutDate",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.Nm":                                                 "Debtor.Name",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.StrtNm":                                     "Debtor.Address.StreetName",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.BldgNb":                                     "Debtor.Address.BuildingNumber",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.PstCd":                                      "Debtor.Address.PostalCode",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.TwnNm":                                      "Debtor.Address.TownName",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.CtrySubDvsn":                                "Debtor.Address.Subdivision",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.Ctry":                                       "Debtor.Address.Country",
		"CstmrDrctDbtInitn.PmtInf[0].DbtrAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd":              "DebtorAgent.PaymentSysCode",
		"CstmrDrctDbtInitn.PmtInf[0].DbtrAgt.FinInstnId.ClrSysMmbId.MmbId":                    "DebtorAgent.PaymentSysMemberId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].PmtId.InstrId":                               "CreditTransTransaction.PaymentInstructionId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].PmtId.EndToEndId":                            "CreditTransTransaction.PaymentEndToEndId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].PmtTpInf.LclInstrm.Prtry":                    "CreditTransTransaction.PayRequestType",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].PmtTpInf.CtgyPurp.Cd":                        "CreditTransTransaction.PayCategoryType",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Amt.InstdAmt.Value":                          "CreditTransTransaction.Amount.Amount",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Amt.InstdAmt.Ccy":                            "CreditTransTransaction.Amount.Currency",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].ChrgBr":                                      "CreditTransTransaction.ChargeBearer",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].CdtrAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd":  "CreditTransTransaction.CreditorAgent.PaymentSysCode",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].CdtrAgt.FinInstnId.ClrSysMmbId.MmbId":        "CreditTransTransaction.CreditorAgent.PaymentSysMemberId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.Nm":                                     "CreditTransTransaction.Creditor.Name",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.StrtNm":                         "CreditTransTransaction.Creditor.Address.StreetName",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.BldgNb":                         "CreditTransTransaction.Creditor.Address.BuildingNumber",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.PstCd":                          "CreditTransTransaction.Creditor.Address.PostalCode",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.TwnNm":                          "CreditTransTransaction.Creditor.Address.TownName",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.CtrySubDvsn":                    "CreditTransTransaction.Creditor.Address.Subdivision",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.Ctry":                           "CreditTransTransaction.Creditor.Address.Country",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].CdtrAcct.Id.Othr.Id":                         "CreditTransTransaction.CrediorAccountOtherId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].RmtInf.Ustrd[0]":                             "CreditTransTransaction.RemittanceInformation",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].RmtInf.Strd[0].RfrdDocInf[0].Tp.CdOrPrtry.Cd": "CreditTransTransaction.Document.CodeOrProprietary",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].RmtInf.Strd[0].RfrdDocInf[0].Nb":             "CreditTransTransaction.Document.Number",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].RmtInf.Strd[0].RfrdDocInf[0].RltdDt":         "CreditTransTransaction.Document.RelatedDate",
	}
}
func PathMapV2() map[string]string {
	return PathMapV5()
}
func PathMapV3() map[string]string {
	return PathMapV5()
}
func PathMapV4() map[string]string {
	return PathMapV5()
}
func PathMapV5() map[string]string {
	return map[string]string{
		"CstmrDrctDbtInitn.GrpHdr.MsgId":                                                       "MessageId",
		"CstmrDrctDbtInitn.GrpHdr.CreDtTm":                                                     "CreateDatetime",
		"CstmrDrctDbtInitn.GrpHdr.NbOfTxs":                                                     "NumberofTransaction",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.Nm":                                                 "InitiatingParty.Name",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.StrtNm":                                     "InitiatingParty.Address.StreetName",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.BldgNb":                                     "InitiatingParty.Address.BuildingNumber",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.PstCd":                                      "InitiatingParty.Address.PostalCode",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.TwnNm":                                      "InitiatingParty.Address.TownName",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.CtrySubDvsn":                                "InitiatingParty.Address.Subdivision",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.Ctry":                                       "InitiatingParty.Address.Country",
		"CstmrDrctDbtInitn.PmtInf[0].PmtInfId":                                                 "PaymentInfoId",
		"CstmrDrctDbtInitn.PmtInf[0].PmtMtd":                                                   "PaymentMethod",
		"CstmrDrctDbtInitn.PmtInf[0].ReqdExctnDt":                                              "RequestedExecutDate",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.Nm":                                                  "Debtor.Name",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.StrtNm":                                      "Debtor.Address.StreetName",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.BldgNb":                                      "Debtor.Address.BuildingNumber",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.PstCd":                                       "Debtor.Address.PostalCode",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.TwnNm":                                       "Debtor.Address.TownName",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.CtrySubDvsn":                                 "Debtor.Address.Subdivision",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.Ctry":                                        "Debtor.Address.Country",
		"CstmrDrctDbtInitn.PmtInf[0].DbtrAcct.Id.Othr.Id":                                      "DebtorAccountOtherId",
		"CstmrDrctDbtInitn.PmtInf[0].DbtrAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd":               "DebtorAgent.PaymentSysCode",
		"CstmrDrctDbtInitn.PmtInf[0].DbtrAgt.FinInstnId.ClrSysMmbId.MmbId":                     "DebtorAgent.PaymentSysMemberId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].PmtId.InstrId":                                "CreditTransTransaction.PaymentInstructionId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].PmtId.EndToEndId":                             "CreditTransTransaction.PaymentEndToEndId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].PmtTpInf.LclInstrm.Prtry":                     "CreditTransTransaction.PayRequestType",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].PmtTpInf.CtgyPurp.Cd":                         "CreditTransTransaction.PayCategoryType",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Amt.InstdAmt.Value":                           "CreditTransTransaction.Amount.Amount",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Amt.InstdAmt.Ccy":                             "CreditTransTransaction.Amount.Currency",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].ChrgBr":                                       "CreditTransTransaction.ChargeBearer",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].CdtrAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd":   "CreditTransTransaction.CreditorAgent.PaymentSysCode",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].CdtrAgt.FinInstnId.ClrSysMmbId.MmbId":         "CreditTransTransaction.CreditorAgent.PaymentSysMemberId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.Nm":                                      "CreditTransTransaction.Creditor.Name",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.StrtNm":                          "CreditTransTransaction.Creditor.Address.StreetName",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.BldgNb":                          "CreditTransTransaction.Creditor.Address.BuildingNumber",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.PstCd":                           "CreditTransTransaction.Creditor.Address.PostalCode",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.TwnNm":                           "CreditTransTransaction.Creditor.Address.TownName",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.CtrySubDvsn":                     "CreditTransTransaction.Creditor.Address.Subdivision",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.Ctry":                            "CreditTransTransaction.Creditor.Address.Country",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].CdtrAcct.Id.Othr.Id":                          "CreditTransTransaction.CrediorAccountOtherId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].RmtInf.Ustrd[0]":                              "CreditTransTransaction.RemittanceInformation",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].RmtInf.Strd[0].RfrdDocInf[0].Tp.CdOrPrtry.Cd": "CreditTransTransaction.Document.CodeOrProprietary",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].RmtInf.Strd[0].RfrdDocInf[0].Nb":              "CreditTransTransaction.Document.Number",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].RmtInf.Strd[0].RfrdDocInf[0].RltdDt":          "CreditTransTransaction.Document.RelatedDate",
	}
}
func PathMapV6() map[string]string {
	return map[string]string{
		"CstmrDrctDbtInitn.GrpHdr.MsgId":                                                       "MessageId",
		"CstmrDrctDbtInitn.GrpHdr.CreDtTm":                                                     "CreateDatetime",
		"CstmrDrctDbtInitn.GrpHdr.NbOfTxs":                                                     "NumberofTransaction",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.Nm":                                                 "InitiatingParty.Name",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.StrtNm":                                     "InitiatingParty.Address.StreetName",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.BldgNb":                                     "InitiatingParty.Address.BuildingNumber",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.PstCd":                                      "InitiatingParty.Address.PostalCode",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.TwnNm":                                      "InitiatingParty.Address.TownName",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.CtrySubDvsn":                                "InitiatingParty.Address.Subdivision",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.Ctry":                                       "InitiatingParty.Address.Country",
		"CstmrDrctDbtInitn.PmtInf[0].PmtInfId":                                                 "PaymentInfoId",
		"CstmrDrctDbtInitn.PmtInf[0].PmtMtd":                                                   "PaymentMethod",
		"CstmrDrctDbtInitn.PmtInf[0].ReqdExctnDt.Dt":                                           "RequestedExecutDate",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.Nm":                                                  "Debtor.Name",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.StrtNm":                                      "Debtor.Address.StreetName",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.BldgNb":                                      "Debtor.Address.BuildingNumber",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.PstCd":                                       "Debtor.Address.PostalCode",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.TwnNm":                                       "Debtor.Address.TownName",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.CtrySubDvsn":                                 "Debtor.Address.Subdivision",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.Ctry":                                        "Debtor.Address.Country",
		"CstmrDrctDbtInitn.PmtInf[0].DbtrAcct.Id.Othr.Id":                                      "DebtorAccountOtherId",
		"CstmrDrctDbtInitn.PmtInf[0].DbtrAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd":               "DebtorAgent.PaymentSysCode",
		"CstmrDrctDbtInitn.PmtInf[0].DbtrAgt.FinInstnId.ClrSysMmbId.MmbId":                     "DebtorAgent.PaymentSysMemberId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].PmtId.InstrId":                                "CreditTransTransaction.PaymentInstructionId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].PmtId.EndToEndId":                             "CreditTransTransaction.PaymentEndToEndId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].PmtTpInf.LclInstrm.Prtry":                     "CreditTransTransaction.PayRequestType",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].PmtTpInf.CtgyPurp.Cd":                         "CreditTransTransaction.PayCategoryType",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Amt.InstdAmt.Value":                           "CreditTransTransaction.Amount.Amount",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Amt.InstdAmt.Ccy":                             "CreditTransTransaction.Amount.Currency",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].ChrgBr":                                       "CreditTransTransaction.ChargeBearer",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].CdtrAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd":   "CreditTransTransaction.CreditorAgent.PaymentSysCode",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].CdtrAgt.FinInstnId.ClrSysMmbId.MmbId":         "CreditTransTransaction.CreditorAgent.PaymentSysMemberId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.Nm":                                      "CreditTransTransaction.Creditor.Name",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.StrtNm":                          "CreditTransTransaction.Creditor.Address.StreetName",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.BldgNb":                          "CreditTransTransaction.Creditor.Address.BuildingNumber",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.PstCd":                           "CreditTransTransaction.Creditor.Address.PostalCode",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.TwnNm":                           "CreditTransTransaction.Creditor.Address.TownName",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.CtrySubDvsn":                     "CreditTransTransaction.Creditor.Address.Subdivision",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.Ctry":                            "CreditTransTransaction.Creditor.Address.Country",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].CdtrAcct.Id.Othr.Id":                          "CreditTransTransaction.CrediorAccountOtherId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].RmtInf.Ustrd[0]":                              "CreditTransTransaction.RemittanceInformation",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].RmtInf.Strd[0].RfrdDocInf[0].Tp.CdOrPrtry.Cd": "CreditTransTransaction.Document.CodeOrProprietary",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].RmtInf.Strd[0].RfrdDocInf[0].Nb":              "CreditTransTransaction.Document.Number",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].RmtInf.Strd[0].RfrdDocInf[0].RltdDt":          "CreditTransTransaction.Document.RelatedDate",
	}
}
func PathMapV7() map[string]string {
	return map[string]string{
		"CstmrDrctDbtInitn.GrpHdr.MsgId":                                                       "MessageId",
		"CstmrDrctDbtInitn.GrpHdr.CreDtTm":                                                     "CreateDatetime",
		"CstmrDrctDbtInitn.GrpHdr.NbOfTxs":                                                     "NumberofTransaction",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.Nm":                                                 "InitiatingParty.Name",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.StrtNm":                                     "InitiatingParty.Address.StreetName",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.BldgNb":                                     "InitiatingParty.Address.BuildingNumber",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.Room":                                       "InitiatingParty.Address.RoomNumber",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.PstCd":                                      "InitiatingParty.Address.PostalCode",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.TwnNm":                                      "InitiatingParty.Address.TownName",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.CtrySubDvsn":                                "InitiatingParty.Address.Subdivision",
		"CstmrDrctDbtInitn.GrpHdr.InitgPty.PstlAdr.Ctry":                                       "InitiatingParty.Address.Country",
		"CstmrDrctDbtInitn.PmtInf[0].PmtInfId":                                                 "PaymentInfoId",
		"CstmrDrctDbtInitn.PmtInf[0].PmtMtd":                                                   "PaymentMethod",
		"CstmrDrctDbtInitn.PmtInf[0].ReqdExctnDt.Dt":                                           "RequestedExecutDate",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.Nm":                                                  "Debtor.Name",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.StrtNm":                                      "Debtor.Address.StreetName",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.BldgNb":                                      "Debtor.Address.BuildingNumber",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.Room":                                        "Debtor.Address.RoomNumber",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.PstCd":                                       "Debtor.Address.PostalCode",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.TwnNm":                                       "Debtor.Address.TownName",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.CtrySubDvsn":                                 "Debtor.Address.Subdivision",
		"CstmrDrctDbtInitn.PmtInf[0].Dbtr.PstlAdr.Ctry":                                        "Debtor.Address.Country",
		"CstmrDrctDbtInitn.PmtInf[0].DbtrAcct.Id.Othr.Id":                                      "DebtorAccountOtherId",
		"CstmrDrctDbtInitn.PmtInf[0].DbtrAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd":               "DebtorAgent.PaymentSysCode",
		"CstmrDrctDbtInitn.PmtInf[0].DbtrAgt.FinInstnId.ClrSysMmbId.MmbId":                     "DebtorAgent.PaymentSysMemberId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].PmtId.InstrId":                                "CreditTransTransaction.PaymentInstructionId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].PmtId.EndToEndId":                             "CreditTransTransaction.PaymentEndToEndId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].PmtId.UETR":                                   "CreditTransTransaction.PaymentUniqueId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].PmtTpInf.LclInstrm.Prtry":                     "CreditTransTransaction.PayRequestType",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].PmtTpInf.CtgyPurp.Cd":                         "CreditTransTransaction.PayCategoryType",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Amt.InstdAmt.Value":                           "CreditTransTransaction.Amount.Amount",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Amt.InstdAmt.Ccy":                             "CreditTransTransaction.Amount.Currency",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].ChrgBr":                                       "CreditTransTransaction.ChargeBearer",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].CdtrAgt.FinInstnId.ClrSysMmbId.ClrSysId.Cd":   "CreditTransTransaction.CreditorAgent.PaymentSysCode",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].CdtrAgt.FinInstnId.ClrSysMmbId.MmbId":         "CreditTransTransaction.CreditorAgent.PaymentSysMemberId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.Nm":                                      "CreditTransTransaction.Creditor.Name",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.StrtNm":                          "CreditTransTransaction.Creditor.Address.StreetName",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.BldgNb":                          "CreditTransTransaction.Creditor.Address.BuildingNumber",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.Room":                            "CreditTransTransaction.Creditor.Address.RoomNumber",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.PstCd":                           "CreditTransTransaction.Creditor.Address.PostalCode",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.TwnNm":                           "CreditTransTransaction.Creditor.Address.TownName",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.CtrySubDvsn":                     "CreditTransTransaction.Creditor.Address.Subdivision",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].Cdtr.PstlAdr.Ctry":                            "CreditTransTransaction.Creditor.Address.Country",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].CdtrAcct.Id.Othr.Id":                          "CreditTransTransaction.CrediorAccountOtherId",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].RmtInf.Ustrd[0]":                              "CreditTransTransaction.RemittanceInformation",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].RmtInf.Strd[0].RfrdDocInf[0].Tp.CdOrPrtry.Cd": "CreditTransTransaction.Document.CodeOrProprietary",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].RmtInf.Strd[0].RfrdDocInf[0].Nb":              "CreditTransTransaction.Document.Number",
		"CstmrDrctDbtInitn.PmtInf[0].CdtTrfTx[0].RmtInf.Strd[0].RfrdDocInf[0].RltdDt":          "CreditTransTransaction.Document.RelatedDate",
	}
}
func PathMapV8() map[string]string {
	return PathMapV7()
}
func PathMapV9() map[string]string {
	return PathMapV7()
}
func PathMapV10() map[string]string {
	return PathMapV7()
}
