package DrawdownRequest

import (
	"encoding/xml"
	"time"

	pain013 "github.com/moov-io/fedwire20022/gen/DrawdownRequest_pain_013_001_07"
	"github.com/moov-io/fedwire20022/pkg/fedwire"
	model "github.com/moov-io/wire20022/pkg/models"
)

const XMLINS string = "urn:iso:std:iso:20022:tech:xsd:pain.013.001.07"

type MessageModel struct {
	//A unique identifier (IMADFedwireFunds1) assigned to the message.
	MessageId string
	//The creation date and time (ISODateTime) of the message.
	CreateDatetime time.Time
	//The total number of transactions (Max15NumericTextFixed) included in the message.
	NumberofTransaction string
	//In the Fedwire Funds Service, this is a person or entity that requests a drawdown.
	InitiatingParty model.PartyIdentify

	//Reference assigned by a sending party to unambiguously identify the payment information block within the message.
	PaymentInfoId string
	//Specifies the means of payment that will be used to move the amount of money.
	PaymentMethod PaymentMethod
	//Date at which the initiating party requests the clearing agent to process the payment. If payment by cheque, the date when the cheque must be generated by the bank.
	RequestedExecutDate model.Date
	//Party that owes an amount of money to the (ultimate) creditor.
	Debtor model.PartyIdentify
	//This is the account that will be debited by the debtor agent if the drawdown request is honored.
	DebtorAccountOtherId string
	//Financial institution servicing an account for the debtor.
	DebtorAgent model.Agent
	//Payment processes required to transfer cash from the debtor to the creditor.
	CreditTransTransaction CreditTransferTransaction
}
type Message struct {
	data MessageModel
	doc  pain013.Document
}

/*
NewMessage creates a new Message instance with optional XML initialization.

Parameters:
  - filepath: File path to XML (optional)
    If provided, loads and parses XML from specified path

Returns:
  - Message: Initialized message structure
  - error: File read or XML parsing errors (if XML path provided)

Behavior:
  - Without arguments: Returns empty Message with default MessageModel
  - With XML path: Loads file, parses XML into message.doc
*/
func NewMessage(filepath string) (Message, error) {
	if filepath != "" {
		data, err := model.ReadXMLFile(filepath)
		if err != nil {
			return Message{}, err
		}
		msg := Message{}
		xml.Unmarshal(data, &msg.doc)
		return msg, nil
	}
	return Message{
		data: MessageModel{},
	}, nil
}
func (msg *Message) CreateDocument() *model.ValidateError {
	msg.doc = pain013.Document{
		XMLName: xml.Name{
			Space: XMLINS,
			Local: "Document",
		},
	}
	var CdtrPmtActvtnReq pain013.CreditorPaymentActivationRequestV07
	var GrpHdr pain013.GroupHeader781
	if msg.data.MessageId != "" {
		err := pain013.IMADFedwireFunds1(msg.data.MessageId).Validate()
		if err != nil {
			return &model.ValidateError{
				ParamName: "MessageId",
				Message:   err.Error(),
			}
		}
		GrpHdr.MsgId = pain013.IMADFedwireFunds1(msg.data.MessageId)
	}
	if !isEmpty(msg.data.CreateDatetime) {
		err := fedwire.ISODateTime(msg.data.CreateDatetime).Validate()
		if err != nil {
			return &model.ValidateError{
				ParamName: "CreateDatetime",
				Message:   err.Error(),
			}
		}
		GrpHdr.CreDtTm = fedwire.ISODateTime(msg.data.CreateDatetime)
	}
	if msg.data.NumberofTransaction != "" {
		err := pain013.Max15NumericTextFixed(msg.data.NumberofTransaction).Validate()
		if err != nil {
			return &model.ValidateError{
				ParamName: "NumberofTransaction",
				Message:   err.Error(),
			}
		}
		GrpHdr.NbOfTxs = pain013.Max15NumericTextFixed(msg.data.NumberofTransaction)
	}
	if !isEmpty(msg.data.InitiatingParty) {
		InitgPty, vErr := PartyIdentification1351From(msg.data.InitiatingParty)
		if vErr != nil {
			vErr.InsertPath("InitiatingParty")
			return vErr
		}
		GrpHdr.InitgPty = InitgPty
	}
	if !isEmpty(GrpHdr) {
		CdtrPmtActvtnReq.GrpHdr = GrpHdr
	}
	var PmtInf pain013.PaymentInstruction311
	if msg.data.PaymentInfoId != "" {
		err := pain013.Max35Text(msg.data.PaymentInfoId).Validate()
		if err != nil {
			return &model.ValidateError{
				ParamName: "PaymentInfoId",
				Message:   err.Error(),
			}
		}
		PmtInf.PmtInfId = pain013.Max35Text(msg.data.PaymentInfoId)
	}
	if msg.data.PaymentMethod != "" {
		err := pain013.PaymentMethod7Code1(msg.data.PaymentMethod).Validate()
		if err != nil {
			return &model.ValidateError{
				ParamName: "PaymentMethod",
				Message:   err.Error(),
			}
		}
		PmtInf.PmtMtd = pain013.PaymentMethod7Code1(msg.data.PaymentMethod)
	}
	if !isEmpty(msg.data.RequestedExecutDate) {
		err := msg.data.RequestedExecutDate.Date().Validate()
		if err != nil {
			return &model.ValidateError{
				ParamName: "RequestedExecutDate",
				Message:   err.Error(),
			}
		}
		Dt := msg.data.RequestedExecutDate.Date()
		PmtInf.ReqdExctnDt = pain013.DateAndDateTime2Choice1{
			Dt: &Dt,
		}
	}
	if !isEmpty(msg.data.Debtor) {
		Dbtr, vErr := PartyIdentification1352From(msg.data.Debtor)
		if vErr != nil {
			vErr.InsertPath("Debtor")
			return vErr
		}
		PmtInf.Dbtr = Dbtr
	}
	if msg.data.DebtorAccountOtherId != "" {
		err := pain013.Max34Text(msg.data.DebtorAccountOtherId).Validate()
		if err != nil {
			return &model.ValidateError{
				ParamName: "DebtorAccountOtherId",
				Message:   err.Error(),
			}
		}
		Othr := pain013.GenericAccountIdentification1{
			Id: pain013.Max34Text(msg.data.DebtorAccountOtherId),
		}
		DbtrAcct := pain013.CashAccount38{
			Id: pain013.AccountIdentification4Choice{
				Othr: &Othr,
			},
		}
		PmtInf.DbtrAcct = &DbtrAcct
	}
	if !isEmpty(msg.data.DebtorAgent) {
		err := pain013.ExternalClearingSystemIdentification1CodeFixed(msg.data.DebtorAgent.PaymentSysCode).Validate()
		if err != nil {
			vErr := model.ValidateError{
				ParamName: "PaymentSysCode",
				Message:   err.Error(),
			}
			vErr.InsertPath("DebtorAgent")
			return &vErr
		}
		err = pain013.RoutingNumberFRS1(msg.data.DebtorAgent.PaymentSysMemberId).Validate()
		if err != nil {
			vErr := model.ValidateError{
				ParamName: "PaymentSysMemberId",
				Message:   err.Error(),
			}
			vErr.InsertPath("DebtorAgent")
			return &vErr
		}
		Cd := pain013.ExternalClearingSystemIdentification1CodeFixed(msg.data.DebtorAgent.PaymentSysCode)
		DbtrAgt := pain013.BranchAndFinancialInstitutionIdentification61{
			FinInstnId: pain013.FinancialInstitutionIdentification181{
				ClrSysMmbId: pain013.ClearingSystemMemberIdentification21{
					ClrSysId: pain013.ClearingSystemIdentification2Choice1{
						Cd: &Cd,
					},
					MmbId: pain013.RoutingNumberFRS1(msg.data.DebtorAgent.PaymentSysMemberId),
				},
			},
		}
		PmtInf.DbtrAgt = DbtrAgt
	}
	if !isEmpty(msg.data.CreditTransTransaction) {
		CdtTrfTx, vErr := CreditTransferTransaction351From(msg.data.CreditTransTransaction)
		if vErr != nil {
			vErr.InsertPath("CreditTransTransaction")
			return vErr
		}
		PmtInf.CdtTrfTx = CdtTrfTx
	}
	if !isEmpty(PmtInf) {
		CdtrPmtActvtnReq.PmtInf = PmtInf
	}
	if !isEmpty(CdtrPmtActvtnReq) {
		msg.doc.CdtrPmtActvtnReq = CdtrPmtActvtnReq
	}
	return nil
}
