name: 'CI'

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request: {}

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  detect_changes:
    name: Detect file changes
    runs-on: ubuntu-latest
    outputs:
      go_changes: ${{ steps.go_changes.outputs.src }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: go_changes
        with:
          filters: |
            src:
              - go.mod
              - '**/*.go'

  go:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.go_changes == 'true' }}
    uses: ./.github/workflows/go.yml
    name: Go Tests
    secrets: inherit

  golangci-lint:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.go_changes == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: golangci/golangci-lint-action@v7
        with:
          version: v1.57.2
          args: --timeout=5m --out-format=github-actions

  codeql:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.go_changes == 'true' }}
    uses: ./.github/workflows/codeql.yaml
    name: CodeQL Analysis
    secrets: inherit